### ISSUE TITLE
Expression to calculate the angle between two vectors

### ISSUE THREAD

**Issue by mgutekunst** [Microsoft/WindowsUIDevLabs#101]
Hi, 
In your [answer](https://twitter.com/WindowsUI/status/740946739364954112) to my tweet you asked me to open an issue. So here it is. 

Original message: 
Hi WindowsUI, do you by chance have a ready to use example to calculate the angle between two Vectors using an ExpressionAnimation?

**Comment by patsiu** [comment]
Hey @mgutekunst, thanks for reaching out with your question! We do not have a sample that explicitly does what your asking for, but let me try provide you all the stuff you need. Out of curiosity, what are you planning on using this operation for?

The general formula for calculating the angle between two vectors A and B is:
**Cos(θ)=( (A ∙B) ) / ( ||A|| * ||B|| )**, where **A ∙B** is the dot product and **||A||** and **||B||** is the length of each vector (Not sure if you're already aware of the formula but in case you are not :) ). One thing to note is that we do not have an inbox Dot Product function for Expressions (it's on our To-Do list for the future), but we do have length and ArcCosine. So you will need to calculate the Dot Product manually where **Dot(A,B) = (A.X * B.X) + (A.Y*B.Y) + (A.Z * B.Z)**.

Thus when translating this into an Expression animation, simply take the ArcCos of the dot product divided by the product of the lengths - this is what you will input into Expression string portion:
**ACos( ( (A.X * B.X) + (A.Y*B.Y) + (A.Z * B.Z) ) / ( Length(A) * Length(B) ) )**. The output of this expression will be the angle between the vectors A and B in radians.

Hope this helps!

**Comment by mgutekunst** [comment]
Hi @patsiu, 
thanks for answering. In fact I already tried the formula you described but it's not working in any scenario. 

I've got several randomly moving ellipses (they're moving using an Scalar3Animation on their Offset) which I need to link for a specific period of time while they're moving. 
I was able to create a line sprite whose length is calculated using an expression. Also the line is sticked to one of the two connected ellipses using another expression animation. To actually connect two ellipses I need to change the angle of the created line and that's where I need your help. 

My current solution uses a DispatcherTimer where I calculate the ange using Atan2 which works somehow. Unfortunately there's no expression function for Atan2. 

I probably need to take the relative positions of the ellipses to each other into account but I'm a bit lost here. I've added a screenshot to show my current problem. 
![unbenannt](https://cloud.githubusercontent.com/assets/1259672/16006530/e52acd0a-316d-11e6-9399-85aa359d1a34.png)

**Comment by patsiu** [comment]
Hey @mgutekunst, I'm trying to piece together what you're trying to do, so I have a few questions:

1. Overall, are you simply trying to assign the angle between the two Ellipses Offset values to the rotation angle of the line sprite?
2. You mentioned you tried the formula - I assume you attached it to the Rotation angle property of the line sprite with an expression? When you say it didn't work, what was the outputted behavior of the Expression Animation?
3. Visually, how is the line connected with the Ellipses? Is it connected at a specific point? Sit tangentially between each Sprite?

**Comment by mgutekunst** [comment]
Hi, 
thanks for your help so far. 

1. yes, thats exactly what I'm trying to do. 
2. Yes I used an Expression animation to set the angle of the line. Here's the code that's creating the animation
```csharp
var rotationAnimation = _compositor.CreateExpressionAnimation();
rotationAnimation.SetReferenceParameter("A", visual1);
rotationAnimation.SetReferenceParameter("B", visual2);

rotationAnimation.Expression = "ACos( ( (A.Offset.X * B.Offset.X) + (A.Offset.Y*B.Offset.Y) + (A.Offset.Z * B.Offset.Z) ) / ( Length(A.Offset) * Length(B.Offset) ) )";

_line.StartAnimation(nameof(_line.RotationAngle), rotationAnimation);
```
The problem here is that the line as always drawn downwards and does not take the relative positions of the ellipses to each other into account. For example `visual1` could be above/below and left/right of `visual 2`
3. the line should connect the ellipses centers but that should be possible by simply adding the radius of the ellipses to the Offset in the above formula. Or am I mistaken?

**Comment by patsiu** [comment]
Gotcha - thanks for clarifying. 

A few things that I'm seeing:

- The equation above will rotate the line visual when the offset of A or B changes - so I haven't been able to repro what you've been seeing where the line doesn't move at all? On the side, how are the visuals (A/B) being moved?
- Also as the ellipses move around, how do you ensure the length of the line remains long enough to connect the two centers?
- The equation also won't rotate the line Visual correctly when the offsets of A and B change -  although visually the ellipses may be separated by a particular angle, their vector forms tells a different story. In one example, say A and B are (2, 2) and (2, -2) respectively, basically separated by a height of 4. If you plot out the vectors, they are separated by 90 degrees, so in this case, the line would rotate correctly. However, if A and B are (2, 2) and (2, 6) respectively, it looks the same as the first example, just translated up. However, the angle between these two vectors are now very different (~30 degrees).

Let me take some time and dig around to see if there is a way for you to do this type of scenario with Expressions. Stay tuned.

**Comment by mgutekunst** [comment]
Thanks for putting so much effort into this. 
* My line moves as well if i apply the expression to the Rotate of the visual but it's not connecting the ellipses. The visuals (A/B) are moved using a Vector3Animation that is applied to the Offset. Here's the code:
```csharp
var anim = compositor.CreateVector3KeyFrameAnimation();
anim.InsertKeyFrame(1f, new V(_rnd.Next(0, (int)this.ActualWidth-50), _rnd.Next(0, (int)this.ActualHeight-50), 0));
anim.Duration = TimeSpan.FromSeconds(_rnd.Next(5,10));

ElementCompositionPreview.GetElementVisual(comp).StartAnimation("Offset", anim);
```
This is repeated when the animation finished. To achieve this, i used a `compositor.CreateScopedBatch()`

* To ensure the correct length of the line I use an expression animation and apply it to the size. 
```csharp
var sizeAnim = _compositor.CreateExpressionAnimation();
sizeAnim.SetReferenceParameter("P1", visual1);
sizeAnim.SetReferenceParameter("P2", visual2);
sizeAnim.SetVector3Parameter("Size", new V((e1.Width / 2), (e1.Height / 2), 1));

sizeAnim.Expression = "Vector2(2,Distance(P1.Offset+Size,P2.Offset+Size))";
_line.StartAnimation("Size", sizeAnim);
```
Don't get irritated by the class V. I created a wrapper class because I always got the wrong Vector3 from IntelliSense. Also I hat to manually cast all double values to float. This is now wrapped inside this class.

**Comment by msftdavid** [comment]
I'm closing this thread due to inactivity. Please reopen if this is still a pressing concern or a blocking issue for your app.
