### ISSUE TITLE
Custom CompositionObject

### ISSUE THREAD

**Issue by ratishphilip** [Microsoft/WindowsUIDevLabs#102]
Though it is possible to derived from **CompositionObject**, it is not possible to instantiate such a class, because the constructor of **CompositionObject** is _not public_.

The reason I tried doing this is to animate a non-Composition object's property (which doesn't seem to be possible). So I thought to derive from CompositionObject and try animating a property (and obtain the intermediate values during animation). But I failed there too.

I have to achieve the following objective (_I have asked this before but there hasn't been any reply so far_).
**Animating a mask created using CanvasGeometry**
I have two rectangles - one inside the other. I create a mask using the area defined by the outer rectangle and excluding the inner rectangle.
Now the inner rectangle's Rotation changes at irregular intervals. I need to animate the rotation of the Inner Rectangle and calculate the new mask for each frame of the animation.

It would be great if you guys could point me in the right direction to achieve this.

**Comment by robmikh** [comment]
Hey @ratishphilip,

Currently this isn't possible with the API. You can read my response to [this issue](https://github.com/Microsoft/WindowsUIDevLabs/issues/52) to get a feel for why. Long story short, composition objects don't just live in the app's process, but they are also tracked by the kernel and in the system compositor. There's a lot of infrastructure that a custom object wouldn't be plugged into.

Your best bet currently is actually to create a swapchain as your surface (which you can do with Win2D), and draw into it. You would have to know what an animation would do (meaning you would have to know the duration and all the keyframes) and interpolate the values against the clock by yourself every vsync. You can refer to [this](https://github.com/Microsoft/Win2D/blob/master/samples/CompositionExample/SwapChainRenderer.cs) sample over in the Win2D GitHub page to see how a swapchain would work with the Composition API.

**Comment by ratishphilip** [comment]
@robmikh Thanks for the clarification.
