### ISSUE TITLE
Applying Blur to a SamplesCommon.CompositionImage creates blank blur

### ISSUE THREAD

**Issue by juanpaexpedite** [Microsoft/WindowsUIDevLabs#104]
To begin Build 14361 & 14332 SDK, added SamplesCommon as reference project.

I am trying to simply add the blur effect to a SamplesCommon.Composition Image, I understand this should be easy to apply but might I am missing something:

    <s:CompositionImage x:Name="BackgroundImage" x:FieldModifier="public" HorizontalAlignment="Stretch" VerticalAlignment="Stretch" Stretch="Uniform"
                Source="ms-appx:///Assets/Images/image.jpg" Grid.RowSpan="10" Grid.ColumnSpan="10"/>

And in the Loaded Event

     private void InitializeComposition()
        {

            //BackgroundImage is typeof SamplesCommon.CompositionImage

            var visual = BackgroundImage.SpriteVisual;
            var compositor = visual.Compositor;

            var effect = new GaussianBlurEffect()
            {
                Name = "Blur",
                BlurAmount = 10,
                BorderMode = EffectBorderMode.Hard,
                Source = new CompositionEffectSourceParameter("Backdrop")
            };

            var blurEffectFactory = compositor.CreateEffectFactory(effect, new[] { "Blur.BlurAmount"});

            var brush = blurEffectFactory.CreateBrush();

            var destinationBrush = compositor.CreateBackdropBrush();

            brush.SetSourceParameter("Backdrop", destinationBrush);

            //One Way
            //Black with Blur (App.xaml Dark)
            //var blurSprite = compositor.CreateSpriteVisual();
            //blurSprite.Size = new Vector2((float)BackgroundImage.ActualWidth, (float)BackgroundImage.ActualHeight);
            //blurSprite.Brush = brush;
            //ElementCompositionPreview.SetElementChildVisual(BackgroundImage, blurSprite);

            //Second Way
            //Black with Blur (App.xaml Dark)
            visual.Brush = brush;
            
        }

I have tried in both ways (I understand the second one should be enough) a but appears the image in Black with a blur, so the Image is lost. What I am doing so wrong?

**Comment by krenner** [comment]
@juanpaexpedite  
When using an EffectBrush with CompositionImage the EffectBrush needs to supply the "ImageSource" reference parameter for setting the Image content.  

     Example Source = new CompositionEffectSourceParameter("ImageSource"), 

//OneWay was duplicating CompositionImage functionality.  You can then create/and or update brushes as needed

     _brush = effectFactory.CreateBrush();
      BackgroundImage.Brush = _brush;

**Comment by juanpaexpedite** [comment]
I really appreciate your answer. Now it works like a charm, I have implemented in my app about 5 Composition features in several places that are getting the app really encouraging visually. Hope finish on time when the new great ReadStone update get released. 

Thank you

**Comment by krenner** [comment]
Glad to hear it! Thanks for your feedback.
