### ISSUE TITLE
No documentation about which properties are exposed by getscrollviewermanipulationpropertyset

### ISSUE THREAD

**Issue by simonferquel** [Microsoft/WindowsUIDevLabs#106]
Recently I wanted to make a sample that use Composition API to describe the scrolling "percentage" using colors and expression animation (by interpolating colors by Translation.Y/Extent.Y). But I have no way other than trial and error to find if there is an Extent.Y property on the property set returned by GetScrollViewerManipulationPropertySet... Please document it :)

**Comment by likuba** [comment]
Hey @simonferquel 

Thanks for the feedback.  We're working on improving our documentation across the API, and you're right this is definitely a place where we need to give a bit more information.  In the meantime, here is the list, which hopefully helps a bit:

- Vector3 Translation

- Vector3 Pan

- Vector3 Scale

- Vector3 CenterPoint

- Matrix4x4 Matrix 

There isn't an "Extent" property, but what you may want to try is using the size of the visual that is the root of the scrollable area--does that meet your needs?

**Comment by pgills** [comment]
Closing this issue and captured as feedback.
