### ISSUE TITLE
Pivotanimation is performed twice when clicking pivot header

### ISSUE THREAD

**Issue by AudioW** [Microsoft/WindowsUIDevLabs#108]
Hi,

From build 14361 up to the latest build, the Pivot control seems to have a bug. When I click on a pivot header, the navigation transition seems to be performed twice. 

I have attached a video demonstrating the different behavior. It looks like the content is set and the animation is run just after that moment.
[App2 17-Jun-16 13_30_47.zip](https://github.com/Microsoft/WindowsUIDevLabs/files/320346/App2.17-Jun-16.13_30_47.zip)

**Comment by pgills** [comment]
@AudioW is this animation with the standard XAML Pivot control?

**Comment by AudioW** [comment]
Hi PaulYes it is!
On Thu, Jun 23, 2016 at 6:40 PM +0200, "Paul Gildea" <notifications@github.com> wrote:



@AudioW is this animation with the standard XAML Pivot control?

**Comment by AudioW** [comment]
Fixed in 14383
