### ISSUE TITLE
Suggestion: add cornerradius to Backdrop Control

### ISSUE THREAD

**Issue by juanpaexpedite** [Microsoft/WindowsUIDevLabs#110]
As we know the Backdrop is a control that works Rectangular over its back to make the blur, I have tried creating corners (black, white) in the Noise.jpg, also using a Noise.png (transparent corners) and several other ways and I would like not to create an effect from zero. Might be is there an easy way to make it work but I have not found it.

NOTE, due to in the view I am working I have not any CompositionImage, I had to add checking the is initialized in the Backdrop.cs file:

    #if SDKVERSION_INSIDER
            if (!SurfaceLoader.IsInitialized)
            {
                SurfaceLoader.Initialize(ElementCompositionPreview.GetElementVisual(this).Compositor);
            }

            m_noiseBrush.Surface = await SurfaceLoader.LoadFromUri(new Uri("ms-appx:///Assets/Noise.jpg"));
            m_noiseBrush.Stretch = CompositionStretch.UniformToFill;
    #endif

Thank you,

**Comment by ratishphilip** [comment]
@juanpaexpedite You can use [**CompositionProToolkit**](https://github.com/ratishphilip/CompositionProToolkit#2-creating-masked-backdrop-brush-using-icompositionmask).

First you create an **ICompositionMask** with a rounded rectangle geometry and then pass this mask to the **CreateMaskedBackdropBrush** extension method of **Compositor**.

This will give you a **CompositionEffectBrush** which you can apply to your visual.

**Comment by juanpaexpedite** [comment]
Thank you really a lot, following your great example that's what I achieved:

![capture1](https://cloud.githubusercontent.com/assets/5947026/16440876/b9463722-3dbd-11e6-8572-531937a5fd26.JPG)
![capture2](https://cloud.githubusercontent.com/assets/5947026/16440875/b9384d10-3dbd-11e6-8c7b-4704c2383215.JPG)

Now it's exactly as I designed in my mind, more blur and less sharp :). I will follow the advice of just using one instance.

**Comment by ratishphilip** [comment]
Looks great! :)
