### ISSUE TITLE
Visuals appear blurred when rendered in small size

### ISSUE THREAD

**Issue by ratishphilip** [Microsoft/WindowsUIDevLabs#113]
Using **Composition**, I have created a Visual of size **(5,5)**. Using **CompositionProToolkit**, I have created a **CompositionMaskBrush** in the following way

I create a **CanvasGeometry** which contains a circle of radius **2.5f** and center at **(2.5f, 2.5f)**

Using **CompositionProToolkit**, I create an instance of **ICompositionMask** by calling the **CreateMaskAsync()** method. _Internally the **CreateMaskAsync()** method does this_

```C#
var color = Colors.White;
ICompositionMask mask = new CompositionMask(this, size, geometry, color);

// Render the mask to the surface
using (var session = CanvasComposition.CreateDrawingSession((CompositionDrawingSurface)mask.Surface))
{
    // If the geometry is not null then fill the geometry area
    // with the given color. The rest of the area on the surface will be transparent.
    if (geometry != null)
    {
        session.Clear(Colors.Transparent);
        session.FillGeometry(geometry, color);
    }
    else
    {
        // If the geometry is null, then the entire mask should be filled with
        // the given color
        session.Clear(color);
    }
}

return mask;
```

The **mask.Surface** is created in the following way
```C#
mask.Surface = _graphicsDevice.CreateDrawingSurface(surfaceSize, DirectXPixelFormat.B8G8R8A8UIntNormalized, DirectXAlphaMode.Premultiplied);
```

Now using this mask, I create a CompositionMaskBrush in the following way
```C#
var maskBrush = compositor.CreateMaskBrush();
maskBrush.Mask = compositor.CreateSurfaceBrush(mask.Surface);
maskBrush.Source = compositor.CreateColorBrush(Colors.Blue);

visual.Brush = maskBrush;
```

Now I render the same **CanvasGeometry** using **Win2d** (on a **CanvasControl**) in the following way
```C#
private void OnCanvasDraw(CanvasControl sender, CanvasDrawEventArgs args)
{
    var geometry = CanvasGeometry.CreateCircle(sender.Device, 110, 100, 2.5f);
    args.DrawingSession.FillGeometry(geometry, Colors.Blue);
}
```

When I compare the two rendered circles, I find that the one rendered by Composition appears **_more blurred_** than the one rendered by Win2d.

Here is the screenshot of my test app (magnified 400%)

![composition_win2d](https://cloud.githubusercontent.com/assets/7021835/16503621/b81c22b0-3ec8-11e6-8c6c-abb00c3fa54a.png)

Is this a bug? 
What needs to be done to make the visual rendered by Composition as sharp as (or even better than) Win2d?

**Comment by juanpaexpedite** [comment]
I have the same even if big sizes when the zero X or zero Y are not blank pixels, if you add a blank border around the circle (make 1 pixel bigger in every length its container) that glitch should not appear.

**Comment by ratishphilip** [comment]
I am currently on Build 14376, SDK 14366 and Visual Studio Update 3.

**Comment by pgills** [comment]
@ratishphilip good question. I'll give this to @sernaj to follow up with the team to see if this is expected or a platform bug. 

Thanks for all the build info and just to reiterate the potential issue is:
When you render the same content to a `CompositionDrawingSurfce` and a Win2D `CanvasControl` using Win2D you get different results?

**Comment by sernaj** [comment]
Looking into this. Going to let the Masking feature owners take a look.

**Comment by ratishphilip** [comment]
@sernaj Thank you. Hopefully a solution will be found out soon.

**Comment by sernaj** [comment]
I wanted to get back to this after talking to member of the team. The root of this are DPI policy handling. Win2D tries to compensate for this, where as we try to be agnostic to DPI policy in the API to keep performance high, i.e. we don't try and manage it.

**Comment by ratishphilip** [comment]
It would be great if an option is provided to give priority to rendering quality over performance in certain scenarios.

**Comment by msftdavid** [comment]
Closing this issue as the initial question seems to have been answered.
