### ISSUE TITLE
Are shadows only for images?

### ISSUE THREAD

**Issue by assassin316** [Microsoft/WindowsUIDevLabs#114]
I've looked at the composition samples solution, and the use of shadows applies only to a CompositionImage object. Is it possible to apply a shadow to any FrameworkElement (Grid, Border, Button, etc.) ??

**Comment by pgills** [comment]
The currently,`DropShadow`s can be applied directly to `SpriteVisuals` and not directly to `UIElements`. @krenner if I got something wrong.

However, you can use `TextBlock.GetAlphaMask()` to get a `CompositionBrush` to use as a mask for a shadow if you wanted to create a shadow from text.

Here's a simple example:
XAML:
```xml
<Grid HorizontalAlignment="Center" VerticalAlignment="Center">
    <Canvas x:Name="ShadowHost"></Canvas>
    <TextBlock x:Name="HelloText"
               Style="{ThemeResource HeaderTextBlockStyle}"
               Text="Hello Shadow"
               Foreground="Blue">
     </TextBlock>
</Grid>
```

C#:
```csharp
        private Compositor _compositor;

        public MainPage()
        {
            this.InitializeComponent();
            _compositor = ElementCompositionPreview.GetElementVisual(this).Compositor;
            Loaded += MainPage_Loaded;

        }

        private void MainPage_Loaded(object sender, RoutedEventArgs e)
        {
            DropShadow shadow = _compositor.CreateDropShadow();
            shadow.Mask = HelloText.GetAlphaMask();
            shadow.BlurRadius = 3;
            shadow.Offset = new Vector3(5, 5, 0);

            SpriteVisual visual = _compositor.CreateSpriteVisual();
            visual.Size = new Vector2((float)HelloText.ActualWidth, (float)HelloText.ActualHeight);
            visual.Shadow = shadow;

            ElementCompositionPreview.SetElementChildVisual(ShadowHost, visual);
        }
```

**Comment by assassin316** [comment]
Thanks pgills. I hope in the future this will be possible, it'll allow for greater flexibility on the UI. As of now, I had an idea but will have to cancel it since I can't apply a drop shadow. :\

**Comment by pgills** [comment]
@assassin316 We'll be definitely taking that as feedback as we evolve the API.

Do you see yourself using them more on containers or on any kind of element? For example Windows.UI.Xaml.Shapes?

**Comment by assassin316** [comment]
I see myself applying them directly to Buttons, Borders, Grids, Ellipses, etc. 

Here's an example of an image I found on the web. By using an Ellipse as the background of a button, applying a dropshadow to it can give a subtle but effective UI emphasis (look at the central blue button).

![e4c15238068759 575538415f107](https://cloud.githubusercontent.com/assets/17514380/16740824/c29b14fe-476e-11e6-8f41-ebbe85278288.png)


Another example would obviously be Google's Material Design in which they apply drop shadows to their Floating Action Buttons. Again, this would be easily achieved with a drop shadow on an Ellipse:

[https://material.google.com/components/buttons-floating-action-button.html#buttons-floating-action-button-floating-action-button](https://material.google.com/components/buttons-floating-action-button.html#buttons-floating-action-button-floating-action-button)

**Comment by JasterAtMicrosoft** [comment]
Hi @assassin316,

You can add a shadow to a Shape such as Ellipse using the Shape.GetAlphaMask() method. The usage is the same as what @pgills is doing above. Even though you are attaching the shadow to a SpriteVisual, it will appear as if the shadow is being cast by the Shape element. Here is a full code snippet that adds a shadow to a Shape:

XAML:

```xml
<Grid Width="200" Height="200">
    <Canvas x:Name="ShadowHost" />
    <Ellipse x:Name="CircleImage">
        <Ellipse.Fill>
            <ImageBrush ImageSource="Assets/Images/2.jpg" Stretch="UniformToFill" />
        </Ellipse.Fill>
    </Ellipse>
</Grid>
```

C#:

```csharp
public MainPage()
{
    InitializeComponent();
    CreateDropShadow(ShadowHost, CircleImage);
}

private void CreateDropShadow(UIElement shadowHost, Shape shadowTarget)
{
    Visual hostVisual = ElementCompositionPreview.GetElementVisual(shadowHost);
    Compositor compositor = hostVisual.Compositor;

    // Create a drop shadow
    DropShadow dropShadow = compositor.CreateDropShadow();
    dropShadow.Color = Color.FromArgb(255, 75, 75, 80);
    dropShadow.BlurRadius = 15.0f;
    dropShadow.Offset = new Vector3(2.5f, 2.5f, 0.0f);
    // Associate the shape of the shadow with the shape of the target element
    dropShadow.Mask = shadowTarget.GetAlphaMask();

    // Create a Visual to hold the shadow
    SpriteVisual shadowVisual = compositor.CreateSpriteVisual();
    shadowVisual.Shadow = dropShadow;

    // Add the shadow as a child of the host in the visual tree
    ElementCompositionPreview.SetElementChildVisual(shadowHost, shadowVisual);

    // Make sure size of shadow host and shadow visual always stay in sync
    ExpressionAnimation bindSizeAnimation = compositor.CreateExpressionAnimation("hostVisual.Size");
    bindSizeAnimation.SetReferenceParameter("hostVisual", hostVisual);

    shadowVisual.StartAnimation("Size", bindSizeAnimation);
}
```

**Comment by assassin316** [comment]
Hi Jaster, thank you for your response.

Am I required to have to use an ImageBrush to achieve that? The ideal scenario would be to simply use a regular Fill on the Ellipse avoiding images altogether.

**Comment by JasterAtMicrosoft** [comment]
Nope, the use of ImageBrush is just for an example! This will work no matter what the content of your Ellipse is.

**Comment by assassin316** [comment]
Oh that's great! That would work, I'll try it as soon as I can.

Thanks Jasper!!   :)

**Comment by assassin316** [comment]
I'll keep investigating my code, but it doesn't seem to work. I'll report back once I figure out why  :)

**Comment by assassin316** [comment]
Fixed!  I had an opacity set on my Ellipse, which caused the Canvas to be very faint. I also had to set a size on the Canvas. Now it's working fine!  Thanks!!  :)

**Comment by sohchatt** [comment]
Sorry for missing this question; you should check out the CompositionShadow Control in SamplesCommon: it allows you cast a shadow on any FrameworkElement in XAML. Here's a code snippet from the ShadowInterop sample in SampleGallery:

```
               <common:CompositionShadow OffsetX="10" OffsetY="15" Margin="20">
                    <Polygon Points="50,0 0,50 50,50" Stroke="Red" StrokeThickness="2" Fill="Blue"/>
                </common:CompositionShadow>
```

We demonstrated the usage of this control to apply shadows to your XAML without explicitly having to drop to Windows.UI.Composition in our last LiveQ&A session! The properties on the CompositionShadow control mirror those on the DropShadow object itself, so hopefully this makes the process of adding a DropShadow to your app a lot easier without compromising on any functionality!

**Comment by enghch** [comment]
Sorry for joining a closed issue. Anyone know if this could be used on a Canvas? I've got dozens if not hundreds of little shapes in a Canvas and I'd like to apply a dropshadow to all of them collectively. It looks like Canvas doesn't have a GetAlphaMask() method.
