### ISSUE TITLE
Clipping not applied fine for a TextBlock

### ISSUE THREAD

**Issue by juanpaexpedite** [Microsoft/WindowsUIDevLabs#115]
I am making a rating control and this time I would like to make just using composition, but when I began the Clip property is not working like the XAML RectangleGeometry Clipping:

The control I made is the Rating in the following project:
https://github.com/juanpaexpedite/MasterDetailsComposition/tree/master/AnimatedControls

I have tried several combinations, might be is the font used?

Build 14379 and 14332 SDK (I think there is nothing new about Composition in the new one SDK so that's why I have not installed it yet)

**Comment by pgills** [comment]
@juanpaexpedite I don't believe there should be anything new across those SDKs as you indicated.

Could you possibly post a screen shot of the issue you might be seeing with setting the `InsetClip`?

[InsetClip](https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.composition.insetclip.aspx) is a little bit different than XAML Rectangle Geometry clips. For `InsetClips` you specify the value you'd like to "extend inward" from either the left, top, bottom, or right side of the `Visual` it's applied to.

So you'll want to calculate the distance from the `InsetClip.RightInset` to "extend inward" from the right side of the Visual.

Most likely you are calculating some new length based on the rating value. So you'll want to take the do something like:

Pseudo code:
```
var originalLength = myVisual.Size.Y;
var newLength = 100f; // some length that's calculated based off of the rating value that's was set
var clipLength = originalLength - newLength;

var myInsetClip = compositor.CreateInsetClip();
myInsetClip.RightInset = clipLength;

myVisual.Clip = myInsetClip;
```
Hopefully that helps.

@sernaj for any more clip insights.

**Comment by juanpaexpedite** [comment]
Yes it is working, thank you for the clarification
