### ISSUE TITLE
Do we ask questions here or on StackOverflow?

### ISSUE THREAD

**Issue by assassin316** [Microsoft/WindowsUIDevLabs#116]
I've noticed lately that questions go unanswered for many days at a time, is it because there is an alternative place to ask questions??

**Comment by ratishphilip** [comment]
@assassin316 I think the WindowsUI team is busy with the Anniversary Release.

**Comment by pgills** [comment]
Sorry for the slow the responses as you've indicated we've been focused on polishing up for the Anniversary Release and personally I've recently come back from paternity leave.

Continue to keep asking questions here and keep them coming. We really appreciate the feedback.

Now that I'm back in full capacity I'll run through the issues list and we'll be up and running.

Thanks for understanding!
