### ISSUE TITLE
Animating a visual during Measure and Arrange Layout phases

### ISSUE THREAD

**Issue by ratishphilip** [Microsoft/WindowsUIDevLabs#120]
@pgills @JasterAtMicrosoft 
I am currently on **Build 14388**, **SDK 14388** and **Visual Studio 2015 update 3**.

I am creating a custom control deriving from **Panel**. In the **Measure** phase of layout, I am adding a new visual to the custom control and setting its offset to an initial location. I am also setting the **ImplicitAnimations** property of the visual to contain a Vector3KeyFrameAnimation to animate its change in offset.
Now in the **Arrange** phase of the layout, I am setting the visual's offset to a new location.

I add this custom control to the MainPage.xaml and when I run the application it just shows the visual in the new location directly. 
**What I want to achieve is that when the custom control loads up, the visual should animate its movement from the initial location to the new location.**

Here is the code

```C#
public class MyPanel : Panel
{
    Compositor _compositor;
    SpriteVisual _visual;
    private Vector3KeyFrameAnimation _offsetAnimation;
    private ImplicitAnimationCollection _implicitAnimationCollection;

    public MyPanel()
    {
    }

    protected override Size MeasureOverride(Size availableSize)
    {
        if (_compositor == null)
        {
            _compositor = ElementCompositionPreview.GetElementVisual(this).Compositor;
            _visual = _compositor.CreateSpriteVisual();
            _visual.Size = new Vector2(200, 200);
            _visual.Offset = new Vector3(-200, -200, 0);
            _visual.Brush = _compositor.CreateColorBrush(Colors.Red);

            _offsetAnimation = _compositor.CreateVector3KeyFrameAnimation();
            _offsetAnimation.Target = "Offset";
            _offsetAnimation.InsertExpressionKeyFrame(1f, "this.FinalValue");
            _offsetAnimation.Duration = TimeSpan.FromMilliseconds(500);

            _implicitAnimationCollection = _compositor.CreateImplicitAnimationCollection();
            _implicitAnimationCollection["Offset"] = _offsetAnimation;

            _visual.ImplicitAnimations = _implicitAnimationCollection;

            ElementCompositionPreview.SetElementChildVisual(this, _visual);
        }

        return _visual.Size.ToSize();
    }

    protected override Size ArrangeOverride(Size finalSize)
    {
        _visual.Offset = new Vector3(300, 300, 0);

        return base.ArrangeOverride(finalSize);
    }
}
```

It would be great if you could give me some pointers on how to achieve the desired effect.

**Comment by pgills** [comment]
@ratishphilip Super interesting scenario for a custom layout `Panel` with built-in `ImplicitAnimations`. I've included @shandilvarun for implicit and you've added @JasterAtMicrosoft who has been working on them as well.

I haven't though specifically through this scenario in detail yet (how implicit animation interact with the Measure/Arrange passes), but one question: Do you want to apply the implicit animations on the hand-off Visuals of the Children UIElements of the Panel or are you creating your own Visuals to be implicitly animated in response to layout changes?

**Comment by ratishphilip** [comment]
@pgills @shandilvarun @JasterAtMicrosoft 
Actually, I **do** want to apply the implicit animations to the hand-off visuals of the Children UIElements of the Panel. 
Since that was not working either, I tried out a sample project where I created and added a visual to the Panel to see if `ImplicitAnimations` work in that scenario.

**Comment by ratishphilip** [comment]
In the Measure pass of the custom panel, I am getting the visuals of the Children UIElements added to the panel and I am setting their initial `Offset` as `Vector3(-child.Width, -child.Height, 0f)` and in the Arrange pass, I am calculating the actual `Offset` values of each of the Children and setting them.
With the above process, I am aiming to show some kind of entrance transition for the children when they are added to the panel. But it is not working

**Comment by JasterAtMicrosoft** [comment]
Hi @ratishphilip,

Implicit property animations do not run the first time a Visual shows up on screen. The reason for this is otherwise it would be very easy to accidentally animate values when configuring an implicit animation on a new element. I think for this scenario it should be fine for you to use a normal "explicit" animation.

**Comment by ratishphilip** [comment]
@JasterAtMicrosoft 
"Explicit" animation indeed works!

Thanks for the tip! 👍
