### ISSUE TITLE
Problem with the GetScrollViewerManipulationPropertySet in the anniversay preview

### ISSUE THREAD

**Issue by jmvillagra** [Microsoft/WindowsUIDevLabs#122]
Hi,
Is there any known bug with the GetScrollViewerManipulationPropertySet in the anniversary preview? I´m getting a weird beahviour in a usercontrol that is working perfectly in the november update but it's giving me a hard time with the anniversary preview....

I have a huge Scrollviewer (around 10.000px width x 2.000px hight) where I'm rendering just a few items and recycling them when the view changes.

Every control I render in the scrollview has a expressionanimation based in the scroll properties and when I recycle it I reset the animation like:

_channelsVisual.StopAnimation("Offset.X");
_expression.SetScalarParameter("StartPosition", (float)newposition);  
_channelsVisual.StartAnimation("Offset.X", _expression);   

This is working fine in the stable version of windows, but with the anniversary preview (14388 both build and SDK) sometimes the ScrollManipulation.Translation.X is returning a wrong value but as soon as I move the scrollviewer (or change the view just 0.1px... ) it starts retuning the correct value again...

Any ideas? The expressionanimation is pretty simple:

"(ScrollManipulation.Translation.X > -StartPosition) ? 8 : -(ScrollManipulation.Translation.X + StartPosition - 8)"

Thank you

**Comment by pgills** [comment]
@jmvillagra Thanks for the feedback. I'll point you over to @likuba to see if she has any ideas.

You may be hitting an issue around the recent policy changes around interop properties: https://github.com/Microsoft/WindowsUIDevLabs/wiki/XAML-Composition-Property-Synchronization-Changes

**Comment by likuba** [comment]
Did the article above help address your issue?  If that is the issue you are hitting you will want to work around it by wrapping the UI element you want to animate inside a Canvas in order to avoid the conflict with XAML layout.

**Comment by robert-virkus** [comment]
The above link to https://github.com/Microsoft/WindowsUIDevLabs/wiki/XAML-Composition-Property-Synchronization-Changes leads to a non-existing page

**Comment by robmikh** [comment]
That's my bad, when I updated the article the URL got changed out from under everyone. Here it is: https://github.com/Microsoft/WindowsUIDevLabs/wiki/XAML-Composition-Interop-Behavior-Changes

**Comment by hanselo** [comment]
Closing as resolved.
