### ISSUE TITLE
Will be available more CompositionClip classes like an EllipseClip?

### ISSUE THREAD

**Issue by juanpaexpedite** [Microsoft/WindowsUIDevLabs#123]
In some places I would like to add the MapControl with an Ellipse Clipping, but at the moment there is no way to use more complex clippings than the great InsetClip.

Do we will have more options in the future? a generyClip based on a geometry might be? It will be really interesting to make transitions scaling clips and many more.

**Comment by ratishphilip** [comment]
You can use the CompositionMaskBrush to create a mask and apply it to your MapControl's visual.

**Comment by juanpaexpedite** [comment]
But I cannot set a Brush on the real Element Visual because it is a base Visual and not an SpriveVisual, and only can operate with new ones and apply with ElementCompositionPreview.SetElementChildVisual. Or is there any other way to work with the element real visual? (Hope yes)

**Comment by pgills** [comment]
@juanpaexpedite You are correct in that the current behavior on interop Visuals is that you cannot directly set a Brush property (or CompositionMaskBrush in this case) because Brush is only exposed on the type SpriteVisual and interop Visuals are currently of type Visual.

I've marked this for feedback with some of the following insights:
- Add more clip types like if applications cannot directly control the content of an element's Visual (like Ellipse)
- Allow applications to have more control over an element's Visual e.g. apps could set a CompositionMaskBrush on the content and provide their own custom mask

**Comment by juanpaexpedite** [comment]
Thank you! I have just think about the visual possibilities that more complex options in clipping and there are a lot of visually enhancers. And if it's added more control about the element visual in theory this allows to make plenty of visual operations with the XAML elements that it's a really great step forward.

**Comment by sernaj** [comment]
This is great feedback. There are two ways we are looking at this in the future. First, we want to continue with improved XAML interop in future releases. In short look at what it would take to more tightly integrate SpriteVisual usage by the framework which would make masking a viable option in more scenarios. Clip geometry is something we've discussed, but there are performance implications, and keeping the API highly performant is a prime directive for us.

**Comment by juanpaexpedite** [comment]
Interesting, I understand every operation that requires checking pixels that are shown or doesn't take many calculations, if masking takes less cost than clipping hope we can test a preview soon :). and thank you all for how the team works so well.

**Comment by daneuber** [comment]
@juanpaexpedite We're tracking clipping as part of the general shape support under the request [here](https://developer.microsoft.com/en-us/windows/platform/features/animatedvectorgraphicssupportinthevisuallayer/?q=vector%20graphics). Closing this issue, please feel free to upvote on the public backlog.
