### ISSUE TITLE
TextBox in a ContentDialog Itemssource only displays text when focused

### ISSUE THREAD

**Issue by AudioW** [Microsoft/WindowsUIDevLabs#124]
#I have created a new Contentdialog in Visual Studio 2015 in Windows insider build 14393 using the latest SDK.

In my dialog, I have the following code:

`<ContentDialog
    x:Class="App.EditMultipleNamesDialog"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:classes ="using:App.Classes"
    xmlns:local="using:App"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d"
    Title="Edit Multiple Names"
    PrimaryButtonText="OK">
    <Grid Width="300" Height="500">
    <ListView SelectionMode="None" x:Name="namescontrol" Margin="0,20,0,0" ScrollViewer.VerticalScrollMode="Enabled"  ScrollViewer.VerticalScrollBarVisibility="Visible">
            <ListView.ItemTemplate>
                <DataTemplate x:DataType="classes:Item">
                    <StackPanel Orientation="Horizontal">
                        <TextBlock Text="{Binding Path=ChannelNumber}" Width="40" Margin="0,0,20,5" VerticalAlignment="Center"/>
                        <TextBox MinHeight="30" TextAlignment="Center" MinWidth="160" HorizontalAlignment="Stretch" Margin="0,5,0,5" Text="{x:Bind Path=ItemName, Mode=TwoWay}" />
                    </StackPanel>
                </DataTemplate>
            </ListView.ItemTemplate>
            <ListView.ItemContainerStyle>
                <Style TargetType="ListViewItem">
                    <Setter Property="HorizontalAlignment" Value="Stretch" />
                    <Setter Property="HorizontalContentAlignment" Value="Center" />
                </Style>
            </ListView.ItemContainerStyle>
        </ListView>
    </Grid>
</ContentDialog>`

I create the dialog by using this code:
`                EditMultipleNamesDialog dialog = new EditMultipleNamesDialog();

                dialog.DataContext = VM;

                await dialog.ShowAsync();`

The result is a window that looks like this:

![capture 2](https://cloud.githubusercontent.com/assets/10196339/16946993/adb0c14e-4dac-11e6-88de-389ec7042c16.PNG)
![names1](https://cloud.githubusercontent.com/assets/10196339/16946992/adafabec-4dac-11e6-82d6-e2b0c3ba4d4e.PNG)

Only when I click a textbox, the binded text appears in the box....

Any ideas?

**Comment by JohnnyWestlake** [comment]
I'm potentially being daft, but have you tried setting the Foreground colour on the TextBox to white to see if it's the default foreground colour causing the issue?

**Comment by AudioW** [comment]
It would have been nice if you were right :-) , but I checked and it doesn't fix it....

**Comment by ratishphilip** [comment]
I think it has to do with the default template of the TextBox which I believe is not suited for dark backgrounds.
Edit a copy of the default template of the TextBox and check (and adjust) the Foreground and Background colors set during the various Visual states of the TextBox.

**Comment by pgills** [comment]
@AudioW I'll try to forward this to the controls side to see if there is any known issues with the combination of:
- ContentDialog
- ListView
 - ItemTemplate
 - TextBox - editable

**Comment by AudioW** [comment]
Got it, it looks like the default template has to be adjusted from the original quite precisely. Thanks for the heads up
