### ISSUE TITLE
Is it possible to disable 'elastic band' scroll of a gridview?

### ISSUE THREAD

**Issue by AudioW** [Microsoft/WindowsUIDevLabs#125]
When I hold and drag in a gridview that does not have any scrollbars visible, there is still a sort of elastic drag going on when I move the scrollviewer with my finger. Is it possible to turn this off? It makes clicking items in the viewer less accurate in my situation.

**Comment by JasterAtMicrosoft** [comment]
Hi @AudioW, you should be able to prevent this by setting `ScrollViewer.VerticalScrollbarVisibility="Disabled"` and `ScrollViewer.VerticalScrollMode="Disabled"` on the GridView. This will prevent any scrolling.

**Comment by AudioW** [comment]
Hi @JasterAtMicrosoft , that does indeed solve the elastic band effect, but then of course it also disables the vertical scrolling...:-)

Is it possible to just remove the elastic band effect if the scrollviewer is in a state where there is nothing to scroll?

**Comment by JasterAtMicrosoft** [comment]
My bad, yes setting both properties to `Auto` should give you that behavior.

**Comment by AudioW** [comment]
Ah that's great! Thanks a lot.
