### ISSUE TITLE
undebuggable bug in windows.ui.xaml when using cas

### ISSUE THREAD

**Issue by AudioW** [Microsoft/WindowsUIDevLabs#126]
Hi

I am using the connectedanimationservice to animate an ellipse from one page to the other. This works fine 9/10 times but sometimes I get a crash to which the debugger can’t seem to attach.

I am on build 14393 with the latest sdk. Here is the error event info:

Faulting application name: myappp.exe, version: 1.0.0.0, time stamp: 0x56c69c5d
Faulting module name: Windows.UI.Xaml.dll, version: 10.0.14393.0, time stamp: 0x57899a84
Exception code: 0xc000027b
Fault offset: 0x00000000004d04ff
Faulting process id: 0x1aec
Faulting application start time: 0x01d1e2ef0aa8bdd8
Faulting application path: C:\Users\dev\Desktop\myyapp\bin\x64\Debug\AppX\myapp.exe
Faulting module path: C:\Windows\System32\Windows.UI.Xaml.dll
Report Id: 7af3379c-5d91-4740-bc76-21b3f40b2083
Faulting package full name: myapp.myapp_1.1.6.0_x64__4zg0btev1pvta
Faulting package-relative application ID: App

This is probably not a lot to go on. Here is the code I use:

```
            try
            {
                ConnectedAnimationService cas = ConnectedAnimationService.GetForCurrentView();

                cas.PrepareToAnimate("item", imageellipse);
            }
            catch { }

            ((Frame)ParentPage.Parent).Navigate(typeof(Detail), item);
```

And on  the receiving page:
        protected override async void OnNavigatedTo(NavigationEventArgs e)
        {

```
        try
        {
            ConnectedAnimationService cas = ConnectedAnimationService.GetForCurrentView();

        cas.DefaultDuration = TimeSpan.FromSeconds(1);


            cas.GetAnimation("item").TryStart(detailellipse);
        }
        catch { }


    }
```

**Comment by JasterAtMicrosoft** [comment]
Could you attach a project that demonstrates the issue?

Also, is the crash in PrepareToAnimate or GetAnimation?

**Comment by AudioW** [comment]
Hi Jaster,

here is some info from hockeyapp:

Date/Time:       2016-07-21T03:43:22.963Z
OS Version:      Windows 10.0.14393.0
Report Version:  104

Exception Type:  System.Runtime.InteropServices.COMException
Crashed Thread:  3

Application Specific Information:
An outgoing call cannot be made since the application is dispatching an input-synchronous call.

An outgoing call cannot be made since the application is dispatching an input-synchronous call.

Exception Stack:
Windows.ApplicationModel.Core.UnhandledError.Propagate()

I currently unfortunately don't have time to create a project that I can post up. I hope this info helps.

**Comment by JasterAtMicrosoft** [comment]
I'm not able to repro this without more information, sorry. 😞
Closing this issue.
