### ISSUE TITLE
DropShadows + System Chrome + Phone graphics driver problems

### ISSUE THREAD

**Issue by JohnnyWestlake** [Microsoft/WindowsUIDevLabs#127]
For starters, here's a video demonstrating the problem:
https://1drv.ms/v/s!Am6tzicbkkfemfEskMdOLHBZ_Ljfhw

Background: I have multiple text elements on the screen. These text elements have brushes with DropShadows added to them. On mouse over, I animate the shadows to become visible.

Problem: On the phone, having these shadow visuals seems to make the phone's display driver go nuts - when system chrome is overlaying a shadowed element! See video - all system chrome (navigation bar at the bottom, banner notifications, notification center etc.) flicker when overlayed on top of the app. For these demo purposes, I'm using a Lumia 950XL. 

Super annoying! It's worth noting that when system chrome _isn't_ overlaying a shadow, it's fine.

(Having seen quite a few similar issues over time using DirectX & Win2D on the phone and it's always been related to layers, so I'm guessing it's a driver / DX issue)

Here's a sample app that uses the same button code I'm using an exhibits the same problem. It's worth noting that the constant flickering only occurs when the progress bar updates. Take out code to do that, and flickering only happens at the start of the animation.

To repro: run on a phone, click all the text items a few times so you've seen the shadows on them, and then pull and hold down the notification tray and notice madness.

[ShadowTest.zip](https://github.com/Microsoft/WindowsUIDevLabs/files/378042/ShadowTest.zip)

Additional Problem: In the same app on PC, try moving your mouse really quickly between the two buttons constantly. You'll crash your display driver. On the PC, this is annoying, but not usually terrible (though occasionally it could take your whole system down). On the phone however, it restarts the entire device when the display driver crashes, which is less livable!

(Part of this is down I think to the StopAnimation call in the code, but being able to crash the entire phone's display driver and causing it to restart is a bit of an issue the platform should be preventing us from doing and handling a bit more gracefully!). 

To repro on the phone, just tap between the two buttons really quickly, and then watch as your device dies and restarts!

**Comment by JohnnyWestlake** [comment]
For ref, Lumia 950XL is running: OS 10.0.14393.0, Firmware 01078.00038.16025.39013

**Comment by krenner** [comment]
@JohnnyWestlake  Thank you for the detailed write up and all the information.  I wanted to let you know we are taking a look at this.  At this point we can reproduce your app flickering on device but we will need to do some debugging. "We" being the effects team here in composition - this may as you suggest be a an issue that is independent of shadows.

**Comment by rpedretti** [comment]
I also can reproduce this in my app, as shown at https://1drv.ms/v/s!Arstk3P49tmim9Qdp9vta1b5yC4u3w
What I do is only cast a dropshadow on rectangles and it works just fine on my desktop.

Runnign on Lumia 640, SO 10.0.14393.67, Firmware 02117.00000.15184.36001

**Comment by naeubanks** [comment]
Thanks for the repro app @JohnnyWestlake! I've tracked down the issue and have a fix that resolves both the issue you're seeing in the ShadowTest app and the flickering that @rpedretti is reporting. We'll get back to you soon as to when you can expect the fix to be available.

**Comment by msftdavid** [comment]
This fix should be available in the latest insider build. Closing the issue.
