### ISSUE TITLE
ImplicitAnimations for InsetClip

### ISSUE THREAD

**Issue by ratishphilip** [Microsoft/WindowsUIDevLabs#131]
Since it derives from **CompositionObject**, **InsetClip** class does have a **ImplicitAnimations** property, but it seems that it does not allow implicit animations.

I tried the following code

```C#
_visual = _compositor.CreateSpriteVisual();
_visual.Size = new Vector2(600, 400);
_visual.Offset = new Vector3(200, 200, 0);
_visual.Brush = _compositor.CreateColorBrush(Colors.Red);

var insetAnimation = _compositor.CreateScalarKeyFrameAnimation();
insetAnimation.Target = "RightInset";
insetAnimation.Duration = TimeSpan.FromSeconds(1);
insetAnimation.InsertExpressionKeyFrame(1f, "this.FinalValue");
var implicitAnimationCollection = _compositor.CreateImplicitAnimationCollection();
implicitAnimationCollection["RightInset"] = insetAnimation;
var insetClip = _compositor.CreateInsetClip(0, 0, 0, 0);

insetClip.ImplicitAnimations = implicitAnimationCollection;

_visual.Clip = insetClip;
ElementCompositionPreview.SetElementChildVisual(this, _visual);
```

Now when I change the value of the **RightInset** property of the **InsetClip**, it does not animate

```C#
((InsetClip)_visual.Clip).RightInset = 200;
```

Is there a better approach to solving this issue?

I am on **build 14393.5** and **SDK 14388**. I am using **VisualStudio 2015 Update 3**.

**Comment by shandilvarun** [comment]
Hi @ratishphilip 
Thanks for pointing this out. You are correct that ImplicitAnimation is available on CompositionObject and hence any object that is derived from it will have this property. For the Anniversary Release ImplicitAnimation will only work for Visual and specifically animatable properties of Visual. We are looking to expand the ImplicitAniamation support in the future.

**Comment by ratishphilip** [comment]
@shandilvarun 
Thanks for the reply.
Hoping that, by the Redstone 2 release, Windows Composition will have more awesome features.
