### ISSUE TITLE
[SDK 14393 - Repro] Setting a UIElement's Visual.Offset in a Grid causes that element to lose its position

### ISSUE THREAD

**Issue by crb9826** [Microsoft/WindowsUIDevLabs#132]
In the 14393 RTM SDK, animating or setting the Visual.Offset of a UIElement that is in a child of a Grid will cause it to lose it's layout position. Essentially, the Grid.Row, Grid.Column, and Margin of that element will be ignored, and it will be moved to the top left (0, 0) position of the Grid.

If you set the Offset property of the element's Visual, it will move to the top-left of the Grid. However, if you only animate Offset.Y, the element will move to the top of the grid but maintain its correct X-position. If you only animate Offset.X, the element will move to the left of the Grid but maintain it's correct Y-position. The incorrect position persists after the animation is over.

This does not occur in apps targeting 10586 when running on any device. It also does not occur in apps targeting 14393 when running on a 10586 device.

I've attached a repro. [CompositionBugRepro.zip](https://github.com/Microsoft/WindowsUIDevLabs/files/398349/CompositionBugRepro.zip)

In the repro, there are four TextBlocks, each in a different row of a grid. When you click on a TextBlock, its Visual's Offset is set to { 0, 0, 0 }, which will cause it to move to the top-left of the Grid. If you change the target version of the repro to 10586, or deploy to a device running 10586, this bug won't occur.

By the way, thanks for your work so far! The new Composition APIs are pretty amazing over all.

**Comment by JasterAtMicrosoft** [comment]
Hi @crb9826,

Thanks for getting in touch! The issue you are seeing is the result of a behavior change we made in the Anniversary Update property where the XAML framework uses the Offset property of the handout Visual to represent layout. The details are captured [here](https://github.com/Microsoft/WindowsUIDevLabs/wiki/XAML-Composition-Interop-Behavior-Changes), but the upshot is that if you are animating or modifying the Offset of a handout visual, you should wrap its element in a Canvas to make sure the framework is not running layout on the element.

For example:

```xml
<Canvas>
    <Border x:Name="ElementToAnimate" ... />
</Canvas>
```

**Comment by crb9826** [comment]
Ah gotcha, thanks for letting me know. This explains why some expression animations don't work either, since XAML sets the property on the Visual which cancels the animation. This makes things a bit harder, but I can work around it :)
