### ISSUE TITLE
Creating a Reflection effect for CompositionImage (or any Visual)

### ISSUE THREAD

**Issue by ratishphilip** [Microsoft/WindowsUIDevLabs#133]
Hi,
Is it possible to create a reflection effect for CompositionImage (or any other Visual) like this using Composition APIs?

![reflection](https://cloud.githubusercontent.com/assets/7021835/17353582/db84cc74-58f5-11e6-958a-1a711ea7852a.PNG)

**Comment by robmikh** [comment]
Yes there is! If you need a solution that can work for any arbitrary visual (NOT subtrees), then you can create a new `SpriteVisual` with the same properties as the target visual, and give it the same brush. Then crate a `LayerVisual` and use a `CompositeEffect` with a linear gradient as a mask. Next you'll want to flip the reflection visual 180 degrees on the X-axis. Finally, attach the `LayerVisual` as a child of the target visual, and the `SpriteVisual` as a child of the `LayerVisual`. 

Here's the code I used to test this: 
**Note: This is some quick test code, so I didn't cache anything. Don't forget to cache everything that you'd want to reuse, especially the effect factory!**
```
private void InitComposition()
{
    _compositor = ElementCompositionPreview.GetElementVisual(this).Compositor;
    _imageLoader = ImageLoaderFactory.CreateImageLoader(_compositor);

    var visual = _compositor.CreateSpriteVisual();
    visual.Offset = new Vector3(150.0f, 150.0f, 0.0f);
    visual.Size = new Vector2(150.0f, 150.0f);
    visual.Brush = _compositor.CreateSurfaceBrush(_imageLoader.LoadImageFromUri(new Uri(@"ms-appx:///Assets/Images/microsoft.png")));

    ElementCompositionPreview.SetElementChildVisual(this, visual);

    Reflect(visual);
}

private void Reflect(SpriteVisual visual)
{
    var layerVisual = _compositor.CreateLayerVisual();

    var effectDescription = new CompositeEffect
    {
        Mode = Microsoft.Graphics.Canvas.CanvasComposite.DestinationIn,
        Sources =
        {
            new CompositionEffectSourceParameter("source"),
            new CompositionEffectSourceParameter("mask")
        }
    };

    var effectFactory = _compositor.CreateEffectFactory(effectDescription);
    var effectBrush = effectFactory.CreateBrush();

    effectBrush.SetSourceParameter("mask", CreateGradientBrush(visual.Size));

    layerVisual.Effect = effectBrush;
    layerVisual.Offset = new Vector3(0, visual.Size.Y + 7.0f, 0);
    layerVisual.Size = visual.Size;
    layerVisual.Opacity = 0.5f;

    var reflectionVisual = _compositor.CreateSpriteVisual();
    reflectionVisual.Size = visual.Size;
    reflectionVisual.Brush = visual.Brush;
    reflectionVisual.CenterPoint = new Vector3(visual.Size / 2.0f, 0);
    reflectionVisual.RotationAngleInDegrees = 180;
    reflectionVisual.RotationAxis = new Vector3(1, 0, 0);

    visual.Children.InsertAtTop(layerVisual);
    layerVisual.Children.InsertAtTop(reflectionVisual);
}

private CompositionSurfaceBrush CreateGradientBrush(Vector2 size)
{
    var gradientSurface = _imageLoader.CreateSurface(size.ToSize());
    _imageLoader.DrawIntoSurface(gradientSurface, (surface, device) =>
    {
        var canvasDevice = CanvasComposition.GetCanvasDevice(device);

        using (var session = CanvasComposition.CreateDrawingSession(surface))
        {
            session.Clear(Colors.Transparent);
            var brush = new CanvasLinearGradientBrush(canvasDevice, Colors.White, Colors.Transparent);
            brush.StartPoint = new Vector2((float)surface.Size.Width / 2.0f, 0);
            brush.EndPoint = new Vector2((float)surface.Size.Width / 2.0f, (float)surface.Size.Height * 0.6f);
            session.FillRectangle(new Rect(0, 0, surface.Size.Width, surface.Size.Height), brush);
        }
    });

    return _compositor.CreateSurfaceBrush(gradientSurface);
}
```

That gave me this result:
![reflection](https://cloud.githubusercontent.com/assets/7089228/17395407/17283106-59e3-11e6-8e6a-33e0f3f0e5b4.png)

You'll want to tweak the numbers to make it work the way you want (or preferably as properties in some helper class or control). Specifically you'll want to fiddle with the offset of the reflection and the start and end points of the gradient.

**Comment by robmikh** [comment]
I'd like to add that if you can get away with doing this without the `LayerVisual` (say that you know the target visual has a `CompositionSurfaceBrush` and not a `CompositionEffectBrush`), then you definitely should. The `LayerVisual` was used in the above solution so that this would work in all cases. For instance, when the target visual has an effect brush:

![effectreflection](https://cloud.githubusercontent.com/assets/7089228/17395743/d3640628-59e4-11e6-8b1b-9c5863abb4db.png)

Additionally, you could modify the above solution to walk the subtree of the target visual, and reconstruct an identical subtree to be the reflection. This would also require the use of a `LayerVisual`.

**Comment by ratishphilip** [comment]
@robmikh 
Thanks a lot. Now I have more clarity on how to use a `CompositeEffect`.
Just had one more question related to this
Is there any performance difference when I use `LayerVisual` instead of `SpriteVisual` when I know that  targetVisual has a `CompositionSurfaceBrush` and not a `CompositionEffectBrush`?

**Comment by ratishphilip** [comment]
@robmikh 
Based on this, I have incorporated the API to create a reflection for Visual (_and its subtree_) in [**CompositionProToolkit** project](https://wpfspark.wordpress.com/2016/08/08/compositionprotoolkit-v0-4-released/).
