### ISSUE TITLE
Dealing with mouse (pointer) input in Curtain example

### ISSUE THREAD

**Issue by GeertvanHorrik** [Microsoft/WindowsUIDevLabs#135]
Checking out the Curtain example in the composition demo. Looks good, but it doesn't support mouse. When trying to disable the check for touch, I get an access exception.

Unfortunately I cannot change the `VisualInteractionSource.ManipulationRedirectionMode` because it can only redirect touch stuff.

Why is this and how can we support both mouse and touch for this effect?

**Comment by likuba** [comment]
@GeertvanHorrik for now, touch and precision touchpads are the only input modalities that are auto supported, but there are options for how to get the mouse behavior you want as well.  Are you looking for a click to sort of push the curtain up, or for a click & drag experience to pull the curtain up?

**Comment by GeertvanHorrik** [comment]
Thanks for your response @likuba.

I am looking to recreate exactly what Groove does (in narrow mode). So when you click, it shows a "gravity-like" curtain. Then the user can slowly move the curtain up and the view behind it will show up.

Basically the touch and mouse behave exactly the same, which is what users would expect.

**Comment by likuba** [comment]
Gotcha--as I mentioned unfortunately for this release we only have touch and precision touchpad supported automatically.  That being said, there are a few options to help get mouse input to drive InteractionTracker as well.

If you want mouse click & drag to act like a touch drag, the best option is probably to populate a propertyset with the mouse data, and use that on mouse down to animate the InteractionTracker position with [InteractionTracker.TryUpdatePositionWithAnimation](https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.composition.interactions.interactiontracker.tryupdatepositionwithanimation.aspx).

The other option I was mentioning was something like a "click to dismiss" similar to the Windows lockscreen mouse behavior.  If you want to do something like that, you would want to use [InteractionTracker.TryUpdatePositionWithAdditionalVelocity](https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.composition.interactions.interactiontracker.tryupdatepositionwithadditionalvelocity.aspx), where you can use a velocity that causes dismissal.  

Those are your best bets for now--hopefully one of them can help you get the UX you are looking for.

**Comment by likuba** [comment]
Closing for now, but please let us know if there is anything more you need help with to achieve your scenario.
