### ISSUE TITLE
Animate CompositionImage SurfaceBrush

### ISSUE THREAD

**Issue by LostLogic** [Microsoft/WindowsUIDevLabs#136]
Hi!
I have a CompositionImage of 120x120, which is loaded with an image source of 240x120.
I want to animate the image by setting the offset from 0,0 to 1,0. (Which I figure, should be correct) How can I do this?

This is what I've got so far, but it's not playing well.

```
            image.Source = ImageUri;
            image.Stretch = Stretch.UniformToFill;
            image.SurfaceBrush.AnchorPoint = new Vector2(0.5f,0.5f);

            image.SurfaceBrush.Offset = new Vector2(0.0f,0.0f);

            var surfaceAnimation = _compositor.CreateVector2KeyFrameAnimation();
            surfaceAnimation.InsertKeyFrame(0f, new Vector2(0.0f,0.0f));
            surfaceAnimation.InsertKeyFrame(1f, new Vector2(1.0f, 0.0f));
            surfaceAnimation.Duration = TimeSpan.FromSeconds(3);
            surfaceAnimation.IterationBehavior = AnimationIterationBehavior.Forever;

            image.SurfaceBrush.StartAnimation("planetRotation", surfaceAnimation); // This fails
```

**Comment by JohnnyWestlake** [comment]
You've set your target property as "planetRotation". If that a thing, or did you want   `image.SurfaceBrush.StartAnimation(nameof(image.SurfaceBrush.Offset), surfaceAnimation); ` ?

**Comment by LostLogic** [comment]
Thanks Johnny! That was the hint I needed!

Final code:```

// Update the image URI
            image.Source = AvatarUri;
            image.Stretch = Stretch.UniformToFill;
            image.SurfaceBrush.CenterPoint = new Vector2(0.5f,0.5f);

            var linear = _compositor.CreateLinearEasingFunction();
            var surfaceAnimation = _compositor.CreateVector2KeyFrameAnimation();
            surfaceAnimation.InsertKeyFrame(0f, new Vector2(-50.0f,0.5f), linear);
            surfaceAnimation.InsertKeyFrame(1f, new Vector2(50.0f, 0.5f), linear);
            surfaceAnimation.Duration = TimeSpan.FromSeconds(5);
            surfaceAnimation.IterationBehavior = AnimationIterationBehavior.Forever;

            image.SurfaceBrush.StartAnimation(nameof(image.SurfaceBrush.Offset), surfaceAnimation);
```
