### ISSUE TITLE
Application crashing when animation used in gridview and reordering

### ISSUE THREAD

**Issue by moc426** [Microsoft/WindowsUIDevLabs#14]
Hi

I am having trouble with a basic animation to elements on a usercontrol. Here is my animation code:

                visual = ElementCompositionPreview.GetElementVisual(gImage);
                Compositor compositor = visual.Compositor;

                var animation = compositor.CreateVector3KeyFrameAnimation();

                animation.InsertKeyFrame(0f, new Vector3(0f, 0f, 0f));
                animation.InsertKeyFrame(0.50f, new Vector3(0, -50f, 0f));
                animation.InsertKeyFrame(1f, new Vector3(0, 0f, 0f));

                animation.Duration = TimeSpan.FromSeconds(6);
                animation.IterationBehavior = AnimationIterationBehavior.Forever;

                visual.StartAnimation("Offset", animation);

So it grabs the image element "gimage" and moves it up and down. This works fine.

Now what I have is an ObservableCollection of this usercontrol in a gridview. This gridview is set to allow reordering of items. I can reorder an item on the same row it is on, but once I move it to another row in the grid, the application crashes with "An unhandled win32 exception occurred in appname.exe [7996]". If I disable the animations, this error does not occur and I can reorder all items on my gridview.

I would appreciate any feedback on this, I can't seem to work around it.

Thanks!

**Comment by shandilvarun** [comment]
Hi, Thanks for bringing this up. We will look into the scenario and get back.

**Comment by pgills** [comment]
@shandilvarun Any updates on this issue?

@moc426 Are you still running into this issue? If so, what BUILD number are you using?

**Comment by moc426** [comment]
@pgills Yes the issue still exists, I am using build 10586.

I enabled native debugging and this is the message I get

0xC000027B was unhandled
Message: Unhandled exception at 0x0431A41E (Windows.UI.Xaml.dll) in app_name.exe: 0xC000027B: An application-internal exception has occurred (parameters: 0x0E7568E0, 0x00000001).

It is not able to load, combase.pdb not loaded

10.0.14267.1000(rs1_release.160213-2013)
C:\Windows\SysWOW64\combase.dll

**Comment by pgills** [comment]
@moc426 I'll poke @shandilvarun to see if there has been any progress.

**Comment by shandilvarun** [comment]
Hi @moc426  do you mind attaching a small app that repros this issue? if not then can you provide some more insights on how are you re-ordering and set of operations.

**Comment by moc426** [comment]
@shandilvarun 

Sure attached is quick sample app I put together that reproduces the issue. You can run the application. Dragging the items on the same row works fine, once you drag to a different row, it will crash.

Thanks

[testcomposition.zip](https://github.com/Microsoft/composition/files/147590/testcomposition.zip)

**Comment by shandilvarun** [comment]
@moc426 we have identified this as a bug and will update you once we have a fix in place. For now to workaround this issue is to use transitions (ReorderThemeTransition or ContentThemeTransition). Thanks for finding one for us.

**Comment by pgills** [comment]
Closing. If there are any issues with the workaround, please reactivate.
