### ISSUE TITLE
Exception while using ScopedBatch

### ISSUE THREAD

**Issue by ratishphilip** [Microsoft/WindowsUIDevLabs#141]
I am on **build 14901** and **SDK 14393**, **Visual Studio 2015 Update 3**.

In order to simplify the use of **ScopedBatch**, I have created the following extension method

```C#
public static class TestCompositorExtensions
{
    public static void CreateScopedBatch(this Compositor compositor, 
        CompositionBatchTypes batchType, 
        Action action, 
        Action postAction = null)
    {
        if (action == null)
            throw 
              new ArgumentException("Cannot create a scoped batch on an action with null value!", 
              nameof(action));

        // Create ScopedBatch
        var batch = compositor.CreateScopedBatch(batchType);

        // Is there any action to be executed when the batch completes?
        if (postAction != null)
        {
            //// Handler for the Completed Event
            TypedEventHandler<object, CompositionBatchCompletedEventArgs> handler = null;
            handler = (s, ea) =>
            {
                // Unsubscribe the handler from the Completed Event
                batch.Completed -= handler;
                // Invoke the post action
                postAction();
            };

            batch.Completed += handler;
        }

        // Invoke the action
        action();

        // End Batch
        batch.End();
    }
}
```

so that it can be used like this

```C#
compositor.CreateScopedBatch(CompositionBatchTypes.Animation,
    () => 
    {
        // Action
        visual.StartAnimation("Opacity", fadeInAnimation);
    },
    () =>
    {
        // PostAction
        visual.StartAnimation("Rotation", rotationAnimation);
    });
```

However, on using this code, I get a **System.InvalidOperationException** at this line

```C#
    batch.Completed -= handler;
```

If I comment, this line, everything works as expected. The reason I am unsubscribing from the **Completed** event is to ensure that there are no memory leaks and that the ScopedBatch is properly garbage collected. 

Am I doing something wrong here? 
Will the ScopedBatch be garbage collected properly if I do not unsubscribe to the **Completed** event?

### Here are the details of the exception raised
**System.InvalidOperationException**
**Message**:
    A method was called at an unexpected time. (Exception from HRESULT: 0x8000000E)

**StackTrace**:
```C#
    at Windows.UI.Composition.CompositionScopedBatch.remove_Completed(EventRegistrationToken token)
    at System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.NativeOrStaticEventRegistrationImpl.RemoveEventHandler[T](Action`1 removeMethod, T handler)
    at System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.RemoveEventHandler[T](Action`1 removeMethod, T handler)
    at TestCompositorExtensions.<>c__DisplayClass0_1.<CreateScopedBatchNext>b__0(Object s, CompositionBatchCompletedEventArgs ea)
```

**Comment by JohnnyWestlake** [comment]
The following small re-write does the trick. It also explicitly causes Dispose on the ScopedBatch too, which I figure probably needs to be done regardless of a postAction.

(Pretty much everything you create from the compositor has Dispose methods on them so I figure they all need to be manually disposed? Even easing functions and such. There's not much guidance on it yet)

```
public static void CreateScopedBatch(this Compositor compositor,
        CompositionBatchTypes batchType,
        Action action,
        Action postAction = null)
        {
            if (action == null)
                throw
                  new ArgumentException("Cannot create a scoped batch on an action with null value!",
                  nameof(action));

            // Create ScopedBatch
            var batch = compositor.CreateScopedBatch(batchType);
           
            //// Handler for the Completed Event
            TypedEventHandler<object, CompositionBatchCompletedEventArgs> handler = null;
            handler = (s, ea) =>
            {
                // Unsubscribe the handler from the Completed Event
                ((CompositionScopedBatch)s).Completed -= handler;

                try
                {
                    // Invoke the post action
                    postAction?.Invoke();
                }
                finally
                {
                    ((CompositionScopedBatch)s).Dispose();
                }
            };

            batch.Completed += handler;

            // Invoke the action
            action();

            // End Batch
            batch.End();
        }
```

**Comment by ratishphilip** [comment]
@JohnnyWestlake Thanks for the reply.

I am still getting the same exception where the handler is being unsubscribed. 

Another thing I would like to mention here is that I am executing the API under **Task.Run(...)** like this

```C#
Task.Run(() =>
    {
        compositor.CreateScopedBatch(CompositionBatchTypes.Animation,
            (batch) => 
            {
                // Action
                visual.StartAnimation("Opacity", fadeInAnimation);
            },
            (batch) =>
            {
                // PostAction
                visual.StartAnimation("Rotation", rotationAnimation);
        });
    });
```
Is that the cause of the exception?

**Comment by JohnnyWestlake** [comment]
I'm going to say almost certainly (in that tiny snippet there's no real advantage to using Task anyway, it's probably actually detrimental performance wise, though I realise all use cases wouldn't be that simple).

Even marshalling back to the UI thread doesn't help either, and you can't use await Task.Run inside the actions as it won't actually await (unless the signature is change to some variant of Func)

**Comment by ratishphilip** [comment]
The snippet is a part of a large code which needs to be run on a separate thread. Therefore I am running  it under Task.Run().

**Comment by ratishphilip** [comment]
Ok. Now I removed the Task.Run() and ran the code directly.

I am still getting the same exception at the handler unsubscription.

**Comment by JohnnyWestlake** [comment]
Two questions: Are you off the UI thread at the start of calling this? And does anything in your action _await_ or switch thread?  If both of those are false you shouldn't have much issue

**Comment by ratishphilip** [comment]
Yes, I am off the UI thread at the start of calling this. The method encapsulating this code is executed in  response to a System.Threading.Timer Tick.

And yes, I have a _await_ call in my method prior to using the ScopedBatch. The skeleton if the method is something like this

```C#
async Task LoadImages()
{
    ...
    ... 
   _img = await LoadFromUri(uri);
    ...
    ...

    compositor.CreateScopedBatch(CompositionBatchTypes.Animation,
        (batch) => 
        {
            // Action
            visual.StartAnimation("Opacity", fadeInAnimation);
        },
        (batch) =>
        {
            // PostAction
            visual.StartAnimation("Rotation", rotationAnimation);
    });
}
```

**Comment by JohnnyWestlake** [comment]
Basically from what I can tell, if you want to unhook, you need to start this method from the UI thread, so you may want to call _compositor.CreateScopedBatch(...)_ from a Dispatcher.

As to whether that's a bug or by design... someone more knowledgeable will have to answer :P

**Comment by ratishphilip** [comment]
I was under the impression that Composition elements were not dependant on the UI thread and rather ran in separate Composition thread. ScopedBatch also derives from CompositionObject.
So I am wondering for could be the reason _compositor.CreateScopedBatch(...)_ is dependant on a UI thread.

**Comment by ratishphilip** [comment]
Ok, wrapping the method body under _await Dispatcher.RunAsync(...)_ causes the code to execute without any exceptions.
But this does not seem the right approach to me. What if the UI thread has lots of items enqueued before this method? It would delay the execution of the method!

**Comment by ratishphilip** [comment]
@pgills @JasterAtMicrosoft @robmikh any comments on this issue?

**Comment by ratishphilip** [comment]
It seems my code was a little messed up. After refactoring it seems to work fine. Thanks.

**Comment by ratishphilip** [comment]
This issue seems to be happening again.
I am using the **`CreateScopedBatch`** code specified by @JohnnyWestlake and it id being invoked from the UI thread.
This issue is sporadic and happens mostly when called several times in rapid succession.
