### ISSUE TITLE
[Function Request] Customize minimize maximize close buttons of UWP app.

### ISSUE THREAD

**Issue by higankanshi** [Microsoft/WindowsUIDevLabs#142]
I belive it's critical to make the minimize, maximize and close buttons customizable for building a refined UI. Suppose we have an app with two modes like Zune - normal and mini. In the mini mode, the app only presents the indispensable and small elements on the window.
 For the mini mode, the three buttons in standard size are too big. And for the consistency of the UI design, sometimes it will be nice to allow the app freely styling the buttons,especially the close button. I know maybe it's not at the Microsoft's priority list, but I believe we can somehow make it available.

 For example, developers can hide those built-in buttons and draw their own ones and call "CoreWindow.Minimize()", "CoreWindow.Maximize" etc. 
Or maybe just styling them as XAML elements though for now they are not XAML frameelements. But that would be nice. We do like to build universal Windows apps. 
But for now, uwp obviously lacks some important features. Looking forward to customizable window chrome for UWP apps.

**Comment by decademoon** [comment]
I'm not sure about this. There's too much inconsistency across Windows 10 as a whole (don't even get me started on the context menus), so giving developers the ability to style the title bar buttons as they please would just make things worse.

**Comment by MaxfieldWalker** [comment]
Microsoft Sticky Notes(UWP) looks disable default minimize maximize close buttons.
Is there already any way to customize them?

![image](https://cloud.githubusercontent.com/assets/7913793/18940992/f43599cc-8647-11e6-9454-f5fdf7eee24a.png)

**Comment by robmikh** [comment]
There's currently no way to do this. I'm not sure what's going on with Sticky Notes, but it seems to be closer to a Centennial app than it is a "true" UWP.

**Comment by tomzorz** [comment]
@robmikh make uwp great ~~again~~ for the first time

**Comment by daneuber** [comment]
Thanks for the feedback. Please feel free to file a feature request in the backlog so we can get this routed to the correct team [here](https://developer.microsoft.com/en-us/windows/platform/features).
