### ISSUE TITLE
Questions regarding the behavior of CompositionMaskBrush

### ISSUE THREAD

**Issue by ratishphilip** [Microsoft/WindowsUIDevLabs#144]
I am on build **14901** and **SDK 14393**, **Visual Studio 2015 Update 3**. 

I have a couple of questions regarding the behavior of CompositionMaskBrush in certain scenarios.

### Scenario 1

I am creating a **CompositionDrawingSurface** of size **(400, 400)** and drawing a **CanvasGeometry** on it. I am then creating a **CompositionSurfaceBrush** from the surface. This surface brush is used to provide the **Mask** for the **CompositionMaskBrush**.

Now when I apply the mask brush to a visual of size **(200, 200)** I see that the canvas geometry is resized to fit the visual. 
**Is there a way to prevent the brush from resizing its surface to fit the target visual? Also it would be great if there was an option to specify the alignment (horizontal and vertical) of the unresized mask within the visual.**

![mask_issue](https://cloud.githubusercontent.com/assets/7021835/17674664/5b0996f2-62db-11e6-8904-67ce99ffb993.png)
Here is the code

```C#
private void OnLoaded(object sender, RoutedEventArgs e)
{
    var compositor = ElementCompositionPreview.GetElementVisual(this).Compositor;
    var canvasDevice = CanvasDevice.GetSharedDevice();
    var graphicsDevice = CanvasComposition.CreateCompositionGraphicsDevice(compositor,
                                                                         canvasDevice);

    var surfaceSize = new Size(400, 400);
    var drawingSurface = graphicsDevice.CreateDrawingSurface(surfaceSize, 
                                              DirectXPixelFormat.B8G8R8A8UIntNormalized, 
                                              DirectXAlphaMode.Premultiplied);

    var width = (float)surfaceSize.Width;
    var height = (float) surfaceSize.Height;

    // Create the combined geometry
    var ellipse1 = CanvasGeometry.CreateEllipse(canvasDevice, width / 2, 
                                          height / 2, 0.45f * width, 0.225f * height);
    var ellipse2 = CanvasGeometry.CreateEllipse(canvasDevice, width / 2, height / 2,
                                          0.225f * width, 0.45f * height);
    var combinedGeometry = ellipse1.CombineWith(ellipse2, Matrix3x2.Identity,
                                                 CanvasGeometryCombine.Union);

    using (var session = CanvasComposition.CreateDrawingSession(drawingSurface))
    {
        session.FillGeometry(combinedGeometry, Colors.Black);
    }

    var surfaceBrush = compositor.CreateSurfaceBrush(drawingSurface);
    var maskBrush = compositor.CreateMaskBrush();
    maskBrush.Mask = surfaceBrush;
    maskBrush.Source = compositor.CreateColorBrush(Colors.Red);

    var visual1 = compositor.CreateSpriteVisual();
    visual1.Size = surfaceSize.ToVector2() * 0.5f;
    visual1.Offset = new Vector3(100, 100, 0);
    visual1.Brush = maskBrush;
            
    ElementCompositionPreview.SetElementChildVisual(this, visual1);
}
```

### Scenario 2
When I apply a mask to a **SpriteVisual**, the mask is not applied to its children in its visual tree. Is there a way to enforce it (rather than traverse through the visual tree and apply it manually)?

**Comment by ratishphilip** [comment]
I found the solution to **Scenario 2** myself. The simple answer is: _**Use a LayerVisual**_.

Here is the sample code (_I have used [**CompositionProToolkit**](https://github.com/ratishphilip/CompositionProToolkit) for generating the mask_)

```C#
private void InitComposition()
{
    Compositor compositor = ElementCompositionPreview.GetElementVisual(this).Compositor;
    ICompositionGenerator generator = CompositionGeneratorFactory.GetCompositionGenerator(compositor);
    
    //// Create the combined geometry
    var ellipse1 = CanvasGeometry.CreateEllipse(canvasDevice, width / 2, height / 2, 0.45f * width, 0.225f * height);
    var ellipse2 = CanvasGeometry.CreateEllipse(canvasDevice, width / 2, height / 2, 0.225f * width, 0.45f * height);
    var combinedGeometry = ellipse1.CombineWith(ellipse2, Matrix3x2.Identity, CanvasGeometryCombine.Union);

    var visualLayer = compositor.CreateLayerVisual();
    visualLayer.Size = surfaceSize.ToVector2();
    visualLayer.Offset = new Vector3(400, 100, 0);

    var v1 = compositor.CreateSpriteVisual();
    v1.Size = new Vector2(300, 300);
    v1.Brush = compositor.CreateColorBrush(Colors.Red);
    v1.Offset = new Vector3(30, 30, 0);
    visualLayer.Children.InsertAtTop(v1);

    var v2 = compositor.CreateSpriteVisual();
    v2.Size = new Vector2(300, 300);
    v2.Brush = compositor.CreateColorBrush(Colors.YellowGreen);
    v2.Offset = new Vector3(130, 130, 0);
    visualLayer.Children.InsertAtTop(v2);

    // Create the effect to create the opacity mask
    var layerEffect = new CompositeEffect
    {
        // CanvasComposite.DestinationIn - Intersection of source and mask. 
        // Equation: O = MA * S
        // where O - Output pixel, MA - Mask Alpha, S - Source pixel.
        Mode = CanvasComposite.DestinationIn,
        Sources =
                {
                    new CompositionEffectSourceParameter("source"),
                    new CompositionEffectSourceParameter("mask")
                }
    };

    var layerEffectFactory = compositor.CreateEffectFactory(layerEffect);
    var layerEffectBrush = layerEffectFactory.CreateBrush();

    var layerMask = generator.CreateMask(surfaceSize, combinedGeometry);
    layerEffectBrush.SetSourceParameter("mask", compositor.CreateSurfaceBrush(layerMask.Surface));

    visualLayer.Effect = layerEffectBrush;
    
    ElementCompositionPreview.SetElementChildVisual(this, visualLayer);
}
```
![layer_mask](https://cloud.githubusercontent.com/assets/7021835/17701992/eb102f72-6380-11e6-83be-e0330909109f.png)

**Comment by sohchatt** [comment]
Thank you for the images for context. Since you already figured out Scenario 2, all you need is to add in one (or two) lines of code for Scenario 1! 
You need to adjust the [Stretch ](https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.composition.compositionsurfacebrush.stretch.aspx)and [Vertical ](https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.composition.compositionsurfacebrush.verticalalignmentratio.aspx)/ [Horizontal ](https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.composition.compositionsurfacebrush.horizontalalignmentratio.aspx) AlignmentRatio properties on your CompositionSurfaceBrush! The default behavior for Stretch is [Uniform](https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.composition.compositionstretch.aspx), thence the result you're seeing. It seems like what you're looking for is CompositionStretch.None.

Also, in the Anniversary Update, we added new properties on SurfaceBrush to mirror all the transformations on Visual (anchorPoint, centerPoint, offset, rotationAngle, scale, transformMatrix), so, should you wish to do something more custom depending on more complicated scenarios (something not addressed by simply using Stretch and Alignment), you can achieve those too. 

Hope this helps.

**Comment by ratishphilip** [comment]
@sohchatt Thanks a lot. Those are the properties I was looking for. 
I must have missed those properties during my initial investigation.
