### ISSUE TITLE
How to make a visual with a "cutout" that uses a shape's GetAlphaMask() result?

### ISSUE THREAD

**Issue by BillHenning** [Microsoft/WindowsUIDevLabs#148]
Hello, I'm relatively new to the visual layer so please excuse any newbie-ness.  I'm trying to make a large solid color Visual that would block the current view and then have a shape in the center of it that is "cut out" of it.  The shape comes from a XAML Path.GetAlphaMask() call.  Then the idea would be to animate that cutout shape in a zoom in fashion to reveal the full screen behind it.

It seems like this would need to be done with some combination of effects, a backdrop brush, etc. but I'm having trouble making headway on this.  I know the CompositionProToolkit might support this, but I'm trying to sort out how to do it without any complex libraries attached.

Any help is appreciated!

**Comment by robmikh** [comment]
Fundamentally you would achieve this using a `CompositeEffect`, but in a different way than we've demoed before. If you look at the effect description for a `CompositeEffect`, you'll notice that there is a `Mode` property. In your case, you'll want to set this to `CanvasComposite.DestinationOut`. What this will do is use the mask to remove non transparent pixels from the destination (in your case it would be a `ColorSourceEffect`). From there you should be able to animate the visual as you please!

Here's a reference for the effect description you would use:

```
var effectDescription = new CompositeEffect
{
    Mode = Microsoft.Graphics.Canvas.CanvasComposite.DestinationOut,
    Sources =
    {
        new ColorSourceEffect { Color = Colors.Blue },
        new CompositionEffectSourceParameter("mask")
    }
};

var effectFactory = compositor.CreateEffectFactory(effectDescription);
var effectBrush = effectFactory.CreateBrush();
effectBrush.SetSourceParameter("mask", alphaMask);
```

**Comment by BillHenning** [comment]
Hi @robmikh, thanks that gets me most of the way there.  I made a SpriteVisual and assigned the effectBrush (from your logic) to its Brush property.  I set the size of the SpriteVisual to the size of the logo, center it in the window, and see the cutout fine.  

The problem now is that I need to "bleed" the edges of the sprite using my background color (Blue in your code above) all the way to the edges of the window.  And then fire off a scale zoom animation that will grow the cutout so that it consumes the entire window contents and all this Blue background moves out of the way.  

Any suggestions on how I get the window area surrounding this sprite visual to be filled with Blue and also animate such that it's not interfering with the cutout scale zoom?

**Comment by robmikh** [comment]
For that you'll want to chain yet another effect!

```
var alphaMask = MyControl.GetAlphaMask();
var myControlSize = new Vector2((float)MyControl.ActualWidth, (float)MyControl.ActualHeight);
var pageSize = new Vector2((float)ActualWidth, (float)ActualHeight);

var effectDescription = new CompositeEffect
{
    Mode = Microsoft.Graphics.Canvas.CanvasComposite.DestinationOut,
    Sources =
    {
        new ColorSourceEffect { Color = Colors.Blue },
        new Transform2DEffect
        {
            Source = new CompositionEffectSourceParameter("mask"),
            // You can think of this matrix as setting the CenterPoint of mask to
            // be in the center of the mask (the same size as the control it came
            // from), setting the Offset to be the middle of the page, and applying
            // a scale of 0.5f.
            TransformMatrix = Matrix3x2.CreateTranslation(myControlSize / -2.0f) *
                              Matrix3x2.CreateTranslation(pageSize / 2.0f) *
                              Matrix3x2.CreateScale(0.5f) *
                              Matrix3x2.CreateTranslation(myControlSize / 2.0f)
        }
    }
};

var effectFactory = compositor.CreateEffectFactory(effectDescription);
var effectBrush = effectFactory.CreateBrush();
effectBrush.SetSourceParameter("mask", alphaMask);

var visual = compositor.CreateSpriteVisual();

visual.Size = pageSize;
visual.Brush = effectBrush;

ElementCompositionPreview.SetElementChildVisual(this, visual);

// Hide the control
var controlVisual = ElementCompositionPreview.GetElementVisual(MyControl);
controlVisual.Opacity = 0;
```

The effect in question is the `Transform2D` effect, which allows you to apply a 3x2 matrix to an effect source. In this case we'll apply it to the alpha mask. Set the transform in such a way where the mask would be where you want it, and then make sure the visual is set to take up the entire screen (or even larger if you're going to be shrinking and growing the visual, that way you'd never see the edges). You should be able to animate the visual any way you want after that.

The trickiest part of this would be getting the matrix just right. In this example it's kind of static, but remember that you can declare certain effect properties as modifiable when creating the `CompositionEffectFactory`. That way you can apply animations and expressions to the `TransformMatrix` property of the effect brush. Setting up the matrix math in an expression that pulls values from a property set, and then changing the property set when the page changes size, is one use for this.

Let me know if you have any further questions!

**Comment by BillHenning** [comment]
Thanks for all the detail @robmikh, that works well.
