### ISSUE TITLE
HIt Testing a rotated Visual

### ISSUE THREAD

**Issue by ratishphilip** [Microsoft/WindowsUIDevLabs#150]
I am on build **14905** and **SDK 14393**, **Visual Studio 2015 Update 3**. 
I have a visual which I have rotated perspectively like shown below
![rotatedvisual](https://cloud.githubusercontent.com/assets/7021835/17811268/b506b2b8-65d6-11e6-8dec-3f079d0ba1b2.png)

Here is the code which I have used

``` C#
public sealed partial class ProjectionPage : Page
{
    private Matrix4x4 _projectionMatrix;

    public ProjectionPage()
    {
        InitializeComponent();

        Loaded += OnLoaded;
    }

    private void OnLoaded(object sender, RoutedEventArgs e)
    {
        var compositor = ElementCompositionPreview.GetElementVisual(this).Compositor;

        var visual = compositor.CreateSpriteVisual();
        visual.Size = new Vector2(400, 400);
        visual.Offset = new Vector3(200, 200, 0);
        visual.Brush = compositor.CreateColorBrush(Colors.Red);
        visual.CenterPoint = new Vector3(visual.Size * 0.5f, 0);
        visual.RotationAxis = new Vector3(0, 1, 0);
        visual.RotationAngleInDegrees = -60;

        var depth = 500;
        _projectionMatrix = new Matrix4x4(1, 0, 0, 0,
                                            0, 1, 0, 0,
                                            0, 0, 1, -1 * (1 / depth),
                                            0, 0, 0, 1);

        var parent = ElementCompositionPreview.GetElementVisual(CompositionGrid);
        var centerX = 450;
        var centerY = 350;
        var centerZ = 200;
        UpdateParentTransform(parent, depth, centerX, centerY, centerZ);
        ElementCompositionPreview.SetElementChildVisual(CompositionGrid, visual);
    }

    private void UpdateParentTransform(Visual parent, float depth, float centerX, 
        float centerY, float centerZ)
    {
        if (parent == null)
            return;

        _projectionMatrix.M34 = -1 / depth;
        parent.TransformMatrix = Matrix4x4.CreateTranslation(-centerX, -centerY, -centerZ) *
                                _projectionMatrix *
                                Matrix4x4.CreateTranslation(centerX, centerY, centerZ);
    }
}
```

How do I perform hit testing on this visual? That is, given a pointer location on the screen how do I check if the location lies within the projection of the rotated visual?

Also, is there a plan to include pointer interaction support for Composition Visuals in the future?

**Comment by msftdavid** [comment]
Unfortunately, right now there is no simple API level hit-test support that makes hit-testing transformed visuals easy. 

I would imagine you would have similar issues if you were trying to hit-test a scaled visual or a visual that has a non-default AnchorPoint. How have you been hit-testing non-transformed visuals?

Also, in response to the second question, interactions have been an active topic of discussion for us, but I can't comment on any specifics in regards to our future plan. :)

**Comment by ratishphilip** [comment]
@msftdavid 
So far I have only tested non-transformed visual by getting the PointerEvents from its parent and checking whether the point is within the visual's rectangular bounds.

I haven't tested a  scaled visual or a visual that has a non-default AnchorPoint yet.

Well my current idea for hit testing a rotated visual is - Use the projectionmatrix to map the visuals corner points to the 2D screen (not sure how to do this), create a polygon out of these points and check if point is within the polygon.
I wanted to know if there was an easier approach to mapping the corners of the rotated visual on the 2D screen (on which the pointer events are raised).

**Comment by robmikh** [comment]
Currently there isn't a better way. You'll have to walk your tree and multiply matrices together (along with transform components) and then use this matrix to determine the on-screen bounds to do the hittest against.

**Comment by ratishphilip** [comment]
Could you please tell me how to obtain the final matrix (for the above sample code) with which the corners of the visuals should be multiplied to obtain the 2D point on screen?

**Comment by robmikh** [comment]
I'll see if I can throw something together. In the mean time, I wrote some input hit-testing code for a game that I was writing, and then copied the code over to a public repo for a different project. Unfortunately I've kind of neglected this new repo, but the code may be a good start. You can find it [here](https://github.com/robmikh/throwawaygame/blob/master/throwawaygame/Managers/InputManager.cs). It makes the assumption that the only thing set on a `Visual` is `Offset` and `Scale`. In the case of a matrix, you would multiply your multiplied world transform matrix against the local space coordinates to get world space coordinates.

**Comment by ratishphilip** [comment]
@robmikh @msftdavid 
Well, for the past few days I have been browsing through many tutorial sites, trying to understand how projection works. Though I have understood a few concepts, I have having difficulty in mapping them to how it works in Composition.

So far, the basic projection pipeline can be explained in this diagram

![projectionpipeline](https://cloud.githubusercontent.com/assets/7021835/18284633/948c5bb2-741f-11e6-8949-72b0b714ea5a.png)

The coordinates are represented in the *(x, y, z, w)* format.

The local coordinates of an object are first converted to World coordinates. The world coordinates are then transformed to Camera coordinates by multiplying them with the **Camera matrix**. The resulting coordinates are multiplied with the **Projection Matrix**. The coordinates which are obtained are checked if they lie within the viewing frustum and then converted to **Normalized Device Coordinates (NDC)** by dividing the **x**, **y** & **z** values with the **w** value. The **NDC** values are in the range **[-1,1]** in all the three axes. These NDC coordinates are then converted to the screen coordinates.

Now consider the following scenario in UWP Composition

I have a **Grid** called **CompositionGrid** which has the dimensions **1200x800**. I create a **SpriteVisual** of size **200x200** and offset **(500, 300, 0)** and add it to the **CompositionGrid**.

Now, I am setting the Transform Matrix property of the visual representing the SpriteVisual's parent i.e. **CompositionGrid** like this

```C#
var parent = ElementCompositionPreview.GetElementVisual(CompositionGrid);

var depth = 500;
var projectionMatrix = new Matrix4x4(1, 0, 0, 0,
                                     0, 1, 0, 0,
                                     0, 0, 1, -1 * (1 / depth),
                                     0, 0, 0, 1);
                                    
var centerX = 600;
var centerY = 400;
var centerZ = 0;

var perspectiveMatrix = Matrix4x4.CreateTranslation(-centerX, -centerY, -centerZ)
                        * projectionMatrix
                        * Matrix4x4.CreateTranslation(centerX, centerY, centerZ);
                        
parent.TransformMatrix = perspectiveMatrix;
```

Now I am rotating the SpriteVisual by **-45** degrees on the Y-axis along its center.

```C#
var rotation = (float)(-45.0 * Math.PI / 180f);
visual.TransformMatrix = Matrix4x4.CreateRotationY(rotation, new Vector3(100, 100, 0));
```

The SpriteVisual now looks like this

![3dprojection](https://cloud.githubusercontent.com/assets/7021835/18284649/a0fc830e-741f-11e6-9b57-fcda3b8728f0.png)

Now I need to calculate the 2D coordinates of the visual's corners projected on the screen. Let's take the topleft corner first.

Initally the topleft corner has the same value as the Offset of the visual i.e. **(500, 300, 0)**. This is the world coordinate of the topleft corner. If I am understanding correctly, the camera matrix here is **Matrix4x4.Identity** and is located at the center of the **CompositionGrid** looking into the **-Z axis**.
So the camera coordinates remain the same.

After rotation the value can be obtained by

```C#
var topLeftRotated = Vector3.Transform(topleft, 
    Matrix4x4.CreateRotationY(rotation, new Vector3(100, 100, 0)));
```

Now I am stuck here and not sure what should be done next.
- Should the **topLeftRotated** be multiplied with the **projectionMatrix** or **perspectiveMatrix**?
- Why is the projectionMatrix applied to the parent instead of child?
- How to define the viewing frustum? What role does the **depth** play in the **projectionMatrix**. Is it related to the viewing frustum? 
- How to check whether the projected point lies within the viewing frustum?
- How to convert the projected point to NDC coordinates?
- How to convert the NDC coordinates to screen coordinates?

Whatever I have mentioned above is based on my understanding of the projection concept. Kindly correct me wherever I am wrong.

**Comment by Ciders** [comment]
Pointer Interaction with 3D Visuals is an important concept particularly for UI elements.

If a XAML object is manipulated using CompositeTransform3D, it will still respond to pointer interactions.

**Comment by daneuber** [comment]
Thanks for the feedback. Please feel free to file a feature request in the backlog [here ](https://developer.microsoft.com/en-us/windows/platform/features) so we can prioritize this among our other backlog items.
