### ISSUE TITLE
Connected Animation link in app broken

### ISSUE THREAD

**Issue by ScottIsAFool** [Microsoft/WindowsUIDevLabs#151]
If you click on the "click here" link in the app for the connected animation, the GitHub link it takes you to is broken.

**Comment by msftdavid** [comment]
Apologies for the delay. It seems like this is an issue that affects multiple samples. The fix for this issue is currently in progress - we're identifying the samples for which the link is broken and updating the FWLinks to point to the correct locations.

**Comment by msftdavid** [comment]
The FWLinks have been updated to reflect the new directory name. They should work properly now.
