### ISSUE TITLE
TextShimmer crashes on mobile.

### ISSUE THREAD

**Issue by karmaecrivain94** [Microsoft/WindowsUIDevLabs#154]
Having a PointLight with a textblock as target (or maybe the target doesn't matter, I didn't have time to check) in the same way as the TextShimmer sample seems to crash when run on windows 10 mobile. Not just crash the app, but freeze the phone and force it to reboot. Are there any alternative ways to get this effect?

**Comment by sohchatt** [comment]
Sorry to hear about your issue, and thank you for bringing this to our attention. Can you please share some more details with us:

1. Which device are you running your app on?
2. Which build do you experience this behavior on?
3. Would it be possible to share your code with us? Only the parts relevant to the use of PointLight may suffice if this is something you cannot disclose in its entirety.

We'll look into it as soon as we have the relevant information and share out our findings with you.

**Comment by karmaecrivain94** [comment]
Thanks for your quick answer.
1. I'm running it on a Lumia 830
2. Build 14905.1, but this isn't an issue new to this build. I'd noticed that the TextShimmer sample didn't work on the Sample Gallery app about a month ago (can't remember which build).
3. I could, but I'm not sure it's necessary. The app from the SampleGallery makes my phone crash too: https://github.com/Microsoft/WindowsUIDevLabs/tree/master/SampleGallery/Samples/SDK%2014393/TextShimmer

The work you guys are doing on Composition is amazing btw :)

**Comment by karmaecrivain94** [comment]
Any updates? Have you been able to reproduce the crash?

**Comment by sohchatt** [comment]
Unfortunately, @karmaecrivain94 , this behavior is due to a hardware-specific (Lumia 830 in your case) issue, which has been fixed. You should not experience any such issues with Composition Lights in the next Insider build. Again, thanks for  bringing this to our attention and we hope that you can let us know whether your issue has been addressed in future builds.

**Comment by msftdavid** [comment]
Closing this issue. Please re-open if you are still running into this issue in the new Insider build.
