### ISSUE TITLE
.pfx files missing from Animations_Expressions Project folders

### ISSUE THREAD

**Issue by jhurdlow** [Microsoft/WindowsUIDevLabs#156]
All four projects in the Animations_Expressions solution reference .pfx files, but the files are not in the repository.

**Comment by patsiu** [comment]
Hey @jhurdlow!

Sorry for the delay here. You can generate new test certificates for the projects to get rid of the message you'd see in the output window when compiling (Let me know if you need some help with this). Outside of that, was there another specific issue you were running into?

Thanks!

**Comment by msftdavid** [comment]
Seems like this issue is resolved. Closing.
