### ISSUE TITLE
Unhandled win32 error with connected animations

### ISSUE THREAD

**Issue by andrejt** [Microsoft/WindowsUIDevLabs#158]
To repro, change the Grid element in ConnectedAnimationDetail.xaml (one of WindowsUIDevLabs samples) to include a GridView element before the Image that's being animated:

``` xaml
<Grid>
    <GridView/>
    <Image x:Name="PhotoImage" Margin="50" VerticalAlignment="Center" HorizontalAlignment="Center" />
</Grid>
```

Win32 exception occurs when navigating from ConnectedAnimationDetail.xaml **back** to ConnectedAnimationSample.xaml.

On the other hand, inserting an element after the Image, the animation works fine:

``` xaml
<Grid>
    <Image x:Name="PhotoImage" Margin="50" VerticalAlignment="Center" HorizontalAlignment="Center" />
    <GridView/>
</Grid>
```

Using SDK 14393.

**Comment by msftdavid** [comment]
Thank you for letting us know about this issue. Just so we have more information, what build were you running when you ran into this issue?

**Comment by andrejt** [comment]
Windows 10 Pro 1607 14393.105, SDK 14393 set to both target and min version.

**Comment by JasterAtMicrosoft** [comment]
Thanks for the simple repro steps. I've filed an internal product bug for this. Please feel free to reopen if you need help with a workaround.

Thanks,
Jake
