### ISSUE TITLE
Saving textblock with CompositionShadow on Canvas control to file does not save its shadow

### ISSUE THREAD

**Issue by Monsok** [Microsoft/WindowsUIDevLabs#159]
I am trying to save a Textblock with shadow created using CompositionShadow control. The Textblock is a children of a Canvas control

```
<Grid Background="Transparent">
        <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="*"/>
            <RowDefinition Height="Auto"/>
        </Grid.RowDefinitions>
        <Canvas x:Name="canvas">
            <controls:CompositionShadow BlurRadius="5" ShadowOpacity=".7" OffsetX="5" OffsetY="5"
                    VerticalAlignment="Center"
                    HorizontalAlignment="Center">
                <TextBlock TextWrapping="Wrap" FontSize="48" FontWeight="Bold">
                        Lorem ipsum dolor sit amet.
                </TextBlock>
            </controls:CompositionShadow>

        </Canvas>
        <Button x:Name="btnSave" Content="Save" Click="btnSave_Click" Grid.Row="1" />
    </Grid>
</Grid>
```

In my code behind I have 

```
 private async void saveTextToFile(StorageFile file)
        {
            RenderTargetBitmap renderTargetBitmap = new RenderTargetBitmap();
            await renderTargetBitmap.RenderAsync(this.canvas);
            IBuffer pixelBuffer = await renderTargetBitmap.GetPixelsAsync();

            var width = renderTargetBitmap.PixelWidth;
            var height = renderTargetBitmap.PixelHeight;

            using (IRandomAccessStream stream = await file.OpenAsync(FileAccessMode.ReadWrite))
            {
                var encoder = await
                BitmapEncoder.CreateAsync(BitmapEncoder.PngEncoderId, stream);
                var displayInformation = DisplayInformation.GetForCurrentView();

                byte[] pixels = pixelBuffer.ToArray();
                encoder.SetPixelData(BitmapPixelFormat.Bgra8,
                                     BitmapAlphaMode.Premultiplied,
                                     (uint)width, (uint)height,
                                     displayInformation.RawDpiX,
                                     displayInformation.RawDpiY,
                                     pixels);

                await encoder.FlushAsync();
            }
        }
```

However as you can see below the shadow is not saved. So how do I make sure the shadow of the Textblock is also saved?

![test_20160907150412](https://cloud.githubusercontent.com/assets/21212986/18303040/a29db6e4-750d-11e6-8b59-b7b32cf045c2.png)

**Comment by msftdavid** [comment]
Unfortunately, RenderTargetBitmap does not capture the Composition shadow or any Composition visuals manually inserted below the XAML element.

I'm not aware of an easy way to perform the capture that you're looking for. If using pre-baked assets is an option (just having an image in your project of the text with the appropriate shadow), that would be my recommendation at the moment.

**Comment by tomzorz** [comment]
Can't you have a backdropbrush, and than use that in a win2d canvas, which you can save as a file? I think that could work.

**Comment by robmikh** [comment]
You can't texture from Composition surfaces.

**Comment by tomzorz** [comment]
:( I guess that's a new feature request then. If I remember correctly this is not the first time people wanted to save composition content. (I wanted a faster rendertargetbitmap anyway.)

**Comment by sernaj** [comment]
Good news. This issue was addressed in the Creator's Update 15063 - which is the current available version. As of that release earlier this year (2017) all composition content including shadows should be useable by RTB. Let us know if there is any issue with this.
