### ISSUE TITLE
Connected animations - ListViews "disappearing"?

### ISSUE THREAD

**Issue by andrejt** [Microsoft/WindowsUIDevLabs#161]
Hi,

I have a page with SplitView, where compact Pane contains a ListView for rendering navigation items. SplitView content contains a master page that uses a connected animation for transitioning to details page. That part works fine (except for my previously reported issue). Both master and details page have a GridView control.
The problem is - when navigated to the details page, ListView(s) inside SplitView pane disappear (i.e. are rendered with background color). 

Resizing the window makes them appear again.
Other controls seem to render fine so I temporarily replaced my ListViews with butons in a stackpanel.

A bug, perhaps?

**Comment by JasterAtMicrosoft** [comment]
Hi @andrejt,

Could you attach a project that demonstrates your issue? Sounds like it could definitely be a rendering bug.

Thanks,
Jake

**Comment by andrejt** [comment]
Hi @JasterAtMicrosoft, I'm attaching a minimal repro project. When run, select any item on the right side - the frame will connected-animate to a details page and navigation icons on the left side will disappear (but not the hamburger button!). Resize the window (or even just tap the hamburger) and icons will reappear.

[WUI.ZIP](https://github.com/Microsoft/WindowsUIDevLabs/files/484654/WUI.ZIP)

**Comment by JasterAtMicrosoft** [comment]
Thanks Andrej! We're investigating this bug internally. It sounds like you were able to work around it so I'm going to close this issue for now.

Thanks,
Jake
