### ISSUE TITLE
[API Request]GetAlphaMask for all UIElement

### ISSUE THREAD

**Issue by h82258652** [Microsoft/WindowsUIDevLabs#162]
I try the sample and I found only Image, Shape and TextBlock have GetAlphaMask method.
There should all the UIElement have this method.
I put a Border(with CornerRadius) into a CompositionShadow control.
But the CompositionShadow control do not handle the CornerRadius.
![qq 20160914112824](https://cloud.githubusercontent.com/assets/5144550/18499095/616e5b04-7a6e-11e6-9e30-df5ba77946a7.jpg)

**Comment by jeffstall** [comment]
AFAIK, I don’t believe that this is possible to do today with just Xaml and Composition APIs. Shadows are not computed for children visuals, only for the parent visual. Therefore, even if you have a child Border element that has a rounded corner, the parent Element Image / Shape / TextBlock that you’re calling GetAlphaMask() on won’t take the Border child element into account.

You could solve this by writing your own custom rendering in Win2D into a CompositionDrawingSurface, wrapping with a SurfaceBrush, and then providing the brush as the DropShadow.Mask property.

Thanks!
~ Jeff

**Comment by ratishphilip** [comment]
@h82258652 You can use [CompositionProToolkit](https://github.com/ratishphilip/CompositionProToolkit) to achieve the masking.
