### ISSUE TITLE
Wrong link for "List of talks for BUILD 2016 that can be watched on Channel9"

### ISSUE THREAD

**Issue by robert-virkus** [Microsoft/WindowsUIDevLabs#170]
The link "List of talks for BUILD 2016 that can be watched on Channel9" on the projects homepage (https://github.com/Microsoft/WindowsUIDevLabs)  
leads to 
https://github.com/Microsoft/WindowsUIDevLabs/wiki/Windows-UI-Newsletter---May-Edition#build-sessions
which does not exist.

**Comment by msftdavid** [comment]
Thanks for reporting the issue. It looks like we changed the name of the first issue of the newsletter and forgot to update the link in the homepage.

The updated link is this one: https://github.com/Microsoft/WindowsUIDevLabs/wiki/Windows-UI-Newsletter---Volume-1#build-sessions

I will update the link shortly. Until then, feel free to go to the address above.

**Comment by msftdavid** [comment]
The link has been updated.
