### ISSUE TITLE
Adding effects to an UIElement affects WebView

### ISSUE THREAD

**Issue by AppXDevWP** [Microsoft/WindowsUIDevLabs#172]
Adding any effect to an UIElement which may or may not contain a WebView control makes the WebView stop working. This makes it unresponsive to any events like click, scroll, etc.

Please fix this.

**Comment by hanselo** [comment]
Hi @AppXDevWP - thanks for reporting this issue!  Could you please tell me what you're trying to accomplish and what you mean by WebView stop working?

For example, are you trying to load a web page on WebView, apply a desaturation effort to the WebView, and subsequently finding that you are no longer able to scroll or push buttons on the WebView?

If you have an example code that demonstrates this problem, that would help a lot with the investigation.

Thanks again!

**Comment by AppXDevWP** [comment]
Hi.

It is very easy to replicate this issue. Let's just say you are applying a temperature tint effect (I was using this, but I checked and turns out it affects all effects) to the LayoutRoot of a page.

On setting this effect, if the page had a WebView, it would cause it to not respond to any clicks, scrolls, etc.

I used the standard code for setting a sprite visual to a grid compositor, but replaced the effect with Temperature Tint effect (but as I have mentioned, all effects have the same issue)

Thanks,
P

**Comment by hanselo** [comment]
Hi @AppXDevWP - I looked at this a little bit.  Are you applying an effect onto a CompositionBackdropBrush that you place (in the visual tree) in front of the WebView element?  If so, then you are essentially placing something in front of the WebView that would receive all interactions from that point on (hence why you're not able to interact with it).

To be sure, though, would you mind sharing your code/project for me to verify what's happening in the visual tree?  thanks!

**Comment by AppXDevWP** [comment]
Sorry for delay @hanselo 

I am applying the effect to the LayoutRoot of that page and the WebView is present in its visual tree. I can interact with everything except the WebView when the effect is applied. 

Here is my code:

`var gridVisual = ElementCompositionPreview.GetElementVisual(LayoutRoot);

                var compositor = gridVisual.Compositor;

                var effectVisual = compositor.CreateSpriteVisual();

                effectVisual.Size = new Vector2(
                  (float)100,
                  (float)100);

                TemperatureAndTintEffect blurEffect = new TemperatureAndTintEffect()
                {
                    Temperature = (float)settings.Values["FluxValue"],
                    Source = new CompositionEffectSourceParameter("source")
                };

                var effectFactory = compositor.CreateEffectFactory(blurEffect);
                var effectBrush = effectFactory.CreateBrush();
                effectBrush.SetSourceParameter("source", compositor.CreateBackdropBrush());

                effectVisual.Brush = effectBrush;

                ElementCompositionPreview.SetElementChildVisual(LayoutRoot, effectVisual);`

**Comment by AppXDevWP** [comment]
Unfortunately, I cannot share the code of my actual project, but I can hook you up a temporary project to test.

**Comment by hanselo** [comment]
@AppXDevWP thanks for that sample code.  I'll try it out on a test project and get back to you asap.

**Comment by AppXDevWP** [comment]
@hanselo the xaml of the page is like this:

<Page ...>
<Grid Name="LayoutRoot">
...
<WebView .../>
...
</Grid>

**Comment by hanselo** [comment]
@AppXDevWP yep, I created a test app with your code and have communicated your scenario to my team ("Customer wants to apply an effect over a WebView").

We are currently triaging the issue to determine what the proper resolution should be.

Thanks again for using our APIs and reporting this issue!

**Comment by hanselo** [comment]
Hi @AppXDevWP - my apologies for the long delay since our last correspondence.

Placing a visual with a backdrop brush and effects over a webview prevents further interaction with the webview because you are essentially placing a "transparent" (with effects) object in front of the webview - sort of like putting something inside a glass case.

Alternatively, have you tried using a layer visual? https://msdn.microsoft.com/en-us/library/windows/apps/Windows.UI.Composition.LayerVisual.aspx

**Comment by hanselo** [comment]
At this time, we don’t have a way to enable your scenario just yet, but the team has received your feedback and we are using your feedback to prioritize enabling this scenario for future releases.  Thanks again for your valuable feedback!
