### ISSUE TITLE
Request: Add a boolean property to disable the ScrollViewer overscroll effect

### ISSUE THREAD

**Issue by h82258652** [Microsoft/WindowsUIDevLabs#173]
sometimes the overscroll effect is terrible, like in the FlipView. But I can not find a way to disable it.
Please add a switch to turn on/off the overscroll effect.

**Comment by daneuber** [comment]
Thanks for the feedback. Please feel free to file a feature request in the backlog [here ](https://developer.microsoft.com/en-us/windows/platform/features) so we can get this routed to the correct team.
