### ISSUE TITLE
Function bindings do not evaluate properly when using x:DeferLoadStrategy

### ISSUE THREAD

**Issue by JohnnyWestlake** [Microsoft/WindowsUIDevLabs#174]
Hey folks,

I'm using function bindings inside one of my controls.

I have XAML like the following,

```
<Button x:Name="Target" IsHitTestVisible="True" />
<Grid x:Name="TestGrid" x:DeferLoadStrategy="Lazy">
     <Button Visibility="{x:Bind Invert(Target.IsHitTestVisible), Mode=OneWay}" Content="You cannot see me" />
</Grid>
```

And the "Invert" method defined as :

```
public Visibility Invert(bool value) => (!value == true) ? Visibility.Visible : Visibility.Collapsed;
```

Problem: When I finally realize "TestGrid", the button is always visible. _IF_ I take the `x:DeferLoadStrategy="Lazy"` off the grid, everything works as expected and I cannot see the button.

Is this a known issue? 

Using VS 15 Preview 5, 10.0.14393.0 SDK, on an Anniversary Update PC.

**Comment by JasterAtMicrosoft** [comment]
Thanks for getting in touch Johnny! Routing this to our x:Bind experts...

**Comment by samsp** [comment]
Not previously known - but yes, its a bug. It seems that we have the wrong logic when a deferred element has its value coming from a function binding.

**Comment by JasterAtMicrosoft** [comment]
Closing this issue as we are tracking this bug internally.

Thanks,
Jake
