### ISSUE TITLE
Pinch-to-zoom gesture with InteractionTracker

### ISSUE THREAD

**Issue by JustinXinLiu** [Microsoft/WindowsUIDevLabs#176]
I am trying to create zoom and pan gestures using the `InteractionTracker` with the following code.

```
_interactionSource = VisualInteractionSource.Create(_rootVisual);
_interactionSource.PositionXSourceMode = InteractionSourceMode.EnabledWithInertia;
_interactionSource.PositionYSourceMode = InteractionSourceMode.EnabledWithInertia;
_interactionSource.IsPositionXRailsEnabled = false;
_interactionSource.IsPositionYRailsEnabled = false;
_interactionSource.ScaleSourceMode = InteractionSourceMode.EnabledWithInertia;
_interactionSource.ManipulationRedirectionMode = VisualInteractionSourceRedirectionMode.CapableTouchpadOnly;

_tracker = InteractionTracker.Create(_compositor);
_tracker.InteractionSources.Add(_interactionSource);
_tracker.MaxPosition = new Vector3(_rootVisual.Size.X, _rootVisual.Size.Y, 0.0f) * 10.0f;
_tracker.MinPosition = _tracker.MaxPosition * -1.0f;
_tracker.MinScale = 0.9f;
_tracker.MaxScale = 12.0f;
_tracker.ScaleInertiaDecayRate = 0.95f;

var positionAnimation = _compositor.CreateExpressionAnimation("-t.Position");
positionAnimation.SetReferenceParameter("t", _tracker);
_pathContainerVisual.StartAnimation("Offset", positionAnimation);

var scaleAnimation = _compositor.CreateExpressionAnimation("Vector2(t.Scale, t.Scale)");
scaleAnimation.SetReferenceParameter("t", _tracker);
_pathContainerVisual.StartAnimation("Scale.XY", scaleAnimation);
```

The code almost works perfectly, except that when I pinch or stretch slowly, the zoom animation becomes really jerky. I can clearly see the path objects shake all the way.

I suspect it's caused by `CenterPoint` movement but I am not sure what's the best way to work around this.  Normally I'd create a collection to store touch points (so I could calculate their center point) after `PointerPressed` and remove them after `PointerReleased`, but since the manipulation is now handled by the tracker, `PointerReleased` doesn't fire anymore. 

Any tips?

Full source code can be found [here](https://github.com/JustinXinLiu/PanAndZoomWithInteractionTracker).

**Comment by JustinXinLiu** [comment]
I actually managed to monitor fingers up/down by implementing the `IInteractionTrackerOwner` interface. So after some digging I found that the issue might be related to the `Position` value of the tracker.

Even when I have the X & Y source mode disabled, the `Position` of the tracker still somehow gets calculated, and because I am also using the `Position` to calculate the `Offset` of the container visual in the expression, this then causes elements within the visual to get _shaky_ when zooming happens.

```
_interactionSource.PositionXSourceMode = InteractionSourceMode.Disabled;
_interactionSource.PositionYSourceMode = InteractionSourceMode.Disabled;
```

Is this a bug or by design?

I also tried using multiple tracker with multiple sources _or_ one tracker with multiple sources. Neither worked as expected. I figure that if I want to achieve free-style panning and zooming like what the `ScrollViewer` does, I can't really split up the gestures and assign them to more than one sources.

**Comment by patsiu** [comment]
Hey @JustinXinLiu,

Going to jump in here real quick - the jerky and jittering movement that you're seeing when zoom real slowly is something that we're already aware of and taking a look at. Unfortunately, we don't have a workaround at the moment, but thanks for bringing this up!

**Comment by JustinXinLiu** [comment]
@patsiu thanks for the update. Also I noticed that the tracker doesn't support rotation animation yet. Is it coming as a new feature in the future?

**Comment by likuba** [comment]
Thanks @patsiu :)
@JustinXinLiu -- we'll let you know when we have insider builds with zoom bug fixes to see if they help with your problems.  In addition, we've definitely thought about adding support for rotation, but currently have a few other things higher in the backlog.  Knowing people are interested though definitely helps us understand the right priority going into future releases.  Is there a specific scenario you have in mind so that we can understand more about how developers would want to use a rotate feature?

**Comment by JustinXinLiu** [comment]
@likuba Basically we want to give users the freedom to do whatever you want within the canvas. We are currently working on a [new UWP app](https://www.drawboard.com/bullclip/) and having rotation support would allow users to see content within the canvas in any angle, on a large monitor.

**Comment by likuba** [comment]
Thanks @JustinXinLiu :)  As you can imagine freeform direct manipulation is the main use case we have heard for the rotation gesture.

Some of the zoom bug fixes are in the recent insider builds, but there are more to come.  Seen any improvements here? In addition to the bug fixes, there should be some new APIs/animatable properties coming to help you have a bit more control over your centerpoint as well as movement in response to input on a VisualInteractionSource.

That being said, you should be able to use multiple sources for one tracker or multiple trackers, as long as they have different source visuals--what was unexpected about the behavior you saw there?  I'm curious if it is a bug or we just didn't explain the design/policy well enough.  Upon a call to the TryRedirect*, we route the input to the tracker by finding the childmost hittested visual for the contact with a VisualInteractionSource configuration matching the gesture being performed.  Multiple contacts on different visuals will parent promote to the first common parent with a VisualInteractionSource configuration that matches the gesture being performed.  The app root under the covers is configured for all gestures so if the input doesn't match the VisualInteractionSource configurations it would go to the CoreWindow and follow the normal flow of input.

**Comment by JustinXinLiu** [comment]
@likuba I haven't got a chance to test it in the latest build but I will definitely do and let you know!

When I was testing multiple sources for one tracker and multiple trackers, I found that I couldn't do freeform gesture. For example, I couldn't change the swipe from horizontal to vertical once the panning started. It almost feels like manipulating a `ScrollViewer` with its `IsHorizontalRailEnabled` & `IsVerticalRailEnabled ` enabled.

However I can sort of understand why since there are multiple sources listening to the same input. So I guess this is by design?

**Comment by JustinXinLiu** [comment]
Haha I was just messing around to see if I could get rid of the jerky zooming experience. :)

If the zoom bug has already been fixed in a later build, I don't think I will need multiple sources at all! I will test it out and let you know. Could you please tell me which build has got the zoom fix?

**Comment by JustinXinLiu** [comment]
Hey @likuba so I just installed the new build `15007` and also updated the  SDK to `15003`. Now when I run the source project attached in my original post, nothing shows up. Looks like it's got something to do with the `InteractionTracker`, when I comment out its related code the paths load up fine.

**Comment by JustinXinLiu** [comment]
Hey @likuba wonder if you have seen my previous comment regarding the `InteractionTracker` stopping to work in the Creators SDK? :)

**Comment by likuba** [comment]
Hey--sorry I missed your last message.  Thanks for pulling this back to the top of the list.
We definitely haven't seen this issue internally.  Are you hitting this with our samples as well, or only in your app?  Is the latest repro still on 15007/15003?

I'll track down where the zoom bug fixes are in the pipeline--there were a series of bugs in this space, so most likely you have fixes for a few but not all on your most recent build.

**Comment by JustinXinLiu** [comment]
No worries. :) So if you run my [repo](https://github.com/JustinXinLiu/PanAndZoomWithInteractionTracker) on your internal build everything shows up fine? Interesting, I just tried running it again on my _15046_ build, re-targeting to SDK _15042_ , nothing shows up. However your samples seem to be working fine.

**Comment by likuba** [comment]
Ah sorry, I meant we hadn't seen this as a generic problem--trying out your repo it also was not showing any content on my build either.  Looking at the code, it seems this is just a simple error of the content being placed off-screen :)  In the last release (14393), we had a bug in how we resolved Min & Max position, which I think was clamping some of your values to 0.  Now that your min/max are being correctly honored, your content is ending up way off screen. In this code:

	_tracker.MaxPosition =newVector3(_rootVisual.Size,0.0f) *3.0f;
	_tracker.MinPosition = _tracker.MaxPosition *1.0f;

You are setting MaxPosition == MinPosition == ReallyBigNumber, so your content can only ever be positioned at ReallyBigNumber.  

What I think you intended to do was MinPosition = MaxPosition *-1.0f, which means your content can live anywhere between -ReallyBigNumber, and ReallyBigNumber.

**Comment by JustinXinLiu** [comment]
No wonder! I was confused about that and wondering why `MinPosition` could be the same as `MaxPosition`.

All makes sense now. Thanks @likuba!

**Comment by tmjorud** [comment]
Hello :) 

I see that Justin have closed this issue, but I just wanted to comment on this for other users that might stumble across this, and maybe find this helpful. I think I've been struggling with kind of the same issues that is adressed here. There is something happening with the offset when you scale with the InteractionTracker, that you initially dont have direct control over. In my specific case, I'm using an InteractionTracker to scale a CompositionVirtualDrawingSurface with a very long width along the Y-Axis, in other words, only Scale.Y (not Scale.X). For some reason when I started scaling, the Offset.X was starting to drift, panning me away from the initial position from where I started scaling. To get past this, I used the ConfigureCenterPointXModifiers, which gives me control over the current CenterPoint for the x-axis, based on a condition. Which in my case is whenever the user is scaling. I can then set a value that will be used as the current CenterPointX. Below is the code that solved my issue. This might be of no use for you Justin, but I just wanted to share this. I hope it makes sense :)

`var modifier = CompositionConditionalValue.Create(_compositor);
 var conditionExpression = _compositor.CreateExpressionAnimation("source.DeltaScale != 1");
 var valueExpression = _compositor.CreateExpressionAnimation("-tracker.Position.X");
 conditionExpression.SetReferenceParameter("source", _interactionSource);
 valueExpression.SetReferenceParameter("tracker", _tracker);
 modifier.Condition = conditionExpression;
 modifier.Value = valueExpression;
 _interactionSource.ConfigureCenterPointXModifiers(new CompositionConditionalValue[] { modifier });`

**Comment by likuba** [comment]
Thanks @tmjorud for sharing! This is exactly the type of scenario that caused us to introduce the centerpoint modifiers (we hit something similar when we were first writing interactions3D and wanted the pinch zoom to move along Z offset rather than optical zoom, and at the time had to solve it by creating 2 separate trackers).  Hopefully we'll get ours samples updated soon to show this in action, but it's awesome to have this as an example for anyone who is stuck :)  Thanks again!

**Comment by tmjorud** [comment]
Thanks @likuba, glad to hear :)
