### ISSUE TITLE
Composition Matrix4x4 ExpressionAnimation Exception

### ISSUE THREAD

**Issue by Pierce913** [Microsoft/WindowsUIDevLabs#177]
I am trying to animate a Matrix4x4 using linear interpolation. But this throws an exception.

Exception thrown: 'System.ArgumentException' 
WinRT information: One or more parameters have not been set on the ExpressionAnimation.
Additional information: The parameter is incorrect.

this is the code snippet:
```
var originalMatrix = "origin";
var destinationMatrix = "destination";
var amount = "amount";                        
var expression = compositor.CreateExpressionAnimation($"Matrix4x4.Lerp({originalMatrix}, {destinationMatrix}, {amount})");            
expression.SetMatrix4x4Parameter(originalMatrix, visual.TransformMatrix);
expression.SetMatrix4x4Parameter(destinationMatrix, GlobalTransformDestination.ToMatrix4x4());
expression.SetScalarParameter(amount, .5f);
visual.StartAnimation("TransformMatrix", expression);
```

It throws the exception on the last line.

If i just use
`var expression = compositor.CreateExpressionAnimation($"{originalMatrix}");`
it works fine

Ideas?

**Comment by JustinXinLiu** [comment]
This looks like a bug to me... Just tried a scalar one and it worked, changed to matrix and it failed.

**Comment by Pierce913** [comment]
Ok so I found a workaround... Do the interpolation manually. As you say Justin I think there is a problem with Lerp().

```
var originalMatrix = "o";
var destinationMatrix = "d";
var amount = "a";            
var props = "p";

var str = "Matrix4x4(";
for (var i = 1; i <= 4; i++)
{
	for (var j = 1; j <= 4; j++)
	{
		str += $"o._{i}{j} + (d._{i}{j} - o._{i}{j}) * p.a, ";
	}                
}
str = str.Substring(0, str.Length - 2) + ")";

PropertySet = compositor.CreatePropertySet();
PropertySet.InsertScalar(amount, 0f);
var expression = compositor.CreateExpressionAnimation($"{str}");            
expression.SetMatrix4x4Parameter(originalMatrix, visual.TransformMatrix);
expression.SetMatrix4x4Parameter(destinationMatrix, GlobalTransformDestination.ToMatrix4x4());
expression.SetReferenceParameter(props, PropertySet);
visual.StartAnimation("TransformMatrix", expression);

var animator = compositor.CreateScalarKeyFrameAnimation();
var easing = compositor.EaseOutExpo();
animator.StopBehavior = AnimationStopBehavior.LeaveCurrentValue;
animator.Duration = TimeSpan.FromMilliseconds(time);
animator.InsertKeyFrame(0.0f, 0.0f, easing);
animator.InsertKeyFrame(1.0f, 1.0f, easing);
animator.IterationBehavior = AnimationIterationBehavior.Count;
PropertySet.StartAnimation(amount, animator);
```

**Comment by patsiu** [comment]
Hey @Pierce913 

Thanks for reporting this issue - we are seeing the same behavior where Lerp is not behaving as expected with a 4x4 matrix and looking into it. For now, you will have to do the interpolation manually as you have identified above.

**Comment by Pierce913** [comment]
Cool. Also another related issue. The reason I had to used one letter variable names is because I get an expression too long exception. It would be good if the max length could be increased as it is not long enough when dealing with 4x4 matrices

**Comment by likuba** [comment]
@Pierce913 -- 
You're right--we've noticed a few people hitting the 1000 character limit issue, especially when dealing with matrices.  Unfortunately, for now we need to keep a character limit since ExpressionAnimations run in the system compositor and arbitrarily long expressions could cause system performance issues.  We're looking into a variety of options to mitigate this in the future to allow developers to author more complex expressions without a concern of character limit (which we know is a very simplistic indicator of complexity), but unfortunately for now the best mitigation options are short character names and propertysets that contain pieces of the longer expression.

Hope that helps a little to at least explain why this limitation is in place--it is also helpful for us to know that people are hitting this issue so that we can appropriately prioritize future improvements in this area.

**Comment by Pierce913** [comment]
Is it possible to have dynamic parts of an expression in property sets?

**Comment by Pierce913** [comment]
For anyone interested. I've found the best way to avoid this character limit issue is to chain separate expressions linked by properties in the property set.

**Comment by msftdavid** [comment]
The character limit issue is currently by design. Converting to a feedback item for future consideration.

**Comment by daneuber** [comment]
Thanks for the feedback. Please feel free to file a feature request in the backlog [here ](https://developer.microsoft.com/en-us/windows/platform/features) so we can prioritize this among our other backlog items.
