### ISSUE TITLE
Alternative CompositionShadow - DropShadow performs poorly on Intel integrated GPU

### ISSUE THREAD

**Issue by bgulrich** [Microsoft/WindowsUIDevLabs#178]
I've got a project in which I've wrapped my button shapes the CompositionShadow class provided in your repo.  My target device is a Surface 3 (not Pro) and I've noticed that only a few of these shadows on the screen at any given time, pegs the GPU load at 100%.  I recently removed the call to add the shadow visual to the tree and the GPU load drops to 0 (but of course my shadows are gone).  I tried to create my own drop shadow by applying a black ColorSource to the alphamask of the UIElement and then applying a Gaussian blur, but only hard edges are allowed so my shadow gets clipped (but again my GPU load drops to 0).  I noticed from the API documentation that a visual's shadow isn't clipped by it's container, but it requires a CompositionShadow, but I can't find a way to extend this base class.  Is there any way to accomplish what I'm after?  
-Either to optimize the provided DropShadow so it doesn't eat up my GPU (I can't see a way to set caching or performance/speed tradeoff)
-Or create a more efficient shadow

Thanks!

**Comment by sohchatt** [comment]
hi bgulrich,

DropShadow is certainly not supposed to cause the performance issues you mention: this is something that we'd like to investigate further. Would it be possible for you to share a repro app (and information about the build you were running this on) so we may take a look?

**Comment by bgulrich** [comment]
Thanks for your quick reply.  Below is a screenshot of the attached code running on my laptop which has more power (but higher resolution than the surface 3 I'm targeting).  It just throws a bunch of shapes on the screen with drop shadows behind them in a scroll viewer wrapped wrap grid.  I'm running build 14393.447.  Even when the GPU load isn't maxed out, the scroll viewer lags considerably.  The last photo shows 0% GPU load when the following line is commented out: 

 //ElementCompositionPreview.SetElementChildVisual(ShadowElement, _shadowVisual);

[ShadowTest.zip](https://github.com/Microsoft/WindowsUIDevLabs/files/591125/ShadowTest.zip)

![image](https://cloud.githubusercontent.com/assets/13284399/20293717/5b5fb642-aabe-11e6-98fe-5d4cee34c2d6.png)

![image](https://cloud.githubusercontent.com/assets/13284399/20293725/6ad9547a-aabe-11e6-931b-5848008a4c00.png)

![image](https://cloud.githubusercontent.com/assets/13284399/20293796/d55481f8-aabe-11e6-9763-3d3647a59b40.png)

**Comment by bgulrich** [comment]
P.S. - I'm loving the API!  Please don't make me go back to RenderTargetBitmap :)

**Comment by bgulrich** [comment]
Any word on this?  Can anyone suggest a way to get shadows working without the issues I'm describing?

I've also noticed the "Desktop Window Manager" process' CPU usage goes way up with this demo on the screen.  I didn't mention it in my original post because I figured the high GPU usage was the root cause of this other symptom, but I get very frequent freezes in the UI of my application with this issue.  I'll describe the nature of the freezes below in case it helps, but they disappear COMPLETELY if dropshadows are removed.

FREEZES: everything on my screen freezes (my app and otherwise).  The system doesn't stop responding to input, however.  If I interact with the app using touch, once the UI comes back to life, it's as though all the interactions I did while it was frozen had occured.  Another thing to note is that once, I was presenting in a conference room using a Barco ClickShare USB device and when the UI froze on my laptop screen, it continued running on the remote screen.  I can usually  exit the frozen state by generating a display event either with CTRL+ALT+DEL, resizing the app, etc.

**Comment by bgulrich** [comment]
Same issue on HP Elite x2 with a Core M3 processor.

**Comment by sohchatt** [comment]
Thanks for bringing this to our attention. I know it took a while, but we've located some issues that were hindering DropShadow performance in your use-case (with XAML Shapes hosted in a ScrollViewer) on Surface3. With the new improvements, your application should not cause GPU usage to spike on the next Insider builds that will be released shortly.

In the meanwhile, for older builds, you may wish to create a DropShadow object and reuse it for all the shapes that are of the same type/ size instead of generating a new DropShadow for each shape (here I'm presuming that your actual application isn't generating hundreds of randomly sized XAML Shape objects). This workaround will require you to drop down to the Windows.UI.Composition layer instead of using the CompositionShadow XAML Control from SamplesCommon: there are samples and closed issues that show how you may create a DropShadow object using the Composition APIs and then insert it into your XAML tree.

**Comment by bgulrich** [comment]
Thanks for your response.  I'm glad to hear the fix is coming soon.  I've played around with the insider builds and the performance seems better.  I think I'm going to have to wait for the Creator's update because while many of the UI elements in my app are similar, they are not identical in size/shape, and so unless I'm misunderstanding something, the workaround you described wouldn't apply to my situation.  The composition goodies shown off at developer day look great!
