### ISSUE TITLE
Pixel fitting method

### ISSUE THREAD

**Issue by Pierce913** [Microsoft/WindowsUIDevLabs#179]
I am adding images which contain text to a canvas and then applying a transformation to them with the composition TransformMatrix property. The resultant transformed image seems to lack clarity. I have done the same thing with Win2D using the same transform and it seems to fit the image to the pixels better resulting in much crisper text. Is there any way to adjust the pixel rounding/fitting when using composition transforms?

**Comment by sohchatt** [comment]
Can you share more details about the transformation you're applying through SpriteVisual.TransformMatrix?

**Comment by Pierce913** [comment]
It includes a scale and translate. When I scale the XAML canvas I insert a new higher dpi images to compensate. This keeps it crisp if I apply the transform with Win2D. but fuzzy if I apply the transform using TransformMatrix

For example... start with an image rendered at the screen dpi. Do pinch to zoom and translate. Take the new  zoom level and multiply it to determine the new dpi and update the image. (I'm using a Win2D CanvasControl to host the image inside my canvas)

I should note I am using a surface pro 3 with higher than 96 dpi screen

**Comment by Pierce913** [comment]
I've noticed I can make the images sharp if I render them at 2x the size and downsize them. But this is less than Ideal as it requires allot of extra computer power

**Comment by JohnnyWestlake** [comment]
I think this is expected at the moment, Composition transforms literally just stretch whatever rendered texture the XAML engines spits out. to over simplify things. So if you scale up in Composition compared to scaling up in XAML itself or on the Win2D Canvas, it's not going to take advantage of the fact your image is higher resolution. 

Basically if you apply the transform in Win2D, it will render the image at the scaled up size as the transform is applied during / before rendering. If you apply the transform with composition, it will render the image at it's original non transformed size, then stretch it without rerendering, as the transform is applied *after* the original rendering.

Good for performance, not good for your specific use case?

(I could be way off base here but that's what I'm taking out from what your issue sounds like)

**Comment by Pierce913** [comment]
I don't believe that is the problem as the bluing would be much more severe. When I zoom in using the transform. I also insert a higher quality asset by a corresponding amount. (which is scaled down buy a local transform, then up by the main one to make it the correct size). The blur is subtle and not as though the image has just been scaled up. But the "crispness" of the text is noticeably lower than when I did the same on Win2D. I should note that this observation is on a higher dpi screen (216 dpi surface pro 3). When on a desktop screen (117 dpi) It actually appears crisper than the win2D implementation did. This leads me to think it has something to do with the pixel fitting logic (Like UseLayoutRounding)

**Comment by jacobstern** [comment]
Yep, this intuition is probably correct. As @JohnnyWestlake mentioned, XAML is not aware of composition transforms so it won't apply the usual logic like pixel snapping that enables high fidelity text. I would recommend using a [RenderTransform](https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.xaml.uielement.rendertransform) or [Transform3D](https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.xaml.uielement.transform3d.aspx) in this case.

**Comment by JasterAtMicrosoft** [comment]
Yep, this intuition is probably correct. As @JohnnyWestlake mentioned, XAML is not aware of composition transforms so it won't apply the usual logic like pixel snapping that enables high fidelity text. I would recommend using a [RenderTransform](https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.xaml.uielement.rendertransform) or [Transform3D](https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.xaml.uielement.transform3d.aspx) in this case.

**Comment by JasterAtMicrosoft** [comment]
@Pierce913, to make sure we're on the same page and able to address your problem, would it be possible for you to attach a small project that demonstrates the issue you're running into?

Thanks,
Jake

**Comment by Pierce913** [comment]
@JasterAtMicrosoft  Here you are. In this example I found that the issue is not just with my complicated image scenario. If I simply take a textblock and translate it with the TransformMatrix it becomes blury. The example shows the issue.

[BluryTransforms.zip](https://github.com/Microsoft/WindowsUIDevLabs/files/623224/BluryTransforms.zip)

**Comment by JasterAtMicrosoft** [comment]
Sorry for the delay. As I mentioned earlier this is an expected artifact for text when using Composition transforms. As a workaround I would use [RenderTransform](https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.xaml.uielement.rendertransform) or [Transform3D](https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.xaml.uielement.transform3d.aspx).

**Comment by likuba** [comment]
Hi @Pierce913 
We're continually working to improve the interoperability between XAML and Composition, but did this workaround solve your issue for now?

Thanks!

**Comment by Pierce913** [comment]
Hi @likuba 

Unfortunately the RenderTransform suffered similar clarity issues when I had several matrix transforms multiplied together to create a resultant 2D transform with fractional translations.

The way I solved the issue was to apply a final 'adjustment' matrix to all my transforms to make sure the resultant matrix's translation aligns with an integer number of logical display pixels.

This results in crystal clear rendering.

Cheers!

**Comment by likuba** [comment]
Awesome--thanks for sharing your workaround to this issue!  I'm going to go ahead and close this one out, but feel free to reactivate or open a new one if you have additional problems.
