### ISSUE TITLE
Pixelated transformed rectangle when offscreen

### ISSUE THREAD

**Issue by Pierce913** [Microsoft/WindowsUIDevLabs#180]
I have noticed that rectangles transformed with the TransformMatrix property loose there anti-aliasing when they extend out of screen bounds.

To reproduce:
1. Take a XAML Rectangle. make its size width = 1; height = 100;
2. Apply a composition transform to  make the line longer to say 1000 using TransformMatrix Property. (scaleX = 1; scaleY = 10)
3. Apply a 60 degree rotation to the rectangle's TransformMatrix property.

4. Put the Rectangle inside a Canvas and have the TransformMatrix property set on that to follow your finger.

5. Notice that when the rectangle (should look like a 1px line) is within the screen bounds it is smooth and anti-aliased. And notice when you extend a portion of it to outside the screen bounds it becomes jagged

**Comment by dani5447** [comment]
Hi @Pierce913  thanks for bringing this to our attention. Could you attach a small sample project demonstrating the exact issue, just to be sure we're aligned on the problem we're looking at?

**Comment by daneuber** [comment]
Hi @Pierce913  thanks for bringing this to our attention. Could you attach a small sample project demonstrating the exact issue, just to be sure we're aligned on the problem we're looking at?

**Comment by Pierce913** [comment]
Here you go. Resize the right side of the window in until it covers the tip of the line. You will see that end of the line goes from smooth to pixelated.

[Antialiasing bug.zip](https://github.com/Microsoft/WindowsUIDevLabs/files/623178/Antialiasing.bug.zip)

**Comment by daneuber** [comment]
Thanks! We're having trouble repro-ing it still. Can you run 'winver' and provide your build number?

**Comment by JustinXinLiu** [comment]
Version 1607 (OS Build 14393.447).

I can replicate it too. It might be less obvious on SP4 due to higher res.

**Comment by daneuber** [comment]
Thanks! We were able to repro this on 14393 but we aren't able to replicate this on the latest insider build. We're going to try to narrow down what fixed this bug. Do you have a specific scenario and/or app you were building where you ran into this?

**Comment by JustinXinLiu** [comment]
@daneuber which build are you referring to? I just tested it on _14965_ with the same SDK version and the issue was still there.

**Comment by daneuber** [comment]
You're right, I'm sorry I meant we weren't able to replicate on the latest *internal build*. We're working on testing it on the most recent insider build and we'll keep you updated on that progress! Thanks.

**Comment by daneuber** [comment]
Update: we were able to repo on the insider build 14965 but as I mentioned it's still no repro on internal builds. We'll continue to look at insider builds as they come out and keep trying to repro. Thanks

**Comment by daneuber** [comment]
Update: we just looked at this again on the latest insider slow build, 14986, and it no longer repros. Can you attempt to repro again?

**Comment by JustinXinLiu** [comment]
I just did a test in _15007_ with SDK _15003_ and couldn't replicate it anymore. Please feel free to close this issue now.

**Comment by daneuber** [comment]
@Pierce913 closing this for now, let us know if you run into this again
