### ISSUE TITLE
Need a DirectManipulationCompleting event for ScrollViewer

### ISSUE THREAD

**Issue by JustinXinLiu** [Microsoft/WindowsUIDevLabs#181]
The `DirectManipulationCompleted` event of the `ScrollViewer` fires too late - it only gets called when the animation of the scrolling finishes.

What would be really helpful is to provide an event (maybe something like `DirectManipulationCompleting`) that would fire as soon as the pointer is released (e.g. finger lifts up from screen).

I had to create hacks for this missing feature. Ugly timers were used in my _pull-to-refresh_ sample [here](https://github.com/JustinXinLiu/PullToRefreshUWP_WindowsComposition/blob/master/PullToRefreshXaml/MainPage.xaml.cs#L129) as well as in my `Tab` control [here](https://github.com/JustinXinLiu/Continuity/blob/master/Continuity/Controls/Tab/Tab.cs#L361). I understand that in order to achieve the best performance, the `ScrollViewer` control uses direct manipulation that swallows normal pointer events. But by providing one extra direct manipulation event it would make many scrolling-based animations possible/easier.

**Comment by decademoon** [comment]
Something like this would be a godsend. It's great that the ScrollViewers in XAML are butter-smooth, but they take complete control over the pointer events, making any kind of custom interactions impossible without horrible, horrible hacks. The ScrollViewer has to be the most mysterious control in how it works, most of which is undocumented.

Exposing the ScrollViewer property set was one unexpected bonus at the time, props to the XAML+Composition teams for doing that 👏

**Comment by daneuber** [comment]
Thanks for the feedback. Please feel free to file a feature request in the backlog [here](https://developer.microsoft.com/en-us/windows/platform/features) so we can prioritize this among our other backlog items.

**Comment by JustinXinLiu** [comment]
I wish this could be the place for us to post Composition-specific feature requests though.

Anyway, here is the [link](https://wpdev.uservoice.com/forums/110705-universal-windows-platform/suggestions/20445508-need-a-directmanipulationcompleting-event-for-scro).

**Comment by daneuber** [comment]
Please definitely continue to post Composition feature requests here (we do actively monitor and look at all issues posted here on GitHub). It is helpful to have an additional posting discoverable on UserVoice for people to vote on who are not actively watching our GitHub.
