### ISSUE TITLE
How to grid size increases with screen size?

### ISSUE THREAD

**Issue by iamstudentVN** [Microsoft/WindowsUIDevLabs#183]
How to grid size increases with screen size?
![grid](https://cloud.githubusercontent.com/assets/12800744/20779500/723660a0-b7a7-11e6-98af-58740e6bc6b6.jpg)

**Comment by JasterAtMicrosoft** [comment]
Hi @iamstudentVN,

You're looking for something like this:

```xml
<Grid>
    <Grid.RowDefinitions>
        <RowDefinition Height="*" />
        <RowDefinition Height="*" />
    </Grid.RowDefinitions>
    <Grid.ColumnDefinitions>
        <ColumnDefinition Height="*" />
        <ColumnDefinition Height="*" />
        <ColumnDefinition Height="*" />
    </Grid.ColumnDefinitions>
    <!-- Content goes here... -->
</Grid>
```

I'd recommend starting with [this documentation page](https://msdn.microsoft.com/en-us/windows/uwp/layout/layouts-with-xaml) for an overview of layouts in XAML.
