### ISSUE TITLE
Strange binding behavior

### ISSUE THREAD

**Issue by h82258652** [Microsoft/WindowsUIDevLabs#185]
This problem is hard to description.
I create a demo here: https://github.com/h82258652/UWPStrangeBindingBehavior

When the Pivot x:Name is "Pivot", the Binding not work. But I modify to "Pivot1", it works.
PS: x:Bind has no problem, only Binding has this problem.

**Comment by JasterAtMicrosoft** [comment]
Thanks very much for letting us know about the bug! We're now tracking it internally. As I workaround I would definitely recommend using x:Bind, which is also preferable for performance reasons.

Thanks,
Jake

**Comment by h82258652** [comment]
@JasterAtMicrosoft 
Thanks for response. x:Bind can get better performance, but sometimes still need Binding, like CommandParameter. And the main reason is I'm also working on WPF, I code the control's xaml can run on WPF and UWP platform(As similar as possible). Hope one day they can bring x:Bind to other xaml platform.

**Comment by msftdavid** [comment]
Closing as an internal bug has been filed to track the issue.
