### ISSUE TITLE
Everything about offset only apply in the the first item of the ListView's CCC event

### ISSUE THREAD

**Issue by chungweileong94** [Microsoft/WindowsUIDevLabs#190]
In the ListView's CCC Event, I discovered that every offset settings only apply to the first item. And I found the issue request #78  have the same problem, but I still don't know what is the problem.

**Here's my CCC event code:**

        `private void CharacterListView_ContainerContentChanging(ListViewBase sender, ContainerContentChangingEventArgs args)
        {
            if (!args.InRecycleQueue)
                args.ItemContainer.Loaded += ItemContainer_Loaded;

            args.Handled = true;
        }

        private void ItemContainer_Loaded(object sender, RoutedEventArgs e)
        {
            var itemContainer = sender as ListViewItem;
            var itemsPanel = CharacterListView.ItemsPanelRoot as ItemsStackPanel;
            var itemIndex = CharacterListView.IndexFromContainer(itemContainer);
            var grid = itemContainer.ContentTemplateRoot as Grid;

            if (itemIndex >= itemsPanel.FirstVisibleIndex && itemIndex <= itemsPanel.LastVisibleIndex)
            {
                if (_compositor == null) _compositor = ElementCompositionPreview.GetElementVisual(this).Compositor;

                var visual = ElementCompositionPreview.GetElementVisual(itemContainer);

                float width = (float)grid.RenderSize.Width;
                float height = (float)grid.RenderSize.Height;

                visual.Size = new Vector2(width, height);
                visual.CenterPoint = new Vector3(width / 2, height / 2, 0);
                visual.Scale = new Vector3(1, 1, 1);
                visual.Opacity = 0;
                visual.Offset = new Vector3(0, 100, 0);

                var fadeAnimation = _compositor.CreateScalarKeyFrameAnimation();
                fadeAnimation.InsertKeyFrame(1f, 1f);
                fadeAnimation.Duration = TimeSpan.FromMilliseconds(500);
                fadeAnimation.DelayTime = TimeSpan.FromMilliseconds(100 * itemIndex);

                var offsetAnimation = _compositor.CreateScalarKeyFrameAnimation();
                offsetAnimation.InsertExpressionKeyFrame(1f, "0");
                offsetAnimation.Duration = TimeSpan.FromMilliseconds(1200);
                offsetAnimation.DelayTime = TimeSpan.FromMilliseconds(100 * itemIndex);

                var scaleAnimation = _compositor.CreateVector3KeyFrameAnimation();
                scaleAnimation.InsertKeyFrame(0, new Vector3(1f, 1f, 0));
                scaleAnimation.InsertKeyFrame(.1f, new Vector3(.05f, .05f, .05f));
                scaleAnimation.InsertKeyFrame(1f, new Vector3(1f, 1f, 0));
                scaleAnimation.Duration = TimeSpan.FromMilliseconds(1250);
                scaleAnimation.DelayTime = TimeSpan.FromMilliseconds(100 * itemIndex);

                visual.StartAnimation("Offset.Y", offsetAnimation);
                visual.StartAnimation("Scale", scaleAnimation);
                visual.StartAnimation("Opacity", fadeAnimation);
            }

            itemContainer.Loaded -= ItemContainer_Loaded;
        }`

If you try to comment out the offset animation, you can see that only the first item is making the offset change. 

Please help :(

**Comment by shandilvarun** [comment]
@chungweileong94 can you please provide a brief description on what you are trying to achieve? You might be seeing XAML-Composition interop issue. Documented here https://github.com/Microsoft/WindowsUIDevLabs/wiki/XAML-Composition-Interop-Behavior-Changes

**Comment by chungweileong94** [comment]
@shandilvarun I think it is the XAML-Composition interop issue, it works on 10586, but not 14393....I manage to solve the issue by wrap the element that I wanted to animate into an canvas. Is it any other possible solution for this, because it's like creating another unnecessary element, which not that good in terms of performance.

**Comment by JohnnyWestlake** [comment]
For what it's worth, the next prerelease SDK handles this better by allowing you to use "RelativeOffset" instead of Offset, which behaves more like "Offset" did in 10586, but that won't be a viable target for a while.

**Comment by chungweileong94** [comment]
@JohnnyWestlake Good to hear that, I think my solution is fine for me as for now.
