### ISSUE TITLE
gif image disappeared after navigation back

### ISSUE THREAD

**Issue by h82258652** [Microsoft/WindowsUIDevLabs#191]
I create a demo here:
https://github.com/h82258652/GifBugDemo/tree/master/GifBugDemo/GifBugDemo.Uwp.14393.Simplest

The first page's `NavigationCacheMode` is `Required`.
Navigate to other page and go back after a while(I set 5 seconds in this demo), the gif disappeared.

OS: Win10 x64 14393.693
SDK version: 14393

**Comment by h82258652** [comment]
![dogegif](https://cloud.githubusercontent.com/assets/5144550/22063952/598d75c6-ddbc-11e6-8239-4e3e12b3add3.gif)
upload demo gif.

**Comment by JustinXinLiu** [comment]
I had a similar problem before but when I tested your code with _15003_ it
was showing up fine.

**Comment by JasterAtMicrosoft** [comment]
I wasn't able to reproduce this on a recent internal build either. Please reopen this issue if you still have this problem on Insider builds 15003 or higher.

Thanks,
Jacob
