### ISSUE TITLE
What happens to Size/RenderSize and Offset/Margin syncing?

### ISSUE THREAD

**Issue by JustinXinLiu** [Microsoft/WindowsUIDevLabs#192]
When I was playing with SDK _14965_ and its corresponding build I was quite certain that the composition property `Size` is in sync with the `RenderSize` of a `UIElement` and the same goes to `Offset` and `Margin`.

But in SDK _15003_ and build _15014_ `Size` are `Offset` are all back to `VectorX.Zero` again.

Are we going to have xaml/composition property syncing in the future? What's the plan here?

**Comment by sernaj** [comment]
Sorry abut the delay in getting to this. For the question on the future plans, reconciling visual properties and UIElement properties are major priority for the team. This will likely take a few releases as we work on this and we will be pulling in our insiders to help vette plans and test code. As far as perceived property syncing in 14965 versus 15003 and 15003 is concerned - what behavior did you see in 14965 that made it look like there was syncing happening?

**Comment by JustinXinLiu** [comment]
@sernaj for example, in _14965_ the `Size.X` is equal to `UIElement.ActualWidth` and `Size.Y` to `UIElement.ActualHeight`.

**Comment by sernaj** [comment]
@JustinXinLiu  Okay, you should be seeing consistent  behavior between all three builds, as we did push the size down starting with the 14393 release and XAML framework layout starting sharing Offset for implicit animation triggers (creating the Offset stomping issue) and we haven't changed that in Creators update. Seeing size at 0 is 10240 behavior and a regression. I haven't seen this, and only way you could get that behavior on build 14393 is by targeting the older SDK in the VS project.  but, I'll definitely check into this. Back to your broader question, yes, we plan to keep moving in the direction of sharing and syncing.

**Comment by sernaj** [comment]
Closing as this should have now stabilized in the builds.
