### ISSUE TITLE
Path animations, now with a shiny use-case

### ISSUE THREAD

**Issue by tomzorz** [Microsoft/WindowsUIDevLabs#193]
So it's been a year since #12 and I've just seen Lottie https://medium.com/airbnb-engineering/introducing-lottie-4ff4a0afac0e#.pjumsiodw where I've discovered https://github.com/bodymovin/bodymovin that can export after effects animations into a json that you can understand :) (and play it via html but I don't care about that part...)

I know I talked about this (ie. AE -> composition) with more than one person online and during the mvp summit but I wanted to follow up that this seems closer than ever if there's any progress on path animations :)

**Comment by sohchatt** [comment]
Path animations have been requested, and this is a gap in the WindowsUI platform that remains to be addressed. Thanks for bringing Lottie to our attention; we'll certainly continue to enable the scenarios that will help you build beautiful and delightful experiences. Your feedback is extremely valuable and we'll be in touch the moment we have any news to share on this front!

Out of curiosity: do you use AfterEffects for motion design when building your applications? Since you mentioned Lottie, I'm trying to get an understanding of your expected workflow (and your tooling preferences) wrt path animations (for UWP or other platforms).

**Comment by JustinXinLiu** [comment]
For me, I wish I could use _Blend_ to build **path morphing** animations like in AE.

Currently I can still use `PointAnimation` to do simple path morphing (although the performance isn't great as it's running on the UI thread) but it takes a lot of time and also not easy to write.

Though I do believe by the time we have Composition-based path animation support, the performance should be butter smooth, I doubt it would be much easier to write.

So to me tooling is definitely important. I am not entirely sold with Lottie as it's using JSON (unless I am wrong), I'd rather have auto-generated native code, just like how _Blend_ does currently.

**Comment by juanpaexpedite** [comment]
If I had time I would take a look using Win2D, I think the performance would be great and you are always updating and drawing, might be even better using the Win2D, Animated Canvas. Hope find time to make some tests. The ideal would be changing values of a SVG? is there animations in SVG? well XAML and SVG are practically the same. I like Inkscape might be has some plugin about animation.

**Comment by tomzorz** [comment]
@JustinXinLiu Lottie only uses .json because Bodymovin exports the AE animations as such. I'd be fine with using Blend or whatever to pull it off. Even implicit path animations could be interesting... for a recently common example.: 

- 6 points + a thickness defines 3 lines for a hamburger menu icon
- first state: 6 points in 3 lines
- second state: 6 points in an X shape (2 of these "hiding")

**Comment by tomzorz** [comment]
@juanpaexpedite agreed :) As you say - if I can animate svg files using css I should be able to do the same natively.

**Comment by tomzorz** [comment]
BTW the first animation-sharing site is already up for Lottie: http://www.lottiefiles.com/ 

It'd be a shame if we'd miss the fun :(

**Comment by juanpaexpedite** [comment]
It is clear, until we have:

private final List<PathKeyframe> keyframes = new ArrayList<>();
and a generic way like <Keyframe<PointF>> 

The sad part it is making this library is really fast with this core things we need! 

Hope now are touching SVG might be touch a bit the XAML core of shapes including the paths to animate them...

**Comment by juanpaexpedite** [comment]
In case you want to use the webview 'workaround' here you are: https://mareinsula.wordpress.com/2017/02/21/wrap-lottie-in-uwp-apps/  repo and details inside

**Comment by daneuber** [comment]
We're tracking path animations as part of the general shape support under the request [here](https://developer.microsoft.com/en-us/windows/platform/features/animatedvectorgraphicssupportinthevisuallayer/?q=vector%20graphics). Closing this issue, please feel free to upvote on the public backlog.

**Comment by azchohfi** [comment]
For now you can just use LottieUWP (https://github.com/azchohfi/LottieUWP/).

**Comment by sohchatt** [comment]
This long wait is finally over: https://aka.ms/lottie
