### ISSUE TITLE
Navigation Flow example broken

### ISSUE THREAD

**Issue by ratishphilip** [Microsoft/WindowsUIDevLabs#194]
In the Navigation Flow example, if I scroll to say item 128 and click on it, the connected animation happens.

But when I click on the Back button, the return animation does not happen. The Tile 128 just stays in its position before fading out.

**Comment by JustinXinLiu** [comment]
I think the reason that the back animation doesn't work is because the first page isn't cached, so when you navigate back, because of the `GridView`'s default virtualization, that item hasn't been realized yet so the connected animation couldn't find anything to animate.

One quick workaround is add `Task.Yield();` after `ItemsGridView.ScrollIntoView(item);`, just to give it a little bit time to render. 

Also another flaw I've found is that, 'cause the app only remembers the selected item index, the position of the scrollbar isn't always the same (due to the use of `ScrollIntoView` which always leads to the item's default position) after coming back. Ideally you want to use `ChangeView` (i.e. a method that belongs to `GridView`'s inner `ScrollViewer`) instead. I am posting the updated code here in case someone's interested.

```
//*********************************************************
//
// Copyright (c) Microsoft. All rights reserved.
// This code is licensed under the MIT License (MIT).
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, 
// INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
// IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, 
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, 
// TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH 
// THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//
//*********************************************************

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Windows.UI.Composition;
using Windows.UI.Xaml;
using Windows.UI.Xaml.Controls;
using Windows.UI.Xaml.Hosting;
using Windows.UI.Xaml.Media;
using Windows.UI.Xaml.Media.Animation;
using Windows.UI.Xaml.Navigation;

namespace CompositionSampleGallery
{
    public static class Extensions
    {
        public static ScrollViewer GetScrollViewer(this DependencyObject element)
        {
            var sv = element as ScrollViewer;

            if (sv != null)
            {
                return sv;
            }

            for (var i = 0; i < VisualTreeHelper.GetChildrenCount(element); i++)
            {
                var child = VisualTreeHelper.GetChild(element, i);

                var result = GetScrollViewer(child);
                if (result == null)
                {
                    continue;
                }

                return result;
            }

            return null;
        }
    }

    public sealed partial class NavigationFlowSourcePage : Page
    {
        private Compositor _compositor;
        private static int s_persistedItemIndex;
        private static double s_persistedVerticalOffset;
        private ScrollViewer _itemsGridViewScrollViewer;

        private ScrollViewer ItemsGridViewScrollViewer =>
            _itemsGridViewScrollViewer ?? (_itemsGridViewScrollViewer = ItemsGridView?.GetScrollViewer());

        public NavigationFlowSourcePage()
        {
            InitializeComponent();


            _compositor = ElementCompositionPreview.GetElementVisual(this).Compositor;

            var listItems = new List<string>();
            for (int i = 0; i < 300; i++)
            {
                listItems.Add($"Item {i}");
            }
            ItemsGridView.ItemsSource = listItems;

            // Set a fade in animation when this page enters the scene
            var fadeInAnimation = _compositor.CreateScalarKeyFrameAnimation();
            fadeInAnimation.Target = "Opacity";
            fadeInAnimation.Duration = TimeSpan.FromSeconds(0.3);
            fadeInAnimation.InsertKeyFrame(0, 0);
            fadeInAnimation.InsertKeyFrame(1, 1);

            // Call GetElementVisual() to work around a bug in Insider Build 15025
            ElementCompositionPreview.GetElementVisual(this);
            ElementCompositionPreview.SetImplicitShowAnimation(this, fadeInAnimation);

            // Set a fade out animation when this page exits the scene
            var fadeOutAnimation = _compositor.CreateScalarKeyFrameAnimation();
            fadeOutAnimation.Target = "Opacity";
            fadeOutAnimation.Duration = TimeSpan.FromSeconds(0.3);
            fadeOutAnimation.InsertKeyFrame(0, 1);
            fadeOutAnimation.InsertKeyFrame(1, 0);

            ElementCompositionPreview.SetImplicitHideAnimation(this, fadeOutAnimation);
        }

        protected override void OnNavigatedTo(NavigationEventArgs e)
        {
            base.OnNavigatedTo(e);
            if (e.NavigationMode == NavigationMode.Back)
            {
                ItemsGridView.Loaded += async (o_, e_) =>
                {
                    var connectedAnimation = ConnectedAnimationService
                        .GetForCurrentView()
                        .GetAnimation("BorderDest");
                    if (connectedAnimation != null)
                    {
                        var item = ItemsGridView.Items[s_persistedItemIndex];

                        ItemsGridView.ScrollIntoView(item);
                        ItemsGridViewScrollViewer.ChangeView(null, s_persistedVerticalOffset, null, true);
                        await Task.Yield();

                        await ItemsGridView.TryStartConnectedAnimationAsync(
                            connectedAnimation,
                            item,
                            "BorderSource"
                        );
                    }
                };
            }
        }

        private void ItemsGridView_ItemClick(object sender, ItemClickEventArgs e)
        {
            ConnectedAnimationService.GetForCurrentView().DefaultDuration = TimeSpan.FromSeconds(0.5);

            s_persistedItemIndex = ItemsGridView.Items.IndexOf(e.ClickedItem);
            s_persistedVerticalOffset = ItemsGridViewScrollViewer.VerticalOffset;
            ItemsGridView.PrepareConnectedAnimation("BorderSource", e.ClickedItem, "BorderSource");

            Frame.Navigate(typeof(NavigationFlowDestinationPage), s_persistedItemIndex);
        }
    }
}
```

**Comment by JohnnyWestlake** [comment]
`Task.Yield()` certainly isn't guaranteed to work, especially on low powered devices. `ListViewPersistenceHelper` is the "proper" class for restoring virtualized ListView / GridView position on changes, and it even works if the ListViewBase or its items have changed size in the meantime which the others don't. But it takes plumbing to get it to work.

For this demo it'd be better off just putting `NavigationCacheMode = NavigationCacheMode.Enabled` in the page constructor and keeping it simple

**Comment by JustinXinLiu** [comment]
@JohnnyWestlake haha you got me there. Initially I was using a `TaskCompletionSource` to wrap the `ChangeView` but sometimes it led to some funny animations so I took it out.

I wasn't aware of the `ListViewPersistenceHelper` class but looks like this is the right way to go. But I do think the sample should work on `Disabled` mode though, so we are sure that the connected animation works in all scenarios.

Anyway, thanks for pointing it out! I am going to try it out now. :)

**Comment by JustinXinLiu** [comment]
So I have tried `ListViewPersistenceHelper` and it works really well - except the back animation is still broken. It's exactly the same issue as when I tried to use TCS to wait for the item to be fully rendered.

Again, by adding a `Task.Delay(1)` the animation works again on my Surface. But like Johnny mentioned this is not guaranteed and ideally this should be addressed by the `ConnectedAnimationService`. 

Please feel free to check out my fork [here](https://github.com/JustinXinLiu/WindowsUIDevLabs/commits/master).

**Comment by JohnnyWestlake** [comment]
For now you'll be far more likely for it to work if you hook onto the ContainerContentChanging event and Yield (or better Dispatch at normal / low priority) from there when the target item actually is about to get set to a container, but for sure surely the Framework should just be doing this for us instead of us users hacking around it.

**Comment by JasterAtMicrosoft** [comment]
Hi folks, thanks for checking out the new samples! We are aware of this problem and should have a fix in upcoming Windows builds. In the meantime Justin's workaround is fine.

**Comment by JasterAtMicrosoft** [comment]
The fix for this issue is available in recent Creator's Update builds. The sample should run just fine now!
