### ISSUE TITLE
The latest build is broken

### ISSUE THREAD

**Issue by jatinam** [Microsoft/WindowsUIDevLabs#195]
Getting compile error for the below line "MainFrame.Content is SampleHost host"
Syntax error. 
In SampleGallery/MainPage.xaml.cs, line 81       
if (MainFrame.Content is SampleHost host)
           {
                SamplePage page = (SamplePage)host.ContentFrame.Content;
                page.OnCapabiliesChanged(_areEffectsSupported, _areEffectsFast);
            }

After I tried fixing the error by modifying the code as shown below, I get a Build error.
if (MainFrame.Content is SampleHost)
            {
                var host = (SampleHost) MainFrame.Content;
                SamplePage page = (SamplePage)host.Content;
                page.OnCapabiliesChanged(_areEffectsSupported, _areEffectsFast);
            }

Build error: using VS 2015 Professional with Update 3
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AppxPackage\Microsoft.AppXPackage.Targets(811,5): error APPX3215: File 'C:\Program Files (x86)\Windows Kits\10\DesignTime\CommonConfiguration\Neutral\UAP\10.0.15021.0\UAP.props' is not a valid MSBuild property file. See http://go.microsoft.com/fwlink/?LinkID=798187 for more information.

**Comment by JohnnyWestlake** [comment]
Q: Are you using VS 2017? This seems to be using C# 7 pattern matching, so you'll have to use 2017 to build direct from source.

(You'll also have to have the very latest SDK installed that can target 15021)

**Comment by jatinam** [comment]
Thanks. Using VS 2017 RC I am able to build and run the samples properly. I have SDK 15021 installed. It's just that the instructions said to use VS 2015, so I had tried with that earlier. It builds and runs fine with VS 2017 RC.
