### ISSUE TITLE
Pan ScrollViewer with the mouse by click and drag

### ISSUE THREAD

**Issue by megamingus** [Microsoft/WindowsUIDevLabs#196]
I think it would be very useful to be able to pan the ScrollViewer with the mouse just like the Maps app does.

I made a simple "hack"  calling ChangeView on PointerMove, but it doesn't feel natural

**Comment by daneuber** [comment]
Thanks for the feedback. Please feel free to file a feature request in the backlog [here ](https://developer.microsoft.com/en-us/windows/platform/features) so we can prioritize this among our other backlog items.
