### ISSUE TITLE
Gradient Animation

### ISSUE THREAD

**Issue by lukeja** [Microsoft/WindowsUIDevLabs#197]
In composition can I animate the Color values of two GradientStops inside a LinearGradientBrush that is used as the background of a Grid?

**Comment by msftdavid** [comment]
Unfortunately, Composition can only animate properties of Composition visuals. GradientStops inside a LinearGradientBrush are not supported.

**Comment by tomzorz** [comment]
@lukeja as a workaround you could use Win2d to pull that off. Or maybe use colored lights / shadows / hue rotation effects to achieve a similar effect.

**Comment by JasterAtMicrosoft** [comment]
You can also accomplish this using a Storyboard with EnableDependentAnimation="True". The animation will run on the UI thread, but it's easy to set up and will have similar performance to something you could put together with Win2D.

XAML
```xaml
<Rectangle Width="300" Height="200">
    <Rectangle.Resources>
        <Storyboard x:Name="AnimateGradientStoryboard">
            <ColorAnimation
            To="CadetBlue"
            Duration="0:0:2"
            EnableDependentAnimation="True"
            Storyboard.TargetName="GradientStop1"
            Storyboard.TargetProperty="Color" />
        </Storyboard>
    </Rectangle.Resources>
    <Rectangle.Fill>
        <LinearGradientBrush>
            <GradientStop x:Name="GradientStop1" Color="CornflowerBlue" />
            <GradientStop Offset="1" Color="OrangeRed" />
        </LinearGradientBrush>
    </Rectangle.Fill>
</Rectangle>
```

C#
```c#
AnimateGradientStoryboard.Begin();
```

**Comment by msftdavid** [comment]
Closing now. Please let us know if these solutions do not work for you.

**Comment by juanpaexpedite** [comment]
Yes we can make our custom library for controls like if this were Monogame world and forget XAML. I do not understand why the solution is always workarounds using Win2D, Surfaces and HtmlView. 

So what's the purpose of Composition then. Why Win2D is so open an Composition so locked, will be in the future all solved or what is the roadmap. 

I think questions like shown are pretty basic and telling answers like EnableDependentAnimation is a bit inconsiderate to our effort to make things right.

Hope you understand our position, I am just serious no rude, we know it takes a great effort to make your work, but it is a really hidden work,
