### ISSUE TITLE
CreateHostBackdropBrush fully transparent window

### ISSUE THREAD

**Issue by quincycs** [Microsoft/WindowsUIDevLabs#202]
Hi

Is it possible to configure CreateHostBackdropBrush so that the brush is fully transparent?  Like a hole is cut out for example?

**Comment by sohchatt** [comment]
A HostBackdropBrush paints a SpriteVisual (or UIElement) with blurred pixels from the region of the desktop behind that SpriteVisual. It is a kind of BackdropBrush, with a few differences: 

1. HBB pixels are sourced from behind the application in which they are painted 
2. HBB content is blurred for security reasons
3. HBB pixels turn transparent when the app is out of focus

So, if I understand your use-case correctly, you can make it appear as if a hole were cut out with (by filling an Ellipse with a HBB) but the desktop (backdrop) pixels that fill your ellipse will be blurred.

**Comment by quincycs** [comment]
Yeah the use case is fully transparent, no blur.  Didn't realize it could be a security issue. 

It's for an IoT solution where we'd have another app in the background displaying Ads (these Ads would show thru the transparent piece.  And in the foreground the consumer experience would be shown.

**Comment by sohchatt** [comment]
HostBackdropBrush doesn't seem to apply to your scenario. Why can't you display your ad inside the app (as opposed to behind it)?

**Comment by quincycs** [comment]
The Ad program is a proprietary software that is already being used like I suggest with WPF apps.  This is a continued missing piece for UWP. 

If HostBackDrop gave an option to let it be fully transparent - but that option would be a restricted API for the MSFT general public store then it would be applicable to my scenario.

**Comment by quincycs** [comment]
The scenario is a UWP app running on a vending machine.  It's not a consumer app that would be downloadable from consumers.

**Comment by nerddawg** [comment]
Quincy, we have that scenario on our backlog - it is one of the remaining gaps in the UWP SDK relative to what you can do in Win32 with windowing. Although this feature does not deliver that scenario, it gets us going in that direction with the platform and shell work already done. We may possibly support that in future, backed by a restricted capability, and will certainly run specifics by you to ensure it covers what you are looking for.

**Comment by quincycs** [comment]
Thank you!

**Comment by ratishphilip** [comment]
Is it possible to create a custom shaped window (say an ellipse) and apply HBB to only that area?

**Comment by tomzorz** [comment]
@nerddawg For me it'd be also important to do this, along with support for click-through. This would allow us to pull of widget-like entities on desktop (or even on mobile if possible, think facebook chat-heads)

**Comment by sohchatt** [comment]
@ratishphilip any more details about what this custom shaped window is supposed to do: do you want elliptic windows or some way of puncturing an elliptic cutout from a window)?

If it is the latter: since HBB is a CompositionBackdropBrush, you can paint a XAML Ellipse with it. However, I'm not sure if this answers your question.

**Comment by ratishphilip** [comment]
@sohchatt I was referring to elliptical windows. 
Since, normally, the window is rectangular, the area not covered by the ellipse shape should be transparent and should allow the mouse/touch interactions to be received by the windows behind it (if there are any).

**Comment by ratishphilip** [comment]
@sohchatt I want to create something like this
![ellipticwindow](https://cloud.githubusercontent.com/assets/7021835/24058490/7ae1654c-0b08-11e7-8618-c8ecd534d2d7.png)

**Comment by sohchatt** [comment]
Unfortunately, HostBackdropBrush isn't of much help to you in this case (i.e. you'd fill your elliptic window with a HBB for the Blur + Tint, but you would still need an elliptic window to achieve this). Marking this as a feature request for non-rectangular window boundaries.

**Comment by brucek5** [comment]
I too want to make the transition from WPF where I create "touch" based applications for Windows 10. Attached is a screen capture of some of the windows ( a cloud and a notepad) that uses the transparent window option that WPF provides. Will UWP get me there, or is this a step backwards?
![window_example](https://cloud.githubusercontent.com/assets/27459740/25029131/48a2dcb0-206f-11e7-8403-85bbddb9545c.jpg)

**Comment by tomzorz** [comment]
@brucek5 you can't do this at the moment with UWP :(

**Comment by daneuber** [comment]
Thanks all for the feedback! It looks like a few feature requests have been created out of this issue chain, so closing this issue. Please open another issue if there's additional feedback.
