### ISSUE TITLE
Publish the Gallery app to Store?

### ISSUE THREAD

**Issue by xied75** [Microsoft/WindowsUIDevLabs#203]
So that we can easily see what's on offer without building it locally?

**Comment by sernaj** [comment]
This is definitely something we have planned for the Creator's Update release. We currently testing a version of the app internally, so stayed tuned.

**Comment by Odonno** [comment]
I would like to see it too on the Windows Store.

**Comment by sernaj** [comment]
The sample gallery is now in the store. You can find it here: https://aka.ms/winuiapp
