### ISSUE TITLE
SVG source has not anti-aliasing in 16170

### ISSUE THREAD

**Issue by juanpaexpedite** [Microsoft/WindowsUIDevLabs#207]
I am making an app using the latest SDK 15063 and in 16170:

![image](https://cloud.githubusercontent.com/assets/5947026/24849840/7d236538-1dc5-11e7-921e-2572c0809326.png)

That is an screenshot of the Image Control that has an SVG as source, what could be the reason it does not appear with smooth lines?

**Comment by samschiferl** [comment]
Thank you for your feedback. Can you provide more details on the exact scenario where you are using the Image control? Specifically, how is the width and height for the Image control determined?

**Comment by juanpaexpedite** [comment]
For sure, for instance, the source svg source file: 

https://gist.github.com/juanpaexpedite/cd1def2361d5cc23efacd415a7206985

And presented like the following:

       <Grid.ColumnDefinitions>
            <ColumnDefinition Width="0.3*" />
            <ColumnDefinition Width="1*"/>
        </Grid.ColumnDefinitions>

        <Image Source="ms-appx:///Assets/Vectors/Personaexample.svg"/>

While I stretch the window suddenly the antialiasing disappears and behaves similar the previous screenshot. I have also converted the strokes to objects and also the same. Also I have 'resized' the SVG source with the same results.

If I open both in Edge and UWP:

![image](https://cloud.githubusercontent.com/assets/5947026/24970581/b78a677e-1fac-11e7-9189-2257f8e5b9f7.png)

Aside of that would be great that the antialiasing could be controlled, might be in the Composition layer, (I think Win2D cannot manage SVG at the moment). I do not know to make some interesting tools.

It is important to me because I want to save the svg to a RenderTargetBitmap and then to a file.

Thank you, I understand this is a new feature and takes time.

**Comment by samschiferl** [comment]
We have identified the issue in our feature which has caused the jagged lines in your scenario and have created an item in our backlog to address the problem. 

In the meantime, you can workaround the issue by resetting the source using SetSourceAsync or UriSource, wait for the Opened event and then save the svg to a RenderTargetBitmap. The SvgImageSource will re-render the SVG at the target size with smooth lines when the source content is reset.

**Comment by juanpaexpedite** [comment]
Thank you! I've realized out that I can create cool SVG tools using UWP and Composition and Win2D. It's incredible that these days there is a lack of those tools. 

And off-topic: Is that possible that the Compiled Binding Team (I do not know if it is really a team) make their own repository. I do not know how to be updated in their roadmap, I think it needs a lot of upgrades. Thank you.

**Comment by JasterAtMicrosoft** [comment]
Hi @juanpaexpedite, could you send your x:Bind feedback to WindowsUI@microsoft.com?

Closing this issue since there is a workaround and we are tracking the fix internally.

Thanks,
Jake

**Comment by mqudsi** [comment]
@samschiferl Can you please provide a issue link, reference, etc. or otherwise definitively give an update on the status of the aliased SVG rendering issue? Is it resolved as of 17763 or 18362? There's more info about the bug [in this StackOverflow issue](https://stackoverflow.com/a/44936073/17027).
