### ISSUE TITLE
exception happened

### ISSUE THREAD

**Issue by HppZ** [Microsoft/WindowsUIDevLabs#208]
1, Animation_Batches->MainPage.xaml.cs:
![untitled](https://cloud.githubusercontent.com/assets/12285582/25120066/37d052c6-244f-11e7-8409-105e4722a6f0.png)

2, EffectEditor-> MainPage.xaml.cs
![untitled1](https://cloud.githubusercontent.com/assets/12285582/25120105/55bab25e-244f-11e7-9e94-1e3f08f77676.png)

**Comment by JustinXinLiu** [comment]
`GetElementVisual` returns a `Visual`, NOT a `ContainerVisual`.

**Comment by HppZ** [comment]
@JustinXinLiu  seems that they don't run their code.

**Comment by JustinXinLiu** [comment]
Just realized it's from the sample. That was just some old code...

**Comment by HppZ** [comment]
sample code that does not work. ha ha

**Comment by nerddawg** [comment]
It is OSS code - you know the concept right? If you feel like doing more than throwing rocks, send a pull request and get it fixed. Otherwise I am sure there are other bugs across Git projects you can find and laugh at.

**Comment by HppZ** [comment]
yes, you are right. I just can't believe that even official sample code makes mistakes like this. I think it can be better.

**Comment by JustinXinLiu** [comment]
We all make mistakes. But the good thing about OSS code is that you can help fix others mistakes by submitting PRs.

You've done a fantastic job spotting the issue, why stop there?

**Comment by contextfree** [comment]
I just ran into this - the Animation_Batches crash seems to be fixed (and the sample overall seems to then work fine) by just removing the "(ContainerVisual)" cast. 

I'm a little unsure about submitting this change because I don't really understand the context (how did it get this way to begin with? did it work on an older version of the API?) but I made a pull request anyway: #227

**Comment by jeffstall** [comment]
Thanks for finding this! I accepted the pull request. Have a great day. ☺

**Comment by daneuber** [comment]
Closing since pull request was accepted. Thanks for contributing!
