### ISSUE TITLE
ScrollViewer flickering with 15063 SDK

### ISSUE THREAD

**Issue by Sergio0694** [Microsoft/WindowsUIDevLabs#209]
Hello, I've just moved to the new 15063 SDK in my app and I noticed that the new template for the ScrollViewer is causing it to flicker when loading its content and when tapping items on a touch display (inside a ListView).
Here's my question on StackOverflow with the full description of the problem: [**ScrollViewer flickering**](http://stackoverflow.com/questions/43562521/workaround-for-the-scrollviewer-flickering-in-15063-sdk)
And here's a small [YouTube video with the problem](https://youtu.be/8x_0iariYfE), you can see the vertical scrollbar (right edge of the window) flickering every time I navigate to the home page, as soon as the content is loaded.

As I said, this also happens when I tap on a ListView item on a touch display, the vertical scrollbar just pops up for no reason (it was working 100% fine up untile the 14393 SDK).
The `VerticalScrollBarVisibility ` property is set to Auto (as it was before the new SDK).

Please let me know if you need more info on my end and I'd be happy to contribute more.
Thanks in advance for your help!

**Comment by Sergio0694** [comment]
Hello, I have some more info on the issue above (as I've added in the original question on StackOverflow).

I attached a `CustomVisualStateManager ` to the `ScrollViewer` control and found out that, as expected, when that flickering happens the control is jumping from the _NoIndicator_ visual state to the _MouseIndicator_ (or _TouchIndicator_) state and back to the _NoIndicator_ state instantly, that's why the flickering happens. 
This happens every single time I click on an item in a `ListView` control, as well as when the content is loaded inside a `ScrollViewer`.

I was trying to come up with a `VisualStateManager` that uses a timer and a delay to apply the states after a given time threshold in order to be able to skip these "fake" states, but of course it'd be much better if the issue was fixed from within the control itself instead of using such a weird workaround (which is not even guaranteed to work properly).

Thanks for your help!

**Comment by adambarlow** [comment]
Sergio can you tell us what build of Windows you are running? Have you made a custom template for either scrollviewer or scrollbar?

**Comment by Sergio0694** [comment]
Hey Adam, thanks for your help! 
The issue is present when compiling the app with the 15063 SDK (I figure that's because the VisualStates have been changed in this Windows 10 build to add the new context-aware animations), I'm running the official Creators Update build on both my PC and phone and the problem happens on both the devices.
Also, I'm not using any custom template, and I see the same flickering both with a standalone ScrollViewer control, and with the one inside a ListView control.
Hope this helps, let me know if there's any other info you need!

**Comment by Trannosaur** [comment]
Hey Sergio, sorry for the delay in response. Is there any minimal repro you have available?

**Comment by Sergio0694** [comment]
@Trannosaur Hello, I don't have a minimal repro for my app right now as it's a fairly large project and it'd take some work to strip all of the unnecessary code away, but I'm developing another app at the moment and I noticed the same exact issue (targeting build 15063, minimum build 15063 too) within a `ListView` control that loads some content after it's rendered.
Basically as soon as the content loads, I can see the scroll bar flicker for that fraction of a second just like it happens in my app, so I'm assuming it's just an issue with the default style of the ScrollViewer in the 15063 SDK and it doesn't have something to do specifically with my app.

If you'd still like a repro to investigate the issue though I can see if I can manage to recreate the glitch in a small project and send you that one.
Thanks for your help!

**Comment by Trannosaur** [comment]
Hi Sergio! Sorry for the lack of response here - this should be fixed for the Windows 10 Fall Creators Update (SDK version 16299).

**Comment by Sergio0694** [comment]
Hello @Trannosaur - thanks for your reply. I've just updated to FCU and to the new SDK and I've tried to rebuild my app targeting the new W10 version, the issue does see to be fixed now 😄 
Thank you for your help, glad to see that's been solved too!
Cheers, have a nice day!
