### ISSUE TITLE
Composition Stop Animation Read Values

### ISSUE THREAD

**Issue by Pierce913** [Microsoft/WindowsUIDevLabs#210]
When I call StopAnimation on an animation animating the TransformMatrix property and attempt to read back values to find out where the animation is up to it returns incorrect results until about 30ms after stop animation is called. Furthermore if I do not yield the UI thread it seems not to stop at all. What I need is the call to StopAnimation to not return until the animation has actually stopped and the values have been updated, ready to be read back. How can I achieve this with the current API?

**Comment by JohnnyWestlake** [comment]
Have your tried creating a ScopedBatch and using the Completed event on it?

**Comment by Pierce913** [comment]
Yep. The completed event fires on the UI thread which requires me to yield. Therefore I require async between stopping the animation and reading back the value which is what I am trying to avoid.

I.e.
StopAnimation();
await WaitForScopedBatchToCompletedEvent();
ReadBackValue();

...Whereas what I need is...

StopAnimation(); // Synchronously block until animation is stopped
ReadBackValue();

**Comment by scott-moore-ms** [comment]
Short answer - what you want to do is not possible with the API.  As you've noticed, you must yield to the UI thread both for the StopAnimation call to take effect, as well as to be notified of the updated value (and get the scoped batch completion event).
What is the scenario you're trying to build that requires this?  Maybe there's an alternate solution?

**Comment by Pierce913** [comment]
There is an alternate solution but its not elegant. The scenario I am implementing is a pan and zoom canvas. I am using Pointer Pressed, Pointer Moved and Pointer released events. I calculate all the momentum myself and then start a composition transform matrix animation to fling the canvas. I have to wait for any previous animation to stop in the pointer down event and then read back the current transform so I can do my calculations on the current value. This means it has to be async... yielding the UI thread. This results in pointer moved and potentially pointer released events firing before the pointer pressed has completed as it was waiting for the animation completed event to fire. So the solution is to also make the pointer moved and pointer released events async and use an async lock to queue them up ensuring correct execution order.

As most of the functions of the app interact and depend directly on where the current view is looking. I have to make pretty much all other events async and use the same async lock to queue up events in order because of this one small annoyance of StopAnimation() returning before the animation has actually stopped. Storyboards operated correctly and stopped immediately. But they do not have the performance I require. So the end result of the forced async Is forcing async in many other places. This makes the code much more complicated than it needs to be, more prone to bugs, and with reduced performance. The pointer moved which fires many times a second. and having it asynchronously queue up is a noticeable degradation to performance and touch responsiveness.

Before you suggest it. No interaction tracker cannot help me. It is too restrictive and doesn't allow enough control. (for one it has no support for pinch rotate).

**Comment by scott-moore-ms** [comment]
Thanks for the feedback!  Unfortunately, there is no way in our API to block the UI thread until the animation has completed, or receive the events on a background thread.  One suggestion to improve the performance if you're not already doing this is that rather than queuing up every single pointer moved event, use a latch pattern instead, where you only enqueue a move update if you don't already have one in flight, and simply coalesce the moves so that when you get to your deferred processing, you're operating on the most recently seen value.

**Comment by Pierce913** [comment]
OK cool thanks. I'll give the latch pattern a go.
