### ISSUE TITLE
completed event support

### ISSUE THREAD

**Issue by HppZ** [Microsoft/WindowsUIDevLabs#212]
very sorry to bother.
How to get completed event when using ImplicitAnimation?
ScopedBatch can't do that, right? so how to?
much thx!

**Comment by shandilvarun** [comment]
you should add scoped batch where you are updating the properties E.g. 
Open Scope Batch 
--Property Change 
Close Scope batch

**Comment by msftdavid** [comment]
It sounds like this question has been answered. Closing.
