### ISSUE TITLE
x:Bind UriSource BitmapImage not updating when used as Ellipse Fill

### ISSUE THREAD

**Issue by AudioW** [Microsoft/WindowsUIDevLabs#213]
Hi

I have an image which I use in two scenarios: one in a grid and one in an ellipse to make it appear rectangular. I bind the UriSource of my image using x:Bind. However, when updating the image uri, my grid get's updated and my ellipse doesn't. Here is my ellipse code:

                        <Ellipse x:Name="detailellipse" Margin="0,0,0,20" HorizontalAlignment="Center" Width="150" Height="150" VerticalAlignment="Top">
                            <Ellipse.Fill>
                                <ImageBrush>
                                    <ImageBrush.ImageSource>
                                        <BitmapImage UriSource="{x:Bind DetailItem.ImageUri, Mode=OneWay}" />
                                    </ImageBrush.ImageSource>
                                </ImageBrush>
                            </Ellipse.Fill>
                        </Ellipse>

Is this a bug?

**Comment by stmoy** [comment]
Hello AudioW, thank you for bringing this issue to our attention. This was indeed a bug in the platform which we have fixed. The fix should have made it up to the Insider Slow Ring as of early July. 

Since the bug has been fixed, I'm closing this issue.
