### ISSUE TITLE
Unclear support for some Win2D effects with Composition APIs

### ISSUE THREAD

**Issue by Sergio0694** [Microsoft/WindowsUIDevLabs#218]
Hello, I'm working with the Composition APIs and some Win2D effects and I've read the list of the available Win2D effects that are currently supported with the Composition APIs [here](https://docs.microsoft.com/en-us/windows/uwp/composition/composition-effects).

From the list in that page (as well as [this page](https://microsoft.github.io/Win2D/html/N_Microsoft_Graphics_Canvas_Effects.htm)) I can see that the `GaussianBlurEffect` is marked with the `[NoComposition]` attribute, so it shouldn't be supported. Yet I can use this method without any problems (and I'm not sure why):

```csharp
public static SpriteVisual GetAttachedBlur<T>(
    [NotNull] this T element, float blur, int ms) where T : FrameworkElement
{
    // Get the visual and the compositor
    Visual visual = element.GetVisual();
    Compositor compositor = visual.Compositor;

    // Create the blur effect and the effect factory
    GaussianBlurEffect blurEffect = new GaussianBlurEffect
    {
        Name = "Blur",
        BlurAmount = blur,
        BorderMode = EffectBorderMode.Hard,
        Optimization = EffectOptimization.Balanced,
        Source = new CompositionEffectSourceParameter("source")
    };
    CompositionEffectFactory effectFactory = compositor.CreateEffectFactory(blurEffect);

    // Setup the rest of the effect
    CompositionEffectBrush effectBrush = effectFactory.CreateBrush();
    effectBrush.SetSourceParameter("source", compositor.CreateBackdropBrush());

    // Assign the effect to a brush and display it
    SpriteVisual sprite = compositor.CreateSpriteVisual();
    sprite.Brush = effectBrush;
    sprite.Size = new Vector2((float)element.ActualWidth, (float)element.ActualHeight);
    ElementCompositionPreview.SetElementChildVisual(element, sprite);
    return sprite;
}
```

I mean, looking at the documentation, I would expect the code to fail, since the `GaussianBlurEffect` doesn't seem to be supported.
Then, I tried another effect (the `DirectionalBlurEffect`, which is also marked as not supported by the Composition APIs) and that failed (the `CreateEffectFactory` threw an exception.
So my questions are:

-  If both those effects are marked as `[NoComposition]`, why does the `GaussianBlurEffect` actually work with the Composition APIs, and the `DirectionalBlurEffect` doesn't? Is there another way to use those other effects, or is there a plan to support them as well in future Windows 10 releases?

Thanks for your help!

**Comment by sohchatt** [comment]
This is a documentation bug on the Win2D page: GaussianBlurEffect is supported in Composition. 

Thanks for your feedback; we will update the Win2D effect descriptions.

**Comment by Sergio0694** [comment]
@sohchatt Thanks for the quick reply! May I ask if there's hope that other Win2D effects will be supported in the future with the Composition APIs? I'd love to be able to use that `DirectionalBlurEffect` and other effects from the original Win2D list! 😄

**Comment by sohchatt** [comment]
Here's a list of what currently tagged as NoComposition but is supported as of today:

- All BlendEffectModes except Dissolve (Fall Creator's Update Insider)
- BorderEffect (Creator's Update)
- ColorMatrixEffect (Creator's Update)
- DistantDiffuseEffect (Anniversary Update)
- DistatntSpecularEffect (Anniversary Update)
- GaussianBlurEffect (Anniversary Update)
- LuminaceToAlphaEffect (Anniversary Update)
- PointDiffuseEffect (Anniversary Update)
- PointSpecularEffect(Anniversary Update)
- SpotDiffuseEffect (Anniversary Update)
- SpotSpecularEffect (Anniversary Update)

You should see updates to the Win2D documentation over the next few days.

The effects that will be supported in future releases depends on those that you (and others) need. So please feel free to submit feedback (and upvote) about the specific Win2D effects you'd like to see in the Composition APIs.

**Comment by Sergio0694** [comment]
Thanks for your help @sohchatt - happy to see that so many effects are supported already!
Since you said the `BorderEffect` is supported in the Creators Update, I tried to test it as I'd like to use it to replicate the noise effect in the official Acrylic brush (as suggested by @msftdavid  and the WindowsUI team at the Build) on a device running the Creators Update. The thing is that the full Acrylic brush looks so much better than the simple `HostBackdropBrush`, so I'm trying to create something similar on my own until the Fall Creators Update is released.

So, here's the code I came up with (just to test the effect): [**BorderEffect Composition test**](https://gist.github.com/Sergio0694/becbf93a8c287e6297128f0a9445b886#file-bordereffectsample-cs-L35)

The issue is that the `CreateEffectFactory` method throws an `ArgumentException` saying "Unexpected effect input type" (I'm running Windows 10 15063.296 and my app targets the 15063 SDK only).
Can you confirm that the `BorderEffect` is in fact supported by the Composition APIs? And in this case, am I missing something here to get it working?

Thank you again for all your help! 😄

**Comment by sohchatt** [comment]
There are some inaccuracies with the way you define a SourceParameter to your EffectBrush. Have you taken a look at the [Border Playground](https://github.com/Microsoft/WindowsUIDevLabs/tree/master/SampleGallery/Samples/SDK%2015063/BorderPlayground) sample code? 

In particular, the use of CompositionEffectSourceParameter: 

```
            var borderEffect = new BorderEffect
                {
                     ExtendX = (CanvasEdgeBehavior)itemX.Tag,
                     ExtendY = (CanvasEdgeBehavior)itemY.Tag,
                     Source = new CompositionEffectSourceParameter("source")
                };

            var brush = _compositor.CreateEffectFactory(borderEffect).CreateBrush();
            brush.SetSourceParameter("source", _image.Brush);
            _sprite.Brush = brush;
```

I should also point out that Acrylic material is more than just a noise asset tiled on a HostBackdropBrush: you can see a visual representation of the effect graph [here](https://docs.microsoft.com/en-US/windows/uwp/style/acrylic). 

You should have access to Acrylic material in the Insider Preview SDK 16190 that shipped immediately after Build 2017. Are you trying to build your own because you want to target users running Creator's Update builds?

**Comment by Sergio0694** [comment]
Hello @sohchatt - I tried to look at the Windows UI sample app, but the border playground page doesn't seem to be working for me, I only get a [blank page](http://i.imgur.com/7fSAvpP.png) even after playing with the different modes and values.

Anyways, thanks for the tip, I'll study the sample code and see if I can get the `BorderEffect` to work in my application too! I know that the Acrylic brush is available in the Insider Preview SDK, but I wanted to create something similar to use in my app while it still targets the Creators Update, as the Fall Creators Update won't be available for a few more months.

Also, I know the Acrylic is made up of more than the simple background effect, so right now I plan to use:

- `HostBackdropBlur` (which automatically applies a blur effect on its own too)
- An `ArithmeticCompositeEffect` to mix the background blur with a `ColorSourceEffect` (to replicate the tint overlay with a given opacity level)
- Use the `BorderEffect` on top of this to add the noise effect

This should hopefully be close enough to the Acrylic effect, at least it will be better than the simple `HostBackdropBlur`.
I noticed that the Groove/Contacts apps on my PC (build 15063.x) already feature the Acrylic effect (I can see the noise effect too), so I guess that those apps are also manually building the equivalent of the Acrylic brush on their own? I mean, since they're running on my PC with still has the Creators Update.

Thanks again!

**Comment by Sergio0694** [comment]
Hi @sohchatt - just wanted to thank you again and post an update on the issue, I was able to get the `BorderEffect` working and to create an effect that's similar to the Acrylic brush (not 100% there yet, but it's definitely better than before).
Here's a screen! [**OneLocker Acrylic brush**](http://i.imgur.com/Z7orbYZ.jpg)

And as a reference, here's the final code: [**SemiAcrylic effect with Composition and Win2D**](https://gist.github.com/Sergio0694/5219d16bd38b965a4c095b3abf94c465)

Thank you again for your help!
Also, it would be great if you guys could share some more info on the different effects/parameters that are present in the official Acrylic brush, in case other devs wanted to emulate it as well! 😄

**Comment by harrypotter06** [comment]
Hello @Sergio0694,

the Code for Acrylic Brush Crash on Visual Studio 2017 - many Errors, no solution :(

Fehler	CS1503	Argument "1": Konvertierung von "System.Drawing.Size" in "Windows.Foundation.Size" nicht möglich

Fehler	CS0246	Der Typ- oder Namespacename "Rect" wurde nicht gefunden  (We found no using, that needed)

Fehler	CS0246	Der Typ- oder Namespacename "CanvasCreateResourcesEventArgs" wurde nicht gefunden

Fehler	CS0123	Keine Überladung für "Canvas_CreateResources" stimmt mit dem Delegaten "TypedEventHandler<CanvasControl, CanvasCreateResourcesEventArgs>" überein.
