### ISSUE TITLE
CreateHostBackdropBrush in Win32

### ISSUE THREAD

**Issue by melak47** [Microsoft/WindowsUIDevLabs#219]
Will `CreateHostBackdropBrush` or an equivalent be available to Win32 apps for use with DirectComposition or D2D at some point?

This is probably off-topic here, but I'm not sure where else to ask.

**Comment by msftdavid** [comment]
We recommend filing these feature suggestions on User Voice or up-voting/commenting on existing suggestions. Your ask seems similar to [this one]( https://wpdev.uservoice.com/forums/110705-universal-windows-platform/suggestions/19218982-modern-windows-ui-in-win32-desktop-applications).

We do not have any immediate plans to add HostBackdropBrush to the DirectComposition API set. However, the general feature of supporting the effect achieved by HostBackdropBrush for Win32 apps is on our backlog for investigation.

**Comment by Extrimis** [comment]
Actually, There is a way to create HostBackdrop using direct composition, checkout my repo : [Win32 Acrylic Effect](https://github.com/Extrimis/Win32-Acrylic-Effect)

This method uses DWM Private API's and not stable, this is just a demonstration to show it is possible.

**Comment by melak47** [comment]
> 
> 
> Actually, There is a way to create HostBackdrop using direct composition, checkout my repo : [Win32 Acrylic Effect](https://github.com/Extrimis/Win32-Acrylic-Effect)
> 
> This method uses DWM Private API's and not stable, this is just a demonstration to show it is possible.

The Windows.UI.Composition method can now (well, in the insider preview WinSDK) actually be used "directly" with Win32 windows, no WPF/UWP/... needed;
see `DWMWA_USE_HOSTBACKDROPBRUSH` here: https://docs.microsoft.com/en-us/windows/win32/api/dwmapi/ne-dwmapi-dwmwindowattribute#remarks.

But it does require using a bunch of winrt things instead of plain old dcomp.h.

**Comment by Extrimis** [comment]
Yes it is possible too
