### ISSUE TITLE
Scaling a CompositionSurfaceBrush

### ISSUE THREAD

**Issue by ratishphilip** [Microsoft/WindowsUIDevLabs#220]
HI,
I am currently on Windows Insider Build 16199 and SDK version is 16190.

I am creating a CompositionSurfaceBrush using a CanvasGeometry and setting this as the Brush of a SpriteVisual.

Now when I animate the scale property of the Visual to a value larger than its original scale, I see that the CanvasGeometry getting blurred. I understand that to improve performance the brush is simply scaled due to which the image appears blurred.

![scalegeometry](https://user-images.githubusercontent.com/7021835/26905502-92465998-4b9c-11e7-93bc-c2d1c05396e6.png)

Is there a way to enforce the scaling of the geometry during the animation? Or can an event be provided (like the Draw event in Win2d) which allows the developer to update the brush?

Here is the sample code.

```C#
private Compositor compositor;
private CanvasDevice canvasDevice;
private CompositionGraphicsDevice graphicsDevice;


public MainPage()
{
	InitializeComponent();

	Loaded += MainPage_Loaded;
}

private void MainPage_Loaded(object sender, RoutedEventArgs e)
{
	compositor = Window.Current.Compositor;
	canvasDevice = CanvasDevice.GetSharedDevice();
	graphicsDevice = CanvasComposition.CreateCompositionGraphicsDevice(compositor, canvasDevice);

	var visual = CreateVisual();

	ElementCompositionPreview.SetElementChildVisual(this, visual);

	var scaleAnim = compositor.CreateVector2KeyFrameAnimation();
	scaleAnim.Duration = TimeSpan.FromSeconds(2);
	scaleAnim.InsertKeyFrame(0, new Vector2(1,1));
	scaleAnim.InsertKeyFrame(1, new Vector2(2, 2));
	scaleAnim.IterationBehavior = AnimationIterationBehavior.Forever;

	visual.StartAnimation("Scale.XY", scaleAnim);
}

public CompositionDrawingSurface CreateSurface(Size surfaceSize, CanvasGeometry geometry, ICanvasBrush fillBrush, ICanvasBrush strokeBrush, float strokeWidth)
{
	var surface = graphicsDevice.CreateDrawingSurface(surfaceSize, DirectXPixelFormat.B8G8R8A8UIntNormalized, DirectXAlphaMode.Premultiplied);
	// Render the geometry to the surface
	using (var session = CanvasComposition.CreateDrawingSession(surface))
	{
		if (geometry != null)
		{
			// If fillBrush is defined then fill the geometry area
			if (fillBrush != null)
				session.FillGeometry(geometry, fillBrush);

			// If stroke is defined then outline the geometry area
			if (strokeBrush != null)
				session.DrawGeometry(geometry, strokeBrush, strokeWidth);
		}
	}

	return surface;
}

public Visual CreateVisual()
{
	var visual = compositor.CreateSpriteVisual();
	visual.Size = new Vector2(200, 200);
	visual.Offset = new Vector3(300, 300, 0);

	var geometry = CanvasGeometry.CreateCircle(canvasDevice, visual.Size * 0.5f, visual.Size.X / 2);
	var fillBrush = new CanvasSolidColorBrush(canvasDevice, Colors.YellowGreen);
	var strokeBrush = new CanvasSolidColorBrush(canvasDevice, Colors.Black);
	var surface = CreateSurface(visual.Size.ToSize(), geometry, fillBrush, strokeBrush, 3);
	visual.Brush = compositor.CreateSurfaceBrush(surface);

	return visual;
}
```

**Comment by sohchatt** [comment]
For KeyframeAnimations, you can draw your geometry at the appropriate scale right before you animate (eg. draw at 2X scale right before you call StartAnimation). Is this solution helpful in your case? Or were you planning on scaling geometry in other ways that would render this solution unusable?

**Comment by ratishphilip** [comment]
Just like in each frame of an ExpressionAnimation or KeyFrameAnimation the properties of the Visuals are calculated, I would like a similar way to redraw the geometry (for each frame) during the scale animation.

This is possible in Win2d with the Draw event handler.

It would be great if Windows Composition could provide a similar eventhandler for us developers.

**Comment by sohchatt** [comment]
Thanks for the feedback, @ratishphilip . We have two items on our backlog list that will hopefully address your problem:

1. [Animated Vector Graphics support in Composition](https://developer.microsoft.com/en-us/windows/platform/features/animatedvectorgraphicssupportinthevisuallayer/)
2. [Animation support for non-Composition objects](https://developer.microsoft.com/en-us/windows/platform/features/animationsystemtodrivenoncompositionobjectslikewin2dobjects/): while this won't get you animation callbacks from composition animations, your feedback and insight into how you wish to mix Win2D and Composition animations may make this feature a possible solution for your problem.

**Comment by daneuber** [comment]
@ratishphilip It looks like this may be resolved now; please feel free to check out the linked backlog issues and vote on UserVoice. Closing this issue.
