### ISSUE TITLE
AccessViolationException when setting character format in RichEditBox

### ISSUE THREAD

**Issue by Sergio0694** [Microsoft/WindowsUIDevLabs#223]
Hello, I'm not sure whether this is the right place to post this issue, but I've been having some problems (as well as many other users) with the `RichEditBox` control since WinRT came out, and not those problems have persisted on UWP.

In my case, I'm getting a `System.AccessViolationException` when setting the character format of a text range. [**Here's a screen**](http://i.pi.gy/Or8b.png). There are two problems:
1. An `AccessViolationException` is a low level exception that just can't be caught with managed code, so I don't think a control from the official framework like the `RichEditBox` is ever supposed to throw one of these exceptions.
2. As you can see, the loop index here is 1103, and it changes every time, sometimes it works fine, sometimes it crashes at a different position, it just seems to happen at random.

I've also had other exceptions like that with the same `RichEditBox` control, for example when [**setting some text**](https://stackoverflow.com/questions/26830799/accessviolationexception-when-setting-the-text-in-a-richeditbox) with the `SetText` method, and I've seen many other users complaining about similar issues in the past (see [**here**](https://stackoverflow.com/questions/31691939/changing-richeditbox-selection-text-throws-accessviolationexception) and [**here**](https://social.msdn.microsoft.com/Forums/silverlight/en-US/8592bccf-15f9-4896-a1b3-4509c5a87558/richeditbox-throws-exceptions-when-mixing-text-and-images?forum=wpdevelop)).

The thing here is that it seems like the `RichEditBox` control has had some bugs since the Windows Phone 8.1 days that nobody has ever fixed throughout all these years, and they are now present in Windows 10 as well.

**Is there a workaround you can suggest for this specific crash I'm having?**
I don't even understand why is it happening, I'm just setting the color of a selected range.

And also, could you let the team that works on this control that right now it's not perfectly reliable and has a few issues? I hope this feedback might be useful to them! 😄 

Thanks in advance for your help!

**Comment by ryandemopoulos** [comment]
Hi Sergio, thanks for raising this issue and also the previous issues you linked in your write-up.  

It's not immediately clear what the problem is here, so I've passed this along to the development team for RichEditBox and we'll have them take a look.  I also asked them to look into the other issues you linked.  For the time being, since we're not quite sure what's going on just yet, I don't have a workaround to offer.

**Comment by Sergio0694** [comment]
Hello @ryandemopoulos - thank you for your help and your quick response. I do hope this feedback might help, I'm looking forward to hearing back from the `RichEditBox` team! If needed, I can also share the code with them so they can actually replicate the crash and try to investigate it in case it is useful.

**Comment by sidprasad** [comment]
Hi Sergio,
I am a developer who works on `RichEditBox`. I'm having some trouble replicating the crash you mentioned, and would appreciate any further details. You mentioned that you might be able to share some code to help with the investigation -- this would be super helpful!

**Comment by Sergio0694** [comment]
@sidprasad Hello,
thank you so much for your contacting me.
I've sent you an invite to the repo of the app in question, the crash is happening at like 559 (master branch at the moment), at this statement:

```csharp
range.CharacterFormat.ForegroundColor = Brainf_ckFormatterHelper.GetSyntaxHighlightColorFromChar(c);
```

Here's how to easily reproduce the issue:
1) Open the solution, go to `Brainf_ck_sharp_UWP\Views\IDEView.cs`, scroll down to the `LoadCode` method (line 511) and replace the for loop with this test code:

```csharp
// Highlight the new text
while (true)
{
    int count = 0;
    for (int i = start; i < end; i++)
    {
        ITextRange range = EditBox.Document.GetRange(i, i + 1);
        char c = range.Character;
        range.CharacterFormat.ForegroundColor = Brainf_ckFormatterHelper.GetSyntaxHighlightColorFromChar(c);
    }
} 
```
The outer `while (true)` is just to avoid wasting time reloading different saved codes by hand until the app crashes.

2) Run the app
* swipe right to go to the IDE page
* Tap "..." in the command bar at the bottom
* Select "Pick saved source code"
* Choose any one of them (you can try with longer codes like Unicode sum or Sum)

3) At this point the app should crash after a few second, if for some reason it doesn't, just close and reopen it and do the same again, I tried now and I managed to successfully reproduce the crash quite a few times.

Hope this helps, let me know if there's anything else I can do and how it goes with the investigation!
Best regards,
Sergio

**Comment by sidprasad** [comment]
Hi Sergio,
Thank you for the quick response and detailed steps. I'm still finding it hard to reproduce this crash. It would be very helpful if you could share a crash dump with us. Once you encounter the crash while debugging, you can save a dump as follows:

1. In VisualStudio: `Debug -> Save Dump As`
2. Save as a `Minidump with Heap (*.dmp)`

Thanks for raising this issue!

**Comment by Sergio0694** [comment]
@sidprasad Hello, 
I'm sorry about that, I know it's not easy to reproduce the issue as it seems not to have a precise pattern.
Anyways, I've created a [crash dump](https://1drv.ms/u/s!AjTEhZcuNvx2vfNO5FQ0dTnO2823nA), hope it helps!
I've also included the .pdb file for the application (in Debug mode), in case you need them.

Please let me know if there's anything else I can do to help you investigate the issue.
Have a nice day, thank you so much again for your help!
Sergio

**Comment by Sergio0694** [comment]
@sidprasad Hello, any news on the issue? The exception/crash is happening quite often for me and there's nothing I can do about it. Did the crash dump help investigate the problem?
Thanks again! 😊

**Comment by sidprasad** [comment]
@Sergio0694 

Hi Sergio,

Thank you for the crash dumps! I'm still unable to internally repro the bug. It may be that there are differences between my setup and yours. I was hoping you could tell me what language packs you have installed on the machine, as well as what your default language is.

Thank you again for raising the issue.

**Comment by Sergio0694** [comment]
@sidprasad Hello, no problem, I hope the crash dump will help if you can't reproduce the issue on your own. Even though, as I said, it doesn't always happen for me either, sometimes it crashes 2-3 times in a row when I reformat the whole document (so when I apply a character format to every character in the text), sometimes I manage to use the app for quite a while, loading different documents too, without any issue. I just can't can't find a way to reproduce the crash with perfect accuracy either.

Anyways, this is my current [language setup](http://i.pi.gy/ZJVO.png) on my PC - I have Italian (Italy) set as my primary language, and English (United States) available but not downloaded yet.
Thank you for your help! 😄

**Comment by stmoy** [comment]
Thank you again for your help identifying and isolating this bug. We believe that we have fixed both this issue and the one mentioned [here](https://github.com/Microsoft/WindowsUIDevLabs/issues/231), as both stemmed from the same issue. 

This fix should be coming your way in an upcoming Windows Insider build post-Fall Creators Update (build numbers higher than 17000+). Please reach out if you find that this issue still hits.

**Comment by Sergio0694** [comment]
Hello @stmoy and @sidprasad - thank you so much for your help! Glad to hear my feedback helped and to know the issues have now been fixed, I'll look forward to the new builds then!
Cheers! 😄
