### ISSUE TITLE
Request: Support setting ImplicitShowAnimation in Loading event (for deferred loading)

### ISSUE THREAD

**Issue by JohnnyWestlake** [Microsoft/WindowsUIDevLabs#224]
As the name says, in the usecase of using `x:DeferLoadStrategy` or `x:Load` on a FrameworkElement we can't use `ElementCompositionPreview.SetImplicitShowAnimation` properly before the element shows without actually realising the element, which we don't want (or is difficult if it's all controlled through VisualState setters)

I figured the perfect time to set it would be during the `Loading `event on the element, but unfortunately this is too late for "Show" animation to get applied properly the first time. Is there a better time of setting the Show animation in this case to actually apply during deferred realization, or can the framework be updated to support setting Implicit animations during  a FrameworkElement's `Loading` event?

**Comment by JustinXinLiu** [comment]
Second this.

Currently I have to also set `Visibility` to `Collapsed` on the element and assign the implicit animations after the control is realized, and then toggle the `Visibility` to trigger the animation.

**Comment by daneuber** [comment]
Sounds like a workaround is available. Please open an item in the backlog [here ](https://developer.microsoft.com/en-us/windows/platform/features) if you'd like to record this as a requested feature.
