### ISSUE TITLE
all of the demos and samples are with composition image

### ISSUE THREAD

**Issue by touseefbsb** [Microsoft/WindowsUIDevLabs#226]
I have noticed that all demos and samples are with a custom control known as "common:compositionImage"  what if I want to get same type of effects, e.g: zoom with perspective or photo popup example ,but I don't wanna use photos, instead I want to use listview  items or gridview items within a data template with images and textblocks as well, and I want the effect to be applied to whole item ( gridview item ) instead of the image only scenario. There are no samples for this and the samples already present are very limited to images only they must be generic, so one can understand how to apply same effect in any use case scenario.

**Comment by sohchatt** [comment]
You are correct in pointing out that many of our older samples demonstrate the capability of composition effects in a somewhat limited manner. I'd like to clarify that effects are not restricted to images only: an Effect graph's SourceParameter can be set to ant type of CompositonBrush. This means you can apply effects to:
- 	ColorBrush for Solid Colors
-	GradientBrush for Linear Gradients
-	SurfaceBrush for Surfaces, typically used for Image, Video, or Direct-X swapchains 
-	NineGridBrush for Surfaces subject to Nine-Grid Resizing
-	BackdropBrush to sample background pixels from either within the application or from the application’s desktop background.

In the Composition APIs, an EffectBrush may be painted onto a single SpriteVisual or onto a tree of Visuals via a LayerVisual ([sample](https://github.com/Microsoft/WindowsUIDevLabs/tree/master/SampleGallery/Samples/SDK%2014393/TreeEffects)). As of the Creator's Update, an EffectBrush may be applied directly to your XAML UI by wrapping it in a XamlCompositionBrushBase as demonstrated [here](https://github.com/Microsoft/WindowsUIDevLabs/tree/master/SampleGallery/Samples/SDK%2015063/BrushInterop). 

It seems that the capability you're looking for is something akin to LayerVisual effects in XAML, i.e. applying Effects to a tree of XAML UIElements, entire controls, and so on. Unfortunately, this is an unsupported scenario as of the Fall Creator's Update. You may be able to work around this problem in one of two ways, depending on your needs and use-case:

- use a LayerVisual in a Composition Island if you don't necessarily require particular features from the framework 
- place a BackdropBrush-based Effect (by subclassing a XamlCompositionBrushBase, or ElementCompositionPreview.SetChildVisual for version prior to the Creator's Update) on top of your XAML control. Please do note that Backdrop effects are expensive in terms of performance and should be used judiciously/sparingly. 

I understand that neither option is ideal but these should provide you with a temporary solution. Your feedback is valuable, and we'll add this request to our public backlog. I hope this helps.
