### ISSUE TITLE
Cannot create an instance of "CompositionImage"

### ISSUE THREAD

**Issue by pronetag** [Microsoft/WindowsUIDevLabs#228]
I try to use the user control ImagePopupViewer but in VS 2017 it says in XAML designer:

Method not found: 'void Windows.UI.Composition.Vector2KeyFrameAnimiation.InsertKeyFrame(Single, System.Numerics.Vector2);

for below statements:

        <common:CompositionImage x:Name="BackgroundImage" Stretch="Fill" Grid.RowSpan="2" />
        <common:CompositionImage x:Name="PrimaryImage" Margin="10" Grid.Row="0" MinHeight="300" MinWidth="300"/>

Target version: 15063
Min version: 14393

**Comment by ratishphilip** [comment]
The XAML Designer will not render it correctly.
Though when you run the application, it should work fine.

**Comment by pronetag** [comment]
Actually the SamplesNative Project is targeted to x64 and adjust all other projects to target to x64 then problem solved.
