### ISSUE TITLE
How to animate size changes of hand-out visual using implicit animations?

### ISSUE THREAD

**Issue by SvenEV** [Microsoft/WindowsUIDevLabs#230]
I'd like to animate changes to the position and size of XAML elements using implicit animations. I understand that a XAML element's position (as calculated by the layout system) corresponds to `Visual.Offset` and I can successfully animate this. Similarly, I would expect a XAML element's size to correspond to `Visual.Size` (or `Visual.Scale`), but unfortunately implicit animations targeting this property don't seem to have any effect.

For testing purposes I created a Page with a simple Border element and four buttons to change its position and size. Currently, elements are smoothly animated to their new position, but they resize instantly without any animation. Please see my code below:
```CSharp
public sealed partial class MainPage : Page
{
    public MainPage()
    {
        InitializeComponent();

        var v = ElementCompositionPreview.GetElementVisual(border);

        var offset = v.Compositor.CreateVector3KeyFrameAnimation();
        offset.InsertExpressionKeyFrame(1, "this.FinalValue");
        offset.Duration = TimeSpan.FromSeconds(1.5);
        offset.Target = nameof(Visual.Offset);

        var size = v.Compositor.CreateVector2KeyFrameAnimation();
        size.InsertExpressionKeyFrame(1, "this.FinalValue");
        size.Duration = TimeSpan.FromSeconds(1.5);
        size.Target = nameof(Visual.Size);

        var scale = v.Compositor.CreateVector3KeyFrameAnimation();
        scale.InsertExpressionKeyFrame(1, "this.FinalValue");
        scale.Duration = TimeSpan.FromSeconds(1.5);
        scale.Target = nameof(Visual.Scale);

        var anims = v.Compositor.CreateImplicitAnimationCollection();
        anims[nameof(Visual.Offset)] = offset;
        anims[nameof(Visual.Size)] = size;
        anims[nameof(Visual.Scale)] = scale;
        v.ImplicitAnimations = anims;
    }

    private void OnLeftButtonClick(object sender, RoutedEventArgs e) =>
        border.HorizontalAlignment = HorizontalAlignment.Left; // animated

    private void OnRightButtonClick(object sender, RoutedEventArgs e) =>
        border.HorizontalAlignment = HorizontalAlignment.Right; // animated

    private void OnSmallButtonClick(object sender, RoutedEventArgs e) =>
        border.Width = border.Height = 100; // NOT animated

    private void OnLargeButtonClick(object sender, RoutedEventArgs e) =>
        border.Width = border.Height = 200; // NOT animated
}
```

Did I misunderstand something or is this scenario not (yet) supported? Thanks!

**Comment by JustinXinLiu** [comment]
I don't believe this is supported currently. Size change from XAML element involves layout update which is a lot more complicated(running on the UI thread, bad for performance, etc.) than simple offset change. I'd love to know if there's any way we can  support this in the future though.

What I normally do to work around this is, create a `SpriteVisual` as the background of your `Border`, and make the `Border` background transparent. This `SpriteVisual`'s size should be in sync with the `Border`'s render size, and is animatable.

**Comment by SvenEV** [comment]
Thanks for your response. That's some valuable information, I think it would be nice to have this documented somewhere.

The approach with a `SpriteVisual` in the background does indeed work, but only when syncing the visual's size with the XAML element's size manually via `SizeChanged` events. There's no animation when setting `RelativeSizeAdjustment = Vector2.One` instead.

**Comment by shandilvarun** [comment]
Hi @SvenEV, as Justin mentioned Size changes in XAML makes a lot of changes to the element including clips and other layout properties. Sadly Visual Size and UIElement Size are not the same thing. we are actively working to figure out how make UIElement Size change animations simple and easy. I will share the details here once we have a proposal around this. 
Thanks @JustinXinLiu  for jumping in and providing a workaround.
