### ISSUE TITLE
App hangs and eventually throws an AccessViolationException when getting text from a RichEditBox and updating the UI too quickly

### ISSUE THREAD

**Issue by Sergio0694** [Microsoft/WindowsUIDevLabs#231]
Hello, I'm working on an app that relies on the `RichEditBox` control ([Brainf\*ck#](https://www.microsoft.com/store/apps/9nblgggzhvq5)) and I keep getting `AccessViolationException`s every now and then.
I've found another way to reproduce one of these, it usually happens whenever I get the text from the `RichEditBox` too quickly and then edit the UI.
This is the usual crash popup I get: [http://i.pi.gy/PQql.png](http://i.pi.gy/PQql.png) (the underlined text says "Unhandled win32 exception in ...").
Unfortunately VS won't let me create a crash dump (that option is grayed out) so I don't have that right now. Still, I'll be happy to share the code and more details on the issue if that can help.

> The program '[11364] Brainf_ck-sharp.UWP.exe' exited with code -1073741819 (0xc0000005) 'Access violation'.

This is the general idea: I'm displaying some UI overlays over the `RichEditBox` to show the whitespaces and the tab characters in the text. I do this by retrieving the text every time it changes, getting the coordinates of every ' ' and '\t' character, then adding a new UI element in a `Canvas` that overlays the `RichEditBox`.
I know it would probably be better to just have a Win2D canvas on top of the `RichEditBox` and to draw the overlays in there, I'll probably look into it in the future, for now I'm just using actual UI elements (plus, I wouldn't have discovered this issue if I had used Win2D from the start).

**Edit**: I've implemented the overlays with a Win2D `CanvasControl` behind the `RichEditBox` and everything seems to be working fine (I'm keeping the 500ms delay just in case though). Still, that `AccessViolationException` shouldn't be thrown when working with simple UWP controls.

I'm using a `SemaphoreSlim` object to make sure that I'm never getting the text from the `RichEditBox` or adding new UI elements concurrently, but I'm still getting that `AccessViolationException`.
**Note**: the whole thing works fine most of the times, but if I just keep the spacebar key down so that the `RichEditBox` keeps quickly adding spaces in the text, the crash eventually happens (that's why I think it could be a synchronization issue or something like that).

I've solved this by adding a 500ms delay between the `TextChanged` event and when I actually update the UI, and by making sure I never update the UI with less than a 500ms interval between each call. Also, I'm skipping new `TextChanged` events if they happen before 500ms since the last one that got handled.

This seems to have fixed the issue (as a workaround), so I guess there's some kind of synchronization problem within the `RichEditBox` or somewhere in one of the UWP libraries.

I know the description can be a bit vague, so again, I'll be happy to share the source and the steps needed to reproduce the issue. Thank you in advance for your help!
Sergio

**Comment by stmoy** [comment]
Hi Sergio, thank you for reaching out. 

We believe that we have fixed both this issue and the one mentioned [here](https://github.com/Microsoft/WindowsUIDevLabs/issues/223), as both stemmed from the same issue. As you mention above, the root cause of this bug had to do with a multi-threaded timing issue between the XAML framework control and the underlying text stack. 

This fix should be coming your way in an upcoming Windows Insider build post-Fall Creators Update (build numbers higher than 17000+). Please reach out if you find that this issue still hits.
