### ISSUE TITLE
ShyHeader "bounces" when pulled too far

### ISSUE THREAD

**Issue by pcolmer** [Microsoft/WindowsUIDevLabs#233]
I love the ShyHeader effect but it doesn't *quite* match how Groove has implemented it.

In Groove (see video), if I pull down, nothing happens - the header stays at the maximum size.

[Groove Music 23_07_2017 21_36_38.zip](https://github.com/Microsoft/WindowsUIDevLabs/files/1168393/Groove.Music.23_07_2017.21_36_38.zip)

However, in the sample app (see video), if I pull down, the header grows and then bounces back to the maximum size.

[Windows UI Dev Labs Sample Gallery 23_07_2017 21_37_20.zip](https://github.com/Microsoft/WindowsUIDevLabs/files/1168394/Windows.UI.Dev.Labs.Sample.Gallery.23_07_2017.21_37_20.zip)

What do I need to do in order to get ShyHeader to behave the same way as Groove? I find the over-growth and bounce-back unappealing unfortunately.

This is with build 15063.

**Comment by likuba** [comment]
Yah--no problem.  You can just comment out the lines that animate the header scale during overpan/bounce:
```

            // Create and start an ExpressionAnimation to scale the header during overpan

            ExpressionNode headerScaleAnimation = EF.Lerp(1, 1.25f, EF.Clamp(scrollingProperties.Translation.Y / 50, 0, 1));

            headerVisual.StartAnimation("Scale.X", headerScaleAnimation);

            headerVisual.StartAnimation("Scale.Y", headerScaleAnimation);

```
Once you are removing that, you can also get rid of this:

```


            //Set the header's CenterPoint to ensure the overpan scale looks as desired

            headerVisual.CenterPoint = new Vector3((float)(Header.ActualWidth / 2), (float)Header.ActualHeight, 0);
```

Hopefully that updates it to give you the effect you want!

**Comment by pcolmer** [comment]
Brilliant! Thank you.
