### ISSUE TITLE
The animation is not work properly at first time.

### ISSUE THREAD

**Issue by cjw1115** [Microsoft/WindowsUIDevLabs#234]
I called the follow method at page's loaded event handler,but there is no any effect. It is work properly Only if I called the method twice. I'm not sure if it is a bug or I used incorrect. So I post a issue. Thanks.(My os version is 15063,and the vs build target is also 15063.)
Thanks.

        public void CreateParralaxEffect()
        {
            var scrollViewer = listView.GetFirstDescendantOfType<ScrollViewer>();
            var scrollViewerPropset = ElementCompositionPreview.GetScrollViewerManipulationPropertySet(scrollViewer);

            var compositor = ElementCompositionPreview.GetElementVisual(this).Compositor;

            var imgOffsetYAnimation = compositor.CreateExpressionAnimation("Clamp(visual.Translation.Y*factor,-450,1000)");
            imgOffsetYAnimation.SetScalarParameter("factor", 0.4f);
            imgOffsetYAnimation.SetReferenceParameter("visual", scrollViewerPropset);
            imgOffsetYAnimation.Target = "Offset.Y";

            var backgroundVisual = ElementCompositionPreview.GetElementVisual(imgBackground);
            backgroundVisual.StartAnimation("Offset.Y", imgOffsetYAnimation);
        }

**Comment by likuba** [comment]
Hey @cjw1115 --
I think you may be hitting an issue where both XAML layout and your parallax animation are trying to control Offset.  If you try using the Translate property as shown in [this sample](https://github.com/Microsoft/WindowsUIDevLabs/tree/master/SampleGallery/Samples/SDK%2015063/OffsetStompingFix), does that fix your issue?

**Comment by cjw1115** [comment]
@likuba Thank you for your reply.

As your help,I run the sample code on my machine and found out the problem.And I also found a post about the feature. (here is uri [http://blog.robmikh.com/uwp/xaml/composition/2016/07/16/changes-to-xaml-composition-interop.html](url)) . So I think this is a change about compositon api sdk in November Update,not a bug.

Thanks.You can close the issure now.

**Comment by daneuber** [comment]
@cjw1115 Thanks for the follow up. Marking as closed.
