### ISSUE TITLE
Calling TryUpdatePositionWithAdditionalVelocity while animation in progress breaks Resting points

### ISSUE THREAD

**Issue by jmvillagra** [Microsoft/WindowsUIDevLabs#235]
Hi,
I'm working on a Carrusel control using the InteractionTracker & RestingValues and i'm facing a problem using TryUpdatePositionWithAdditionalVelocity to animate the carrusel when the user is using the keyboard/mouse... basically, if i call TryUpdatePositionWithAdditionalVelocity when an animation is still runing, it braaks the restingvalues behaviour and the animation doesn't stop at any of the resting values configured...

I've recorded a small video to show the behaviouer:
https://youtu.be/em13tdfcT9s

Basically, everytime the user clicks on the next / previous button i try to set up a new position:

        private void BttnRight_Tapped(object sender, TappedRoutedEventArgs e)
        {
            e.Handled = true;
            _tracker.TryUpdatePositionWithAdditionalVelocity(new Vector3(2500f, 0f, 0f));
        }

Is this behaviour by design or is it a bug?
Should i try to animate the position to the new value using animations directly without the _tracker or try to use the _tracker.TryUpdatePositionWithAnimation() instead?

Thank you.

**Comment by patsiu** [comment]
Hey @jmvillagra!

Thanks for reaching out with your question. In general, if you want to make sure your resting values get applied, you'll want to use TryUpdatePositionWithAdditionalVelocity(). TryUpdatePositionWithAnimation() will put InteractionTracker into a different state (custom animation) and won't use consider your resting values when considering where InteractionTracker lands.

I took a look at your video, and i'm wondering if you can help me understand with two things:
- Can you put a copy of your Expressions that define both the Condition and the RestingValue?
- Confirm that for both your left and right button clicks you are using TryUpdatePositionWithAdditionalVelocity??
 
Thanks!

**Comment by jmvillagra** [comment]
Hi @patsiu 
I've created a test repo with the control:
https://github.com/villagra/CarruselWinUI

It's a bit messy as i'm still testing things but all the animations configuration is here: https://github.com/villagra/CarruselWinUI/blob/master/Carrusel/Controls/Carrusel.xaml.cs

**Comment by patsiu** [comment]
Thanks @jmvillagra!

I downloaded and have been playing with your project but haven't been able to repro the behavior you showed in the video. I followed the same order of button clicks but the motion seems to land correctly on one of the carousel images.

What build # are you seeing this issue happen on? Do you have another set of steps that repros the problem consistently?

Thanks!

**Comment by jmvillagra** [comment]
Hi,
I've updated the speed in the example to 1500 and now it's easier to reproduce....  i can "easilly reproduce it" selecting one of the items on the sides, then tapping on the button to select the center item and before the animation ends tapping on the button again... it doesn't happens all the time but it's how i can repdouce it...

I'm using the "release build" 1703, 15064.483

Thank you!

**Comment by jmvillagra** [comment]
I changed to use TryUpdatePositionWithAnimation instead of TryUpdatePositionWithAdditionalVelocity and it's working pretty well:

Still lots of details and animations tweaks to do, but it's starting to look great ;)
https://www.youtube.com/watch?v=mdQIRA-terQ&feature=youtu.be

Thanks

**Comment by daneuber** [comment]
@jmvillagra looks great, thanks for sharing the video! Closing this as it appears there is a workaround, and we'll take internal action item to look into this more. Please re-open if this is still an issue.
