### ISSUE TITLE
composition image control throws memory exception on mobile

### ISSUE THREAD

**Issue by touseefbsb** [Microsoft/WindowsUIDevLabs#236]
I tried to run sample gallery app on mobile emulator ( anniversary edition ) and even tried to install sample app from store and ran that, but the app opens the homepage for about 2 secs and then crashes. with composition image control giving some memory exception

**Comment by peterfelts** [comment]
Thanks for reporting this. We were able to reproduce what you're seeing. We also noticed that if you disable visual UI debugging tools for XAML (project options > Debugging > General > "Enable UI Debugging Tools for XAML") the exception doesn't occur. We've created an internal bug to track this.

**Comment by touseefbsb** [comment]
Oh ok thanks for telling me the work around

**Comment by daneuber** [comment]
Closing since workaround has been provided and we're tracking this. Please let us know if you continue to experience issues.
