### ISSUE TITLE
How to know when pointer exists the element when using GetPointerPositionPropertySet?

### ISSUE THREAD

**Issue by JustinXinLiu** [Microsoft/WindowsUIDevLabs#238]
I understand that I can use `ElementCompositionPreview.GetPointerPositionPropertySet(MyElement)` to create expression animations, but I can't seem to figure out how to fire off a keyframe animation when the pointer exits from `MyElement`, without using *UI thread-bound* events like `PointerExited`.

Is this currently supported by Composition?

**Comment by patsiu** [comment]
Hey @JustinXinLiu, 

PointerPositionPropertySet provides you with only the position of the pointer while it is within the bounds of the passed-in UIElement. The existing Pointer Events available on UIElement are currently the only way to know when things like enter/exit occur.

**Comment by JustinXinLiu** [comment]
I see, thanks @patsiu for the clarification.
