### ISSUE TITLE
ExpressionAnimation should support resting points that can invoke keyframe animations

### ISSUE THREAD

**Issue by JustinXinLiu** [Microsoft/WindowsUIDevLabs#239]
Take a *pull-to-refresh* scenario for example, if I pull down the list by say, `120px`, I'd like the expression animation to kick off a keyframe animation and ignore the expression calculation.

Does this make sense?

**Comment by patsiu** [comment]
Hey @JustinXinLiu,

Thanks for the feedback! Just to clarify, you're looking for a way to conditionally trigger the start of an animation yes? Outside of when the output of an animation or property meets a condition, are there any other ways you find useful to conditionally trigger an animation?

**Comment by JustinXinLiu** [comment]
Yes, that's correct.

Currently when I want to stop the expression animation and trigger a keyframe *reset* animation when a condition is met, I will need to monitor this by subscribing to an input event, stop the expression animation and start the keyframe one.

Since it's not possible to get the animated value from an expression animation, this approach only works when an input event is given.

It's almost like the `Condition` and `RestingValue` in `InteractionTrackerInertiaRestingValue`. So I guess it would be cool if the resting animation could be either a keyframe or an expression animation.

**Comment by JustinXinLiu** [comment]
I will give you a scenario. :) Take your *Pointer Rotate* demo for an example, when the cursor enters the picture, how to smoothly animate the rotation of the picture instead of changing the initial rotation instantly; when the cursor leaves, how to again smoothly animate it to the original position? This will require A LOT more code than what's currently there.

**Comment by patsiu** [comment]
Ok - that makes sense. Thanks for sending this info over, we'll use this information to help evaluate this feature against the rest of our work. If other scenarios come to mind, send them our way :)

Thanks again @JustinXinLiu!

**Comment by daneuber** [comment]
@JustinXinLiu thanks for the feedback. We've created [this UserVoice feedback item](https://wpdev.uservoice.com/forums/110705-universal-windows-platform/suggestions/31346728-expressionanimation-should-support-resting-points) and will be tracking it there.
