### ISSUE TITLE
Debuggiing Error

### ISSUE THREAD

**Issue by AkhilBhaskar** [Microsoft/WindowsUIDevLabs#241]
Attempting to deploy a UWP Windows app in Master mode throws an unhandled exception as follows:
Unhandled exception at 0x603FF073 (Windows.UI.Xaml.dll) in HopTheBall.exe: 0xC000027B: An application-internal exception has occurred (parameters: 0x038C1FB0, 0x00000002).
Can Anyone Plese Find The Solution

**Comment by daneuber** [comment]
Closing as duplicate
