### ISSUE TITLE
ExpressionAnimation expression string length problem

### ISSUE THREAD

**Issue by limefrogyank** [Microsoft/WindowsUIDevLabs#243]
I'm trying to write an expression that outputs the same value that Math.Atan2 would output.  (I need to rotate a Visual that represents a connector between two existing Visuals.)  I'm using ExpressionBuilder to do it in a typed fashion and I've created a series of conditionals that should work:

```
var diff = nodeBRef.Offset - nodeARef.Offset;
var rotationExpression = EF.Conditional(
    diff.X > 0,
    EF.ATan(diff.Y / diff.X),
    EF.Conditional(
        (diff.X < 0) & (diff.Y >= 0),
        EF.ATan(diff.Y / diff.X) + (float)Math.PI,
        EF.Conditional(
            (diff.X < 0) & (diff.Y < 0),
            EF.ATan(diff.Y / diff.X) - (float)Math.PI,
            EF.Conditional(
                (diff.X == 0) & (diff.Y > 0),
                (float)Math.PI / 2f,
                EF.Conditional(
                    (diff.X == 0) & (diff.Y < 0),
                    -(float)Math.PI / 2f,
                    0
                )
            )
        )
    )
);
child.StartAnimation("RotationAngle", rotationExpression);
```

The problem is that when I debug the app, WinRT spits out an error that says the expression string is too long.  The app runs, but the animation does not work.  I managed to get it to run by dropping out the edge cases where x == 0, but I'm guessing that's going to give me some glitches.

I'm not sure I've seen anything in the documentation about a limit to how big your expression string is allowed to be.  In any case, is there a workaround to doing these nested conditionals?

**Comment by JustinXinLiu** [comment]
Have a look at this [issue](https://github.com/Microsoft/WindowsUIDevLabs/issues/177). There's a limit of 1000 chars.

**Comment by limefrogyank** [comment]
Thanks! That thread clears up a few things and a possible workaround.
