### ISSUE TITLE
Using ElementCompositionPreivew.GetElementVisual immediately after running ConnectedAnimation 

### ISSUE THREAD

**Issue by limefrogyank** [Microsoft/WindowsUIDevLabs#245]
I don't think this is a bug per se, however, I'm finding that there isn't an easy way to avoid the problem I've encountered.

I am using a ``ConnectedAnimation`` to animate an image and text moving from one page to the next during navigation.  On the detail page, I am creating a "Shy Header" just like in the samples.  The problem is that the image and text in the ``ConnectedAnimation`` are in the header I'm configuring to be 'shy'.

When I call ``ElementCompositionPreivew.GetElementVisual`` on the image (a ``Rectangle`` with ``ImageBrush``), it will completely disappear from the screen.  It is still located in the tree, but you can't see an image anymore.  I'm certain it's conflicting with the still running ``ConnectedAnimation``, but the way I am getting around it is not simple.  

First, I had to wait for the ``Completed`` event on the ``ConnectedAnimation``.  However, that creates a weird situation where the XAML element isn't rendered properly before I take over the ``Visual``.  My ``Rectangle`` needs to have a specific ``Margin`` of 10, but in this case, it will have zero margin.  

Second, (in addition to the 1st point) I tried to wait for the ``ImageBrush.ImageOpened`` event before getting the ``Visual`` using ``ElementCompositionPreivew.GetElementVisual`` .  However, usually the image has already been opened and the event is never fired.  Sometimes it does, usually it doesn't.

Third, I'm checking the underlying ``BitmapImage`` to see if it is already loaded by checking for a non-zero ``PixelHeight``.  If that is the case, I get the ``Visual``.  If not, then I wait for the ``ImageOpened`` event first.  This seems to be working, but is a really clumsy workaround.  

**Basically, I'm wondering if this could be improved somehow.**

This is the resulting code:
```
// animation is the ConnectedAnimation that was just started... this is all in the Page.Loaded event
animation.Completed += (s2, e2) =>
            {
                var imageBrush = (ImageBrush)ImageRectangle.Fill;
                var source = (BitmapImage)imageBrush.ImageSource;
                if (source.PixelHeight > 0)
                {
                    Visual profileVisual = ElementCompositionPreview.GetElementVisual(ImageRectangle);
                    profileVisual.CenterPoint = new Vector3(0f, (float)ImageRectangle.ActualHeight, 0);
                    profileVisual.StartAnimation("Scale.X", iamgeScaleAnimation);
                    profileVisual.StartAnimation("Scale.Y", iamgeScaleAnimation);
                }
                else
                {
                    imageBrush.ImageOpened += (s3, e3) =>
                    {
                        Visual profileVisual = ElementCompositionPreview.GetElementVisual(ImageRectangle);
                        profileVisual.CenterPoint = new Vector3(0f, (float)ImageRectangle.ActualHeight, 0);
                        profileVisual.StartAnimation("Scale.X", iamgeScaleAnimation);
                        profileVisual.StartAnimation("Scale.Y", iamgeScaleAnimation);
                    };
                }
            };
```

**Comment by limefrogyank** [comment]
Hmmm... on the phone emulator, this was sort of working. On the PC, in a regular app, it does not work at all.  There's something going on with the timing in that case.

I can't get this to work other than to manually put the ``Margin`` back in to the ``Visual`` after I pull it out of the XAML element using the ``Offset`` property.  I'm going to see if I can make a repro...

**Comment by limefrogyank** [comment]
I created a reproduction of this issue on my GitHub.

https://github.com/limefrogyank/ConnectedAnimationShyHeaderBug

If you'd rather have it in a zip file, I don't remember how to package it without making it giant...

**Comment by limefrogyank** [comment]
It seems ConnectionAnimations don't work with XamlLight either.  If I have a XamlLight added to the underlying ListViewItem, I'll crash the entire app when the ConnectionAnimation is started on the new page.

**Comment by shandilvarun** [comment]
Hi @limefrogyank, as part of connected animation platform uses the backing visual to perform its animation which might be causing issue for your scenario. the thing i will recommend is to wait for connected animations to finish before you request the backing visual to perform further operations. 

Let me know if this works for you.

**Comment by shandilvarun** [comment]
@limefrogyank, the pattern we are using for connected animations is to start the connected animations i.e. ConnectedAnimationService.TryStart(...) when imageOpened event is fired, this helps us to get the correct size and perform animations. if you do that and wait from completion of animation then you should be able to avoid the above situation. I'm closing this issue for now. if you have further questions or concerns then please feel free to reactivate this. Thanks!
