### ISSUE TITLE
Any support for WPF in the future?

### ISSUE THREAD

**Issue by assassin316** [Microsoft/WindowsUIDevLabs#248]
Since the Composition api deals with the DWM and Win2D etc, will you ever support this on WPF ??

**Comment by assassin316** [comment]
Hello ???  Anyone from the Composition team active in these forums??

**Comment by nerddawg** [comment]
Could you elaborate more on your needs with Composition APIs in WPF? We'd love to know more specifics of what you want to achieve. 

This thread on User Voice is where we are track developer votes for the feature: [https://aka.ms/windowsui/inwin32](https://aka.ms/windowsui/inwin32). 

These are the WPF related items from our product backlog: [https://developer.microsoft.com/en-us/windows/platform/features/?q=wpf](https://developer.microsoft.com/en-us/windows/platform/features/?q=wpf)

**Comment by assassin316** [comment]
Thanks for the links!  It's exactly that, to have the Composition API available to WPF to keep up with the latest changes to UWP. WPF still has a large user base and such an API would be a great benefit. I will be voting.

**Comment by ajbennet** [comment]
Thanks Max. We are well aware of the large user base that WPF has, so we are exploring options to figure out the right way to get Modern UI to WPF and other Win32 Desktop applications. Your votes would definitely help us justify and if you could get a lil more specific on the parts you are trying to modernize or use Composition APIs, that ll help us prioritize and build the right solution.

**Comment by assassin316** [comment]
In my personal opinion, just the basics would be a great start for WPF: translate, scale, rotate, opacity as well as blur and shadow effects. The performance alone from the Composition API is beneficial enough.

**Comment by ajbennet** [comment]
That is the exact kind of information I was looking for. Thanks.

**Comment by daneuber** [comment]
Thanks @assassin316 for the feedback and for contributing on UserVoice. Closing this item out for now since the request is tracked elsewhere.
