### ISSUE TITLE
about dispose XamlLight's property CompositionLight's issue

### ISSUE THREAD

**Issue by cjw1115** [Microsoft/WindowsUIDevLabs#249]
There is a CompositionLight property in XamlLight.

if I do the follow action, it will be throw a runtime exception

    CompositionLight.Dispose();
    CompositionLight = null;

exception message : Access violation reading location 0x0000000000000000 .

So I think the dispose method's logic has issue.

Thanks.

**Comment by likuba** [comment]
Thanks for reporting this one--it was actually a platform bug that should be fixed on 16299 released today!  Please reactivate if you are still seeing the issue.
