### ISSUE TITLE
Contextual UI > Pointer Enter/Exit Effects > Spotlight & PointLightFollow crash the app

### ISSUE THREAD

**Issue by kmgallahan** [Microsoft/WindowsUIDevLabs#251]
As per the title, going into the Contextual UI > Pointer Enter/Exit Effects section and selecting either Spotlight or PointLightFollow will immediately crash the app.

This is on Windows 10 build 15063.674, app version 1.1.19.0

**Comment by robald** [comment]
I was unable to reproduce this crash locally.  If you can send a stack or provide any additional details on how to reproduce, we can take another look.

**Comment by kmgallahan** [comment]
@robald 

All I do to reproduce this is launch the app as acquired from the Microsoft Store, navigate to the aforementioned location, and click either of the mentioned selections from the drop down menu.

The app immediately closes, and I'm left with the attached dump files.

[CompositionSampleGallery.exe.88.zip](https://github.com/Microsoft/WindowsUIDevLabs/files/1643114/CompositionSampleGallery.exe.88.zip)

This is now on Windows 10 build 16299.192.

**Comment by robald** [comment]
Ok, I can repro with the version in the store but not when building the app from the repo.  We'll work on getting a store update.  Thanks!
