### ISSUE TITLE
Can't compile Sample Gallery Solution.

### ISSUE THREAD

**Issue by renatorabelo** [Microsoft/WindowsUIDevLabs#255]
I'm getting multiple errros trying to build SamplesGallery.sln.  I'm using visual studio community 2017 version 15.5.0 preview 1 and windows 10 pro insider preview 10017 and the latest sdk. 
I already tried to change target build but with no success.

**Comment by likuba** [comment]
Sorry you're having issues getting up and running.  Could you help clarify which SDK you are currently targeting, as well as maybe share a screen shot or list of the type of errors you are hitting?

**Comment by renatorabelo** [comment]
I successfully compiled the solution (I repaired Visual Studio and retarget the solution).
