### ISSUE TITLE
Using the CompositionObject.Properties property set within expression animation

### ISSUE THREAD

**Issue by ratishphilip** [Microsoft/WindowsUIDevLabs#258]
As of now we can use a  `CompositionPropertySet` within an expression of a `CompositionExpressionAnimation`.

However, `CompositionObject` class contains a property **Properties** of type `CompositionPropertySet` which can come handy is storing object specific values.

But if we include the **Properties** property within the expression  of an `CompositionExpressionAnimation` it throws an exception.

![image](https://user-images.githubusercontent.com/7021835/31799278-fb9e3b9e-b4ed-11e7-9964-a09280ce4706.png)

Is there a plan to accommodate this in future versions? 

Let me give an example where it will be useful
Consider there are three visuals - **VisualA**, **VisualB** and **VisualC**. Each have a key **displacementOffset** defined in their **Properties** property.

```C#
VisualA.Properties.Insert<float>("displacementOffset", 10f);
VisualB.Properties.Insert<float>("displacementOffset", 20f);
VisualC.Properties.Insert<float>("displacementOffset", 30f);

var expAnim = compositor.CreateExpressionAnimation();
exprAnim.Expression = "Vector3(
  center.X + radius * Cos(currAngle + this.Target.Properties.displacementOffset), 
  center.Y + radius * Sin(currAngle + this.Target.Properties.displacementOffset) , 
  0)";

...

VisualA.StartAnimation("Offset", expAnim);          
VisualB.StartAnimation("Offset", expAnim);
VisualC.StartAnimation("Offset", expAnim);
```

I am currently adding an optimization to **CompositionProToolkit** which will allow the usage of the **Properties** property within the lambda expression. It would be great if this feature is supported within Composition itself.

**Comment by patsiu** [comment]
Hey @ratishphilip!

We **_already_** support this behavior - There is a slight tweak you need to do in your Expression :)

In your example, simply do "**this.Target.displacementOffset**"

For context, We have an optimization in our Expression parser that will look against both public properties on a CompositionObject as well as anything that has been put into the Properties PropertySet. As a result, you don't need to write **CompositionObject.Properties.MyCustomProperty** in your Expression, just **CompositionObject.MyCustomProperty**.

**Comment by ratishphilip** [comment]
@patsiu Oh, great. Thanks for the clarification. :)
