### ISSUE TITLE
Sample Projects Don't Build Cleanly Out Of The Box

### ISSUE THREAD

**Issue by csnazell** [Microsoft/WindowsUIDevLabs#26]
I've spent most of this morning getting the sample projects downloaded from github to build cleanly & run. None of the build cleanly without intervention.

As a rule of thumb samples should not be dependent on unrelated dependencies or require developers to sign up for access to services in order to get a sample to build & run succesfully.

In the case of the composition visual sample I had to hand edit the raw xml of the .csproj in order to get it to build.

**Comment by robmikh** [comment]
Hey csnazell, sorry to hear about that. I'll take a look to see what's going on. To confirm, these are the NOV 10586 samples, correct?

**Comment by csnazell** [comment]
Yes, I was having a look at the NOV 10586 samples.

Thanks.

**Comment by JustinXinLiu** [comment]
FYI - I didn't have to do anything to the composition visual sample and it just compiles and runs...

**Comment by csnazell** [comment]
Steps to recreate:

1. Download Zip of repo
1. Unpack to C:\ (since the zip's internal filepaths are too long to unpack into C:\User\...)
1. Copy composition-master into C:\User\...\VS2015\Projects
1. cd into SDK10586_NOV_UPDATE_RTM\CompositionVisual\
1. open composition visual sample solution in VS2015
1. clean
1. rebuild
1. won't build

Reported error:
`>...\compositionvisual\compositionvisual.csproj(128,5): error : This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\Microsoft.Diagnostics.Tracing.EventSource.Redist.1.1.16-beta\build\portable-net45+win8+wpa81\Microsoft.Diagnostics.Tracing.EventSource.Redist.targets.`

The referenced go.microsoft link dumps you into the root of docs.nuget.org

Cause seems to be the following in the .csproj:

```
<Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
        <ErrorText>This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('..\packages\Microsoft.Diagnostics.Tracing.EventSource.Redist.1.1.16-beta\build\portable-net45+win8+wpa81\Microsoft.Diagnostics.Tracing.EventSource.Redist.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\Microsoft.Diagnostics.Tracing.EventSource.Redist.1.1.16-beta\build\portable-net45+win8+wpa81\Microsoft.Diagnostics.Tracing.EventSource.Redist.targets'))" />
    <Error Condition="!Exists('..\packages\Microsoft.ApplicationInsights.0.14.3-build00177\build\portable-win81+wpa81\Microsoft.ApplicationInsights.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\Microsoft.ApplicationInsights.0.14.3-build00177\build\portable-win81+wpa81\Microsoft.ApplicationInsights.targets'))" />
</Target>
```

Commenting out this section & the related <Import> tags enables the projects to build & run so these packages are clearly not referenced in the code.

**Comment by JustinXinLiu** [comment]
This is just how the new project structure works.

The code repo is not supposed to store all the referencing packages. You will need to download them if they don't exist in your local drive.

This is normally an automatic process by the NPM. If it's not doing it, just go tick *Allow NuGet to download missing packages* in your VS settings.

**Comment by csnazell** [comment]
@JustinXinLiu 
I'd dispute the "new" bit of your comment gIven that none of the projects I've created in VS2015 that reference nuget packages replicate this structure.

I do in fact have Allow NuGet to download missing packages turned on and it isn't downloading these packages.

Referencing packages that aren't used, and add no material value to the project is not best practice.

**Comment by JustinXinLiu** [comment]
That's because the name of *packages.config* is changed to *project.json*. But it's doing the same thing...

**Comment by csnazell** [comment]
@JustinXinLiu 
The current IDE & tool chain doesn't even attempt to process packages.config, even with the indicated options checked. In fact deleting this file from the sample has no effect on the build process. The NuGet tooling is actually looking at the project.json file included in the sample although not referenced in the project. Comparison of the contents of the two files reveals they're referencing different dependencies. So I don't understand how it's at all relevant to getting this sample to build in a clean environment.

I appreciate you are trying to be helpful but to be clear, I did get everything to build as indicated in the first line of the issue description.

**Comment by robmikh** [comment]
Interesting. So it seems if you just download/clone the repo and attempt to build normally then everything works fine. However, if you clean first and then attempt a rebuild as you mentioned in your steps this is where the issue repros. I'm not sure why this makes a difference for the application insights and diagnostic packages (manually installing the packages also doesn't resolve the issue, as it is looking for a specific version that doesn't seem to be on NuGet). 

This is one of our oldest samples, and I'm not sure if it was created by a prerelease version of VS2015. That might explain some of the strange behavior, however. I'll try replacing it with a newly generated project and see if this fixes things. Thanks for bringing this to our attention.

**Comment by pgills** [comment]
Closing. We've moved the CompositionVisual sample [here](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/CompositionVisual). If you are seeing issues with building samples continue to let us know. Thanks!
