### ISSUE TITLE
Does light work on the backside on objects?

### ISSUE THREAD

**Issue by pekspro** [Microsoft/WindowsUIDevLabs#263]
If I rotate an object around the X or Y-axis it seems to me that only one side is affected by the light source. It could look like this:

![image](https://user-images.githubusercontent.com/3163293/32978975-d5cc3d3c-cc4c-11e7-93fe-01ab9b807b9e.png)

This seems to be true for DistantLight, PointLight and SpotLight. AmbientLight works on both sides. I’m doing something wrong?

Here is some sample code:

            var compositor = ElementCompositionPreview.GetElementVisual(this).Compositor;
            var rootVisual = compositor.CreateContainerVisual();

            ElementCompositionPreview.SetElementChildVisual(this, rootVisual);

            var distantLight = compositor.CreateDistantLight();
            distantLight.Color = Colors.White;
            distantLight.Direction = new Vector3(0, 0, -1);
            distantLight.CoordinateSpace = rootVisual;
            distantLight.Targets.Add(rootVisual);

            //var pointLight = compositor.CreatePointLight();
            //pointLight.Color = Colors.White;
            //pointLight.Offset = new Vector3(100, 100, 1000);
            //pointLight.CoordinateSpace = rootVisual;
            //pointLight.Targets.Add(rootVisual);

            //var spotLight = compositor.CreateSpotLight();
            //spotLight.InnerConeAngleInDegrees = 30;
            //spotLight.InnerConeColor = Colors.Red;
            //spotLight.OuterConeAngleInDegrees = 60;
            //spotLight.OuterConeColor = Colors.Yellow;
            //spotLight.Offset = new Vector3(100, 100, 30);
            //spotLight.CoordinateSpace = rootVisual;
            //spotLight.Targets.Add(rootVisual);

            //var ambientLight = compositor.CreateAmbientLight();
            //ambientLight.Color = Colors.White;
            //ambientLight.Targets.Add(rootVisual);

            // Setup a square.
            var childVisual = compositor.CreateSpriteVisual();
            childVisual.Brush = compositor.CreateColorBrush(Color.FromArgb(255, 200, 100, 50));
            childVisual.Size = new Vector2(100, 100);
            childVisual.AnchorPoint = new Vector2(0.5f, 0.5f);
            childVisual.Offset = new Vector3(100, 100, 0);
            childVisual.BackfaceVisibility = CompositionBackfaceVisibility.Visible;
            childVisual.RotationAxis = Vector3.UnitX;
            rootVisual.Children.InsertAtTop(childVisual);

            //When rotated 180 degrees, the object will be black.
            childVisual.RotationAngleInDegrees = 0;
            //childVisual.RotationAngleInDegrees = 180;

**Comment by JohnnyWestlake** [comment]
Not that I've tried, but have you tried placing a light source *under* the object pointing upwards to light the backside? (Negative z offset with positive z direction?)

Whilst the rotations make it *look* like it's 3D - it's still essentially 2D UI system that's just "imitating" a 3D existence in essence so there are a rare few odd quirks like this.

**Comment by pekspro** [comment]
I change the direction to (0, 0, 1) in my sample the square will be black with no rotation, and looks like this when rotated 180 degrees:

![image](https://user-images.githubusercontent.com/3163293/33036835-ebce5ce8-ce2f-11e7-845d-5536a0deb5d1.png)

It’s has color but is darker!

I’m liking the 3D effects you could do, would love to see more support :-). I’m using it to build some basic games to an education application.

**Comment by krenner** [comment]
Hello pekspro – Glad to see you’re experimenting with our lighting API’s. Our current lighting design doesn’t support lighting the backside of a visual.  Depending on what you wish to achieve, you could potentially work around this by creating another copy of the visual and lighting accordingly.  I’ll add support for two sided lighting to our backlog for future consideration.
A side note - I did notice your sample has three of its four lights commented out.  We do restrict the number of lights that can target a visual.  A visual can only be targeted by two non-ambient lights (PointLight, SpotLight or DistantLight).

**Comment by pekspro** [comment]
Thanks for the suggestion @krenner. I ended up with only ambient light, I decided that was good enough for my application :-)

(If you curious, I have used the visual layer to create some basic games in this application: 
https://www.microsoft.com/store/apps/9WZDNCRDCH0J)

**Comment by krenner** [comment]
Thanks for letting us know @pekspro. I am going to close this issue.  Also, thanks for link to your app.  We are always curious to see how applications are using our features.  I'll download your application and check out the games.
