### ISSUE TITLE
Strange Issues in Release Native Build

### ISSUE THREAD

**Issue by SeriousGeorge** [Microsoft/WindowsUIDevLabs#264]
Hi there,

I'm currently trying to get my app into the store. And all out of a sudden I'm getting odd crashes in Release Build, targeting x86/x64 with Native tool chain.

**What am I doing?**
Get Visuals from XAML UI Elements and trying to animate them.
And amongst other things I'm preparing new animations with:

```
animation.IterationCount = loopCount;
animation.IterationBehavior = AnimationIterationBehavior.Count;
animation.StopBehavior = AnimationStopBehavior.LeaveCurrentValue;
```

**Without exception-settings enabled and not catching the exception, it's saying**
```
"The application is in break mode"
and showing error message in a popup:
"Unhandled exception at 0x09933C9A (Windows.UI.Xaml.dll) "
```

**With exception-settings enabled:**
```
Exception thrown: '<unknown>' in Microsoft.CSharp.dll

'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in System.Linq.Expressions.dll
'Windows.UI.Composition.ScalarKeyFrameAnimation' does not contain a definition for 'IterationCount'

Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: ''Windows.UI.Composition.Vector2KeyFrameAnimation' does not contain a definition for 'IterationCount''
```

But that's only in Release & Native Build. Debug and Release without native is running fine.
Same errors above shown up for "IterationBehavior" by the way.

I tried to add "< Namespace Name="Windows.UI.Xaml" MarshalObject="Required All" /> to the "default.rd.xml" file but to no avail.

My only workaround so far would be to get the animations done in the classic way - wich I want to avoid.

**Technical infos:**
Windows 10 UWP (non mobile) Targeting Creators Fall Update 16299
VisualStudio 2017 15.4.4
Windwos 10 64bit Professional (Creators Update) running

**Edit**
If I'm commenting out the lines addressing IterationCount,IterationBehaviour and StopBehaviour the .net native release build is fine. But what if I specifically need this parameters?

**Comment by scott-moore-ms** [comment]
Hi - it's possible that this is a bug with .NET Native.  Could you  please follow the instructions at https://github.com/dotnet/core/blob/master/Documentation/ilcRepro.md and send the resulting ilcrepro file to dotnetnative@microsoft.com?

Thanks!

**Comment by scott-moore-ms** [comment]
In addition to the above, you could try to work around this by adding the following to your default.rd.xml file:
<Type Name="Windows.UI.Composition.KeyFrameAnimation" MarshalObject="Required All" Dynamic="Required All" />

**Comment by SeriousGeorge** [comment]
Hi scott,

great. Adding the "KeyFrameAnimation" line to default.rd.xml worked.
I also just sent two links to ilcRepros at the email you mentioned above. 

One repro for the crashing solution and if you'll need it for comparision one ilcRepro for working solution with your provided workaround.

Thanks a lot!

**Comment by SeriousGeorge** [comment]
Hi Michal,

oh, that's very interesting. Thanks for the link. Went straight into my development resources/links-collection ;)

Thank you.

**Comment by daneuber** [comment]
Thanks for the discussion everyone, it looks like this is resolved. Closing but feel free to reopen if you are still encountering issues.
