### ISSUE TITLE
Strange scaled rendering with LoadedImageSurface

### ISSUE THREAD

**Issue by JohnnyWestlake** [Microsoft/WindowsUIDevLabs#265]
Hi, 

So I'm creating a XAMLCompositionBrush that tiles images, and I've noticed a curious quirk when using LoadedImageSurface that I'm not sure should actually be there when the visual has some sort of XAML scaling applied too it.

![LoadedImageSurface renders incorrectly when loaded without a size with scaling applied too it. (rounding error?)](https://user-images.githubusercontent.com/2319473/33174870-adb625ca-d051-11e7-836b-11b6d944eeb2.png)

See sample project: On the Left is loading the CompositionSurface using LoadedImageSurface, on the right is a more manual method (using Rob M's SurfaceLoader for brevity). The issue becomes apparent when you resize the Window to smaller sizes - the right hand side stays perfectly fine whilst the left seems to make obvious where the tiling occurs.

You'll see from the sample project literally everything is the same between the two brushes apart from a single line of creating the SurfaceBrush. 

As I'd rather use LoadedImageSurface (it handles more failure cases automatically than SurfaceLoader?), is there a work around for this or a known issue?

Sample here:
https://github.com/JohnnyWestlake/LoadedImageSourceBug

(OS Build: 16299.64, 16299 SDK)

**Comment by sohchatt** [comment]
This appears to be an issue with LoadedImageSurface; thanks for bringing it to our attention. 

In the meanwhile, you can workaround this problem by passing in an explicit size for your surface, say 100,100 for your image. So, something like this:
``
LoadedImageSurface.StartLoadFromUri(this.ImageUri, new Windows.Foundation.Size(100, 100));
``

Do let us know if this works for you.

**Comment by sohchatt** [comment]
@JohnnyWestlake this bug has been fixed in Insider builds. Do let us know if your problem still persists.
