### ISSUE TITLE
Ink RightDragAction not working (not even in the sample app)

### ISSUE THREAD

**Issue by Sergio0694** [Microsoft/WindowsUIDevLabs#267]
Hello,
I just noticed that the `InkInputProcessingConfiguration.RightDragAction` property isn't working anymore, not even in the sample app and not even after setting the target/minimum SDK of the sample app all the way back to the Anniversary Update (even though I could swear I've actually seen that API working just fine with the Creators Update).

## What I'm trying to do
Following [**the official sample**](https://docs.microsoft.com/en-us/uwp/api/windows.ui.input.inking.inkinputprocessingconfiguration#Windows_UI_Input_Inking_InkInputProcessingConfiguration_RightDragAction) , I'm setting the `RightDragAction` to `InkInputRightDragAction.LeaveUnprocessed` in order to be able to manually process the strokes when _dragging with the **right** mouse button_.

## What should happen
The `UnprocessedInput.PointerPressed` event (and the other ones too) should be raised whenever I press/drag/release the right mouse button.

## What is actually happening
Those events are not raised _at all_ when using the right button, not even in the sample app.
They are instead raised when I use the mouse left button, so not only do they not work as expected when using the right button, but they're also overriding the expected behavior of the mouse left button after setting that property.

## How to reproduce the issue
Open the [SimpleInk ](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/SimpleInk) sample project, open the "Scenario2" page and then click the lazo button.
At this point, try to drag with the **right** mouse button and observe that nothing is happening.
Try to drag with the **left** button and notice that the `UnprocessedInput` events are being raised, even if the left button is used, and that no ink stroke is being drawn.

Thank you in advance for your help!

**Comment by Sergio0694** [comment]
@msftdavid Hello David, any news about this issue?
I was just wondering whether it will be addressed in RS4 or in a future W10 release.
Thanks! 😄

**Comment by likuba** [comment]
Hi @Sergio0694 
Thanks for reporting this issue!  We did file a bug internally and it is in the backlog to be fixed by the inking team.  We'll make sure to give you an update when one is available.

**Comment by Sergio0694** [comment]
Hi @likuba - thank you for the follow up, looking forward to some good news!
Cheers!

**Comment by likuba** [comment]
This issue should be fixed in recent insider builds and the final SDK for this release.  Please reactivate if you are still seeing this issue.

Thanks!
