### ISSUE TITLE
InteractionTracker issues in build 17040

### ISSUE THREAD

**Issue by JustinXinLiu** [Microsoft/WindowsUIDevLabs#270]
Just want to let you know that there's something wrong with `InteractionTracker` in the insider build _17040_.

Our app has lost the _overpan_ visual when I try panning and moving the object (that implements `InteractionTracker`) around.

Also, if you run the sample app and go to the **Swipe Scroller** page, you will notice the vertical swipe gesture is not working 100% (try swiping down on any card), and it's not smooth too. However it's working perfectly fine in FCU.

**Comment by likuba** [comment]
Hey @JustinXinLiu -- Are you still seeing these issues in the latest builds?

**Comment by JustinXinLiu** [comment]
Looks like it's fixed in the latest insider build. Thanks @likuba !
