### ISSUE TITLE
Pause and resume workaround causing problems

### ISSUE THREAD

**Issue by SeriousGeorge** [Microsoft/WindowsUIDevLabs#271]
Hi there,

on behalf of my former issue: https://github.com/Microsoft/WindowsUIDevLabs/issues/169
I wrote there, to maybe reopen this issue - but I think it has been overlooked.

So I'm writing here...

Meanwhile I switched my whole animation code from storyboards to ScalarKeyFrameAnimations.
I implemented pause/resume as suggested in the other thread. As long as this basically works (setting up the animations as templates and reuse them, combined with the startingValue Property) it has some pitfalls I think.

**a.)** If paused and resumed the animation would play wirh the initial duration again, adding up to the total duration.

For example... if having an animation with duration 10 seconds, pausing at 9 seconds and then resuming, it would resume with the correct animation properties, but adding again 10 secodns, resulting in 19s.

**b.)** There is - at least I seen none - no way to get the current duration or playhead position so to speak.
If there is such a method to extract the current time of the animation, we could at least store that as a workaround to resume at the correct time again.

This is a big problem to me, as I'm trying to make an offscreen renderer with win2d combined with UI-Composition to render UI-Animations as Imagesequences to a video (thus pausing frame by frame). Plus since my current app in the store is a Slideshowapp, pausing is not working as expected.

Again I would strongly vote for a built-in pause/resume interface and options maybe like AnimationPauseBehaviour etc. Yes - and I already created a userVoice entry ;)

**Comment by likuba** [comment]
Hi @SeriousGeorge 

Sorry that workaround ended up having issues...are you open to using newer/insider builds?  If so, there's a new AnimationController feature that you should be able to try out that provides this functionality :) 

Give something like this a try:
```
                _visual.StartAnimation(nameof(Visual.Offset), _animation);
                var controller = _visual.TryGetAnimationController(nameof(Visual.Offset));
```

Then, you should have access to the functions you are looking for, such as Pause/Resume.  There will be a sample for this coming in the pipeline as well, but it's not quite ready yet.  Please note that as with anything on insider builds there will be some bugs that we're still working through, but feedback is always appreciated!

**Comment by SeriousGeorge** [comment]
Hi @likuba ,

aaah.. that's great news indeed. Much appreciated! Sounds very good.
I just recently dropped out of insider builds, as completing my app for store-submission and I keep it that way for the moment since I'm building regulary successive productive updates for my app. (remark to self: find time to setup experimental insider machine ;) )

For the time being I currently implemented an internal timer for all of my animated objects which will keep track of the current timeIndex, stop-, start- and deltaTime. Which will work fine for the next update (thus being able to produce frame by frame offscreen buffer rendering for producing videos along with win2d).

I gladly adopt to the new controller functions if they hit the non-insider builds.

Thank you very much for the heads up and integrating this functionionality into the composition API!

Best regards

**Comment by likuba** [comment]
Great!  Feel free to reach out with feedback once you're able to try it out.  And thanks for the feedback :)
