### ISSUE TITLE
Host BackdropBrush glitch under TitleBar area (happens in Groove too)

### ISSUE THREAD

**Issue by Sergio0694** [Microsoft/WindowsUIDevLabs#273]
## Issue Type
[X] Bug Report 
[ ] Feature Request 
[ ] Sample request  
[ ] Documentation issue or request  
[ ] Other – Please describe:   

## Current Behavior
Hello, this bug has been around for a while now (I've noticed it since the Creators Update, but it's possible it has been there since the `CompositionBackdropBrush` APIs have been introduced back in earlier W10 releases as well (maybe since the Anniversary Update).
The problem is that when using a `CompositionBackdropBrush` (I've only noticed this glitch when the brush is sampling from the desktop, so when using `Window.Current.Compositor.CreateHostBackdropBrush`) in an application, **if** the brush is applied to an area that is **behind** the TitleBar area, with the TitleBar itself that's hidden (using the `ExtendViewIntoTitleBar` property), the brush has a grey overlay in the area where the TitleBar would have been. I understand it's not a 100% clear explanation, so here's a screen:

![image](https://user-images.githubusercontent.com/10199417/35865511-0012cbaa-0b55-11e8-965b-95e309b9cd49.png)

**NOTES:**

- No, the gray effect you see there is *not* caused by the gray header at the top of the app UI, as the composition brush is *not* sampling from the app UI, but from the desktop.
- This same exact issue can be seen in the official Groove app as well, I've noticed it right after the latest update (when they updated the UI and made the app UI go under the TitleBar)

I couldn't make a screenshot from Groove (unfortunately I couldn't reproduce the glitch there after the first time it happened), but it looked something like this (it is slightly exaggerated here):

![image](https://user-images.githubusercontent.com/10199417/35865688-7458142a-0b55-11e8-9370-aad115a9a627.png)

- This issue happens both with custom acrylic brushes (like the one I use in OneLocker, see [here](https://github.com/Sergio0694/UICompositionAnimations/blob/master/UICompositionAnimations/Brushes/CustomAcrylicBrush.cs) the source code for that one), and with the official acrylic brush that I assume is being used in the Groove app
- As for the screen with my app, I'm using the Dark theme there, but I've heard from other devs that the same issue happens when using the Light theme as well
- I've had feedbacks from other devs that can confirm they've seen this same issue as well, on different apps and PCs

## Expected Behavior
The host backdrop acrylic brush (and the actual `CompositionBackdropBrush` brush) should not present these kind of glitches when displayed over (or behind actually) the TitleBar area.

## Steps to Reproduce (for bugs)
Either install the latest Groove version and look at the top left TitleBar area, or create an empty app with an acrylic brush, expand the UI into the TitleBar and look at the blur effect right under the TitleBar area.

**NOTE:** for some reason it looks like this bug most of the times is only visible at the first startup of aa given app, while the same APIs work fine after that. As an example: I've noticed this glitch in Groove right after updating it, but after that it worked fine. Same with my app (OneLocker): I've deployed it from VisualStudio, opened it, noticed the glitch, closed and reopened it and the brush was working fine.

##  Your Environment
* SDK 16299 (and earlier SDK versions)
* Operating System build W10 build 16299 (but the same bug has been present in earlier versions too) 
* Visual Studio Version 2017 Enterprise 15.5.5

**Comment by krenner** [comment]
Hi Sergio0694 - Thanks for the detailed write up.  I am happy to report this bug has been addressed and should be resolved in subsequent insider builds.

**Comment by Sergio0694** [comment]
@krenner Hello, thank you for your answer, glad to hear it's already been fixed! 😄
And wow, that was fast, were you already aware of this issue or was it just really easy/quick to fix?

I'm looking forward to the next RS4 builds then, thanks again!

**Comment by krenner** [comment]
This was a known bug.  The details you provided in your post made it easy for us to make the connection.  The fix should be current insider builds now so I am going to mark this issue as closed.  Please let us know if you see any more problems.
