### ISSUE TITLE
using Spring Animation with Translation back to (0,0,0)

### ISSUE THREAD

**Issue by jasonwurzel** [Microsoft/WindowsUIDevLabs#274]
## Issue Type
[ x ] Bug Report 
[ ] Feature Request
[ ] Sample request  
[ ] Documentation issue or request  
[ ] Other – Please describe:   

## Current Behavior
I'm trying to use SpringVector3NaturalMotionAnimation for animating a button on and off the screen, depending on some state. Using the "Translation" property it works if I animate from Translation (-1,0,0) to Translation (300, 0, 0) and back again to Translation (-1,0,0) using the SpringVector3NaturalMotionAnimation. But if I use (0,0,0) it does not work, as if it is ignored.

## Expected Behavior
When using the Vector3 (0,0,0) I would expect the Visual returns to it's original position

## Steps to Reproduce (for bugs)
here's a little sample app I wrote for reproduction:
 https://github.com/jasonwurzel/SpringyTranslation 

* When starting up, press the "Move Left to -300" Button => the Button slides to the left
* press the "Move Right to -1" Button => the Button slides to the right
* press "Move Left to -300" again
* now press "Move Right to 0" => the Button doesn't move

**Comment by likuba** [comment]
Hi @jasonwurzel 

Are you still seeing this issue on recent builds?  We are unable to repro on the latest.

Thanks!

**Comment by jasonwurzel** [comment]
Hi, 
jep, seems like the issue is gone! Thanks a lot.
