### ISSUE TITLE
PointLight as XamlLight disappears forever after using XAML CompositeTransform3D

### ISSUE THREAD

**Issue by JohnnyWestlake** [Microsoft/WindowsUIDevLabs#278]
## Issue Type
[x] Bug Report 

## Current Behavior
When applying a PointLight as a XAML light, after animating the UIElement using a CompositeTransform3D the  point light disappears, and no combination of magic seems to allow it to return. (I.E. removing the transform, re-creating the light, etc)

(My actual usage uses an animated PointLight as part of a focus visual effect on an Xbox One UWP app, and CompositeTransform3D animations are used as part of page / content transitions)

## Steps to Reproduce (for bugs)
Demo project here : https://github.com/JohnnyWestlake/Transform3DLightBug
Repro steps in the Readme.

##  Your Environment

* SDK #:  16299
* Operating System build # :  Fall Creators Update (16299.251)
* Visual Studio Version # : Vs 15.7 Preview 2

**Comment by JohnnyWestlake** [comment]
I will add the it somewhat works if I don't set a PerspectiveTransform3D on the root container but instead use a perspective TransformMatrix on it's Visual.

Replacing lines 86-100 of MainPage.xaml.cs with this will enable it to work, but it's more complex than using PerspectiveTransform3D (which I'd assume should be doing a pretty similar thing underneath, especially considering setting the Visual TransformMatrix allows the CompositeTransform3D's to work). 

```
       // Creates a basic 4x4 Matrix for use in perspective matrix multiplication
       // Using same default depth as PerspectiveTransform3D - 1000d
        static string PERSPECTIVE_BASE_MATRIX { get; } =
            $"Matrix4x4(1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, -1.0f / 1000f, 0.0f, 0.0f, 0.0f, 1.0f)";

        static string PERSPECTIVE_MATRIX { get; } =
            $"Matrix4x4.CreateTranslation(-this.Target.Size.X /2f, -this.Target.Size.Y /2f, 0f) " +
            $"* {PERSPECTIVE_BASE_MATRIX} " +
            $"* Matrix4x4.CreateTranslation(this.Target.Size.X /2f, this.Target.Size.Y /2f, 0f)";

        public static ExpressionAnimation CreatePerspectiveAnimation(Visual visual)
        {
            return visual.Compositor.CreateExpressionAnimation()
                .SetExpression(PERSPECTIVE_MATRIX)
                .SetTarget(nameof(Visual.TransformMatrix));
        }

        public Storyboard CreateDepth3DIn(
            IEnumerable<FrameworkElement> items,
            FrameworkElement container = null,
            double startDepth = -300,
            TimeSpan? customStagger = null,
            TimeSpan? customOpacityDuration = null,
            TimeSpan? customElementDuration = null,
            EasingFunctionBase customEase = null)
        {
            // 0. Prepare ourselves a nice list of visible framework elements to animate
            var _items = items.ToList();

            // 1. Ensure perspective transform on the target parent to allow depth animations
            //    to work
            //container?.GetPerspectiveTransform3D(); // <-- this guy is dead.
            if (container != null)
            {
                var v = container.GetVisual();
                v.StartAnimation(CreatePerspectiveAnimation(v));
            }
```

**Comment by daneuber** [comment]
Hi @JohnnyWestlake thanks for bringing this up. We've tracked this internally and a fix should be available in upcoming insider builds soon.

**Comment by daneuber** [comment]
@JohnnyWestlake Thanks for your patience. This should be fixed on insider flights available now. Please re-open if you still are able to repro this issue.
