### ISSUE TITLE
UWP Acrylic background does not work correctly when App started in Full Screen

### ISSUE THREAD

**Issue by TonyHenrique** [Microsoft/WindowsUIDevLabs#281]
UWP Acrylic background does not work correctly when App started in Full Screen:

https://aka.ms/O68719

See repro Project code:

https://github.com/TonyHenrique/UWPFullScreenAcrylicApp/

**Comment by YuliKl** [comment]
@TonyHenrique, thank you for your feedback. Acrylic is actually working as designed. Full screen mode is intended to immerse the user in the currently-running app. Therefore, allowing elements from outside the full screen app to be visible through background acrylic may break the immersion and potentially provide unwanted distractions. To best serve user focus, we’ve set background acrylic to automatically fall back to a solid color with no transparency.
