### ISSUE TITLE
ContextMenu background broken in build 17133 (RTM)

### ISSUE THREAD

**Issue by Sergio0694** [Microsoft/WindowsUIDevLabs#283]
## Issue Type

[X] Bug Report   
[ ] Feature Request   
[ ] Sample request  
[ ] Documentation issue or request  
[ ] Other – Please describe:   

## Current Behavior
The OS, starting from the upcoming Spring Creators Update, seems to render a black background behind every context menu, a fraction of a second after the context menu animation has finished. This effectively broke all the context menus in my apps, which are currently targeting the Fall Creators Update.

Here's a GIF that shows the issue:

![context_menu_glitched](https://user-images.githubusercontent.com/10199417/38453463-90dc1d5a-3a56-11e8-8f09-07e1b36a38ac.gif)

A few notes:

- You would **_only ever notice_** this issue with a context menu that has either a transparent background, or some margins. I guess that's why not many other users have reported this yet, since the majority of the apps just stick with the default context menu presenter style.
- I'm using a custom context menu, which has both an in-app acrylic effect (my own implementation, not the built-in acrylic) and a drop shadow at the edges of the context menu. As soon as the second context menu is opened in the GIF, you can see that the black background causes both the acrylic effect to lose the transparency (as there's black behind the menu), and the three edges of the control to appear black. That's because in order to leave space for the drop shadows, I've added some margins at those edges, which now just get filled with that black background too.
- You can see this happens both when the context menu is directly inside the app, and outside as well.

Here's a static screen with the issue: [context_menu_glitched](https://user-images.githubusercontent.com/10199417/38453505-269580fc-3a57-11e8-9c41-a0d91d3840eb.png)

## Expected Behavior
The context menu should be working just like it used to, and that black background should **_not_** be applied by the OS, **_especially_** if I'm using a custom context menu style, as this way the result is just to break my existing implementation (which took me quite some time to do actually, since the context menu UI is not the most intuitive control in the framework to work with, as it's partially managed by the OS directly).

Here's a GIF of the context menu working correctly, with my own effects, when running W10 FCU (ignore the wrong mouse cursor position, that's the screen recording tool).

![context_menu_ok](https://user-images.githubusercontent.com/10199417/38453540-81348080-3a57-11e8-999e-942d26efa26d.gif)

And here's a static screen of the context menu correctly rendered: [context_menu_ok](https://user-images.githubusercontent.com/10199417/38453544-968fc8c2-3a57-11e8-80d5-96441189c60b.png)

## Steps to Reproduce (for bugs)
1.  Create a new UWP app
2.  Create a copy of the default context menu presenter XAML Style, change the background so that it's transparent
3.  Observe that right when the context menu animation finishes, a black background is placed behind the context menu

Or, try to use an in-app acrylic effect as the context menu background, should have the same result. Or, apply some margin to the left, bottom and right margins of the context menu presenter, and notice how those areas become black like in the GIF before.

If you can't reproduce that, I could work on a smaller repro, just ask if you need that and I'll be happy to help.

##  Your Environment

* SDK 16299
* Operating System build 16299 (working), 17133.1 (glitched)
* Visual Studio Version 15.6.4

**NOTE**: I do hope this is just a bug, but since that black background kinda looks to be put there on purpose, if that's the case, didn't the official UWP guideline state that apps targeting previous SDKs were _guaranteed_ to keep working the same on future builds, as every compiled app was more or less "self contained" and independent from the current OS version used by the user?

Thank you in advance for your help!
Sergio

**Comment by daneuber** [comment]
Hi @Sergio0694 thanks for reaching out and the detailed walkthrough! We took a look at your repro & steps and this fix is actually by design. Partially-transparent MenyFlyouts is not supported in Spring Creators Update and earlier versions of Windows, and a fix was done this last release to consistently prevent transparency.  Work is happening for the next version of Windows to support partial transparency via AcrylicBrush in HostBackdrop mode or via custom XamlCompositiionBrushBase subclasses using an effect with a Composition CreateHostBackdropBrush(), and you should be able to achieve your desired look and feel using one of those solutions soon. In the mean time I'm going to go ahead and resolve this Issue as by design, but please feel free to reach out with any other Issues or concerns.

**Comment by Sergio0694** [comment]
@daneuber Hello, thank you for your answer, but I'm not sure I understood exactly what you meant.
Specifically:
- Why are you saying the transparency is "not supported" in the April Update? It's still working perfectly fine (as can be seen by the GIF), it just gets blocked by that black background a few seconds after the menu is shown. I mean, this looks more that a workaround made on purpose to prevent devs from achieving that look, rather than a "not supported" feature, as again, you can see it working fine while the animation is still going.
- I'm probably missing something here, what you mean by "work is happening for the next version of Windows to support partial transparency via AcrylicBrush in HostBackdrop mode or via custom XamlCompositiionBrushBase subclasses"? We can already do that, in fact we've already been able to do that even with just the first Creators Update. In fact, my custom context menu has been using that custom transparenty (implemented with a custom Acrylic brush) from before the Fall Creators Update was released.
- Why don't you want devs to use the in-app acrylic mode, while being absolutely fine with the host backdrop mode? I mean, from a pure UI point of view, it just makes more sense to have the context menu to blur the actual _in app content_ behind it (to give the feel of a translucent surface), rather that showing the background _behind the whole app window_. Such a behavior just looks counter intuitive to me, in fact you can see all the official W10 apps (eg. contacts, photos etc..) using the in-app mode for their popups and overlays for the same reason (eg. the search suggestions dropdown in the photos app).

Just to be clear in case I got across in the wrong way, I'm just honestly curious in understanding the reasoning behind this, I don't want to sound like I'm arguing in any way.

Thank you again for your time! 😊

**Comment by jebishopms** [comment]
Full transparency in MenuFlyouts is not officially supported in any version. It may have been working previously in an undocumented way due to a bug but the April 2018 Update fixed this issue to ensure the background is always applied. The solid color background fill appears after a delay in order to allow time for any fade-in transition animations to complete and cannot be removed.  

  
RE: in-app vs. backdrop modes:  

As shown at the Build 2018 conference last week we will be releasing new default transparent acrylic styles for transient UI like MenuFlyout plus updated Fluent Design guidance for transparency in an upcoming release.  

That will also include improved official support for transparency in scenarios like this via AcrylicBrush or via a custom XamlCompositionBrushBase.

**Comment by ceee** [comment]
@jebishopms @daneuber  You say that transparency will be possible in an upcoming release, but what about the drop shadow the author used and demonstrated in the example?

Furthermore, **why** did you introduce this limitation? You just said that this fix was done by design, but that's no reason imho.

**Comment by Sergio0694** [comment]
Hello @daneuber and @jebishopms, I've installed the latest RS5 preview build along with the new preview SDK, and tried to see if the context menu issue had been fixed. Did a quick test by replacing the background in the `MenuFlyoutPresenter` with my own custom acrylic brush (I mean by building my own Composition/Win2D pipeline and not using the built-in `AcrylicBrush` class) and everything seems to be working fine again:

![image](https://user-images.githubusercontent.com/10199417/44936288-5fcecc80-ad74-11e8-9378-f3d2f73698f7.png)

Haven't reintroduced the drop shadow yet, but since it seems that black canvas that was added with the April Update was removed, that should work as well.

I'm still not entirely sure why that fix was added for a single W10 release (the April Update) and removed immediately after that, but it's fine by me 😄
My question is: do you plan on blocking the in-app transparency effect in the context menu again in the future, or can I trust that the framework won't break my custom implementation again in a future release?

I mean, just to avoid doing the work twice just for a single release again.
Thanks for your help, have a nice day! 😊

**Comment by jebishopms** [comment]
@Sergio0694 the solid color background fill should still appear for any windows/flyouts that directly set a transparent background.

However if you're using a [CoimpositionBackdropBrush](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Composition.CompositionBackdropBrush) then that is fully supported and we plan to keep supporting it.

**Comment by Sergio0694** [comment]
Hello @jebishopms - thanks for your reply, that's good to hear 😄
Yeah I'm using a backdrop brush in my pipeline, and I tried to reintroduce that dropshadow I was originally using around the popup, and apparently it's working fine too (the black canvas is no longer covering the transparent margins around the content presenter of the flyout):

![image](https://user-images.githubusercontent.com/10199417/45050803-86e21280-b082-11e8-9275-394931cb38c3.png)

I do have a couple of questions now, but purely out of curiosity as they're not an issue for me, given that my implementation is working now.
1) I basically reintroduced my original code that was working on 16299 and was broken on 17134. If the fix in 17134 (that broke my implementation) affected my menu flyouts, I assume that it was because my implementation was violating one of those undesired usages of the menu flyout APIs, right? Then why is it that the same code is working again in RS5? Did you partially change your mind and reverted that fix, or was that fix only temporary while working on the new UI?
2) Just as a test, I've actually tried to explicitly set "Transparent" as the background, but the black canvas is still not there. As I said, this doesn't concern me, but here's a screen in case it might help you guys.
![image](https://user-images.githubusercontent.com/10199417/45051415-51d6bf80-b084-11e8-89a4-1d39129b8a24.png)
3) This is just a general feedback/suggestion, but I've made a test using the built-in acrylic brush, and even after setting the tint opacity to just 0.01, the background is still barely visible:
![image](https://user-images.githubusercontent.com/10199417/45051489-821e5e00-b084-11e8-9f23-73da025ba9f5.png)
As I said, I'm using my own pipeline to build the acrylic effect (similar to the built in, but with support for animations on the various Win2D effects, and with a different noise texture), but many devs out there might not be familiar with Composition/Win2D APIs and might benefit from an easy API to set the default acrylic brush to be more transparent and/or with less blur. You might want to consider adding a blur property, and/or to allow the tint amount to be smaller in the future.

Again, I just figured I'd leave some feedbacks while I was at it, and everything I said was just out of genuine curiosity and interest into the various decisions the Windows UI team made here, nothing was meant to criticize your work at all 😊
Feel free to reply if you have some time, in the meantime you can close this issue as the problem is solved anyways.

Cheers!
