### ISSUE TITLE
Add DispatcherTimer As controler in toolbox

### ISSUE THREAD

**Issue by khoshroomahdi** [Microsoft/WindowsUIDevLabs#286]
## Issue Type

[ ] Bug Report   
[ ] Feature Request   
[ ] Sample request  
[ ] Documentation issue or request  
[ ] Other – Please describe:   

## Steps to Reproduce (for bugs)

1.  
2.  
3.  

##  Your Environment

* SDK #:  
* Operating System build # :  
* Visual Studio Version # :

**Comment by daneuber** [comment]
Hi @khoshroomahdi - Thanks for the feedback. This repo is more commonly used for questions and issues relating to developing Windows UI/using Windows.UI.Composition APIs. For UWP platform/toolbox _feature requests_ please create a uservoice entry [here](https://wpdev.uservoice.com/forums/110705-universal-windows-platform) instead so your feedback can be tracked for future updates. When creating the entry, please provide more details on the experience you are trying to accomplish so we can triage appropriately and other users can upvote if they feel the feature is also relevant to their needs.
