### ISSUE TITLE
Add PrinterControler As controler in toolbox

### ISSUE THREAD

**Issue by khoshroomahdi** [Microsoft/WindowsUIDevLabs#288]
## Issue Type

[ ] Bug Report   
[ ] Feature Request   
[ ] Sample request  
[ ] Documentation issue or request  
[ ] Other – Please describe:   

## Steps to Reproduce (for bugs)

1.  
2.  
3.  

##  Your Environment

* SDK #:  
* Operating System build # :  
* Visual Studio Version # :

**Comment by khoshroomahdi** [comment]
it should have multi property for example print preview. default page, page Range and so on

**Comment by daneuber** [comment]
Hi @khoshroomahdi - Unfortunately I'll be closing out most of your issues in a similar manner, but I'm including the copy/paste text so you have the links and info on each issue. We do appreciate you filing these and hope you'll be able to file as uservoice entries with additional information.
This repo is more commonly used for questions and issues relating to developing Windows UI/using Windows.UI.Composition APIs. For UWP platform _feature requests_ please create a uservoice entry [here](https://wpdev.uservoice.com/forums/110705-universal-windows-platform) instead so your feedback can be tracked for future updates. When creating the entry, please provide more details on the experience you are trying to accomplish so we can triage appropriately and other users can upvote if they feel the feature is also relevant to their needs.
