### ISSUE TITLE
Suggestion: decide on an official stackoverflow tag, maybe "wincomposition"

### ISSUE THREAD

**Issue by tomzorz** [Microsoft/WindowsUIDevLabs#29]
The title says it all: it'd probably be better if people would use SO to ask random questions than github.

**Comment by assassin316** [comment]
I agree with **wincomposition**, that's was my first search term I entered on SO when I looked for win composition questions.

**Comment by JustinXinLiu** [comment]
But there's also the old Composition. :P How about *winrt-composition*?

**Comment by sernaj** [comment]
We've been considering  wincomposition, we're less worried about the old composition confusion.

**Comment by JustinXinLiu** [comment]
Let's use *win-composition* then!!

**Comment by tomzorz** [comment]
My vote is for "wincomposition" :+1:
