### ISSUE TITLE
Show Auto suggest Icon in visual studio when i use xaml

### ISSUE THREAD

**Issue by khoshroomahdi** [Microsoft/WindowsUIDevLabs#290]
## Issue Type

[ ] Bug Report   
[ ] Feature Request   
[ ] Sample request  
[ ] Documentation issue or request  
[ ] Other – Please describe:   

## Steps to Reproduce (for bugs)

1.  
2.  
3.  

##  Your Environment

* SDK #:  
* Operating System build # :  
* Visual Studio Version # :

**Comment by khoshroomahdi** [comment]
now I can't find with autocomplete I have to find the name of icon.

**Comment by daneuber** [comment]
Hi @khoshroomahdi - Thanks for the feedback. I've assigned a XAML rep to this issue as FYI but seeing as this is VS + XAML cross-cuting feature request we'd still prefer that you instead file a uservoice entry [here](https://wpdev.uservoice.com/forums/110705-universal-windows-platform) so this can be tracked as a feature request to consider for future updates.
