### ISSUE TITLE
Add stopWatch as controler in visual studio toolbox

### ISSUE THREAD

**Issue by khoshroomahdi** [Microsoft/WindowsUIDevLabs#292]
## Issue Type

[ ] Bug Report   
[ ] Feature Request   
[ ] Sample request  
[ ] Documentation issue or request  
[ ] Other – Please describe:   

## Steps to Reproduce (for bugs)

1.  
2.  
3.  

##  Your Environment

* SDK #:  
* Operating System build # :  
* Visual Studio Version # :

**Comment by jebishopms** [comment]
Hi @khoshroomahdi,

Thanks for the feedback. For UWP platform feature suggestions, could you instead please open an item in either the Windows 10 Feedback Hub or the UWP UserVoice feedback forum:
https://wpdev.uservoice.com/forums/110705-universal-windows-platform

If you do submit feedback or a suggestion through those channels, could you also provide more details on what you're trying to accomplish with a stopwatch?
