### ISSUE TITLE
ImplicitShowAnimation not working in a Virtual Machine

### ISSUE THREAD

**Issue by jmvillagra** [Microsoft/WindowsUIDevLabs#293]
## Issue Type
[X ] Bug Report   
[ ] Feature Request   
[ ] Sample request  
[ ] Documentation issue or request  
[ ] Other – Please describe:   

## Current Behavior
Hi, 
I was testing the new version of our app and I just realized that all the animations we set via ElementCompositionPreview.SetImplicitShowAnimation are not working in virtual machines, (maybe something related to the display driver used by the VM?)

The animations are pretty simple like for example this one
`
placeHolder.Visibility = Visibility.Collapsed;
var easyOut = _compositor.CreateCubicBezierEasingFunction(new Vector2(0.215f, 0.61f), new Vector2(0.355f, 1.0f));
ElementCompositionPreview.GetElementVisual(placeHolder).Opacity = 0;
showAnimation = _compositor.CreateScalarKeyFrameAnimation();
showAnimation.InsertKeyFrame(0.0f, 0.0f);
showAnimation.InsertKeyFrame(1.0f, 1.0f, easyOut);
showAnimation.Target = "Opacity";
showAnimation.DelayTime = TimeSpan.FromMilliseconds(100);
showAnimation.Duration = TimeSpan.FromSeconds(1);                                       

ElementCompositionPreview.SetImplicitShowAnimation(placeHolder, showAnimation);
`
So, if this animations don't run some elements stay hidden forever....

Is this really a bug or should we check if the machine supports it and not used them in that case?  How can check if we should use them or not? Is there some documentation about best practices on animations depending on machines / battery saving modes / etc?

Thank you.

## Expected Behavior
ImplicitShowAnimations should work everywhere.

##  Your Environment
* SDK #:  Target 1803 Min: 16299
* Operating System build # :  17134.48
* Visual Studio Version # : 15.7.3

**Comment by shandilvarun** [comment]
One thing you would want to check if animations are enabled on VM. By default VM settings don't allow animations. it should be settings --> Ease of Access --> Show Animations on Windows. see if this is checked. if not then check the check box and see if that solves your issue. 
Thanks!

**Comment by jmvillagra** [comment]
Yes, that was it. So, next question is how can we check that setting via Code to add or not animations?

**Comment by likuba** [comment]
That setting can be referenced using the property documented here:
https://docs.microsoft.com/en-us/uwp/api/windows.ui.viewmanagement.uisettings.animationsenabled

**Comment by jmvillagra** [comment]
Perfect, Thanks.
