### ISSUE TITLE
Slowly Scrolling GridView 

### ISSUE THREAD

**Issue by mscherotter** [Microsoft/WindowsUIDevLabs#35]
I am trying to understand how to slowly scroll a Xaml GridView but I don't really understand from the samples how to do that.  Should I use a keyframe animation or a something else?  The interaction that I want is that when the user isn't touching the GridView it scrolls slowly to the left but as soon as the user touches it, scrolling stops.  I get an ArgumentException at the last line.  what am I doing wrong?

    void StartAnimatingPictures()
    {
            var scrollViewer = GetScrollViewer(this.Pictures);

            if (scrollViewer == null)
            {
                return;
            }

            _compositor = ElementCompositionPreview.GetElementVisual(this).Compositor;
           
            _scrollProperties = ElementCompositionPreview.GetScrollViewerManipulationPropertySet(scrollViewer);

            var animation = _compositor.CreateScalarKeyFrameAnimation();

            animation.InsertExpressionKeyFrame(0.0f, "ScrollManipulation.Translation.X");
            animation.InsertKeyFrame(1.0f, -1000.0f);

            _scrollProperties.StartAnimation("ScrollManipulation", animation);
    }

**Comment by shandilvarun** [comment]
you need to set reference parameter. something like this 
 animation.SetReferenceParameter("ScrollManipulation", _scrollProperties);

see if this works. 

Thanks, 
Varun

**Comment by mscherotter** [comment]
Varun,
Thanks for the suggestion, but when I add that I still get an argument exception with StartAnimation:
"The specified property was not found or cannot be animated."

**Comment by juanpaexpedite** [comment]
I made a demo about scrolling in here : https://github.com/juanpaexpedite/MasterDetailsComposition/blob/master/ParallaxSplitView/Attached/Effects.cs take a look at the end.
 public class ParallaxEffectComposition : DependencyObject

Might be (I will learn when Composition team answers, they might be really really busy), you have to use the compositor of the ScrollViewer:

   ```
scrollerViewerManipulation = ElementCompositionPreview.GetScrollViewerManipulationPropertySet(scroller as ScrollViewer); 
    scrollerCompositor = scrollerViewerManipulation.Compositor; 
```

**Comment by tomzorz** [comment]
I don't think that you can currently animate the scroll position of a scrollviewer - what you get back is a property set (GetScrollViewerManipulationPropertySet) and not a visual. I think you can only animate properties on a visual at the moment.

**Comment by likuba** [comment]
tomzorz is correct--the property set returned from GetScrollViewerManipulationPropertySet does not allow you to animate its values--it is purely for referencing to coordinate other animations.  Unfortunately, at the moment I don't believe there is a platform solution for what you are trying to do.

**Comment by tomzorz** [comment]
@likuba Although it'd be cool if we could :) +feature-request?

**Comment by likuba** [comment]
@tomzorz noted :) and don't forget to stay tuned for build where you'll be able to see what we are adding this release!

**Comment by tomzorz** [comment]
@likuba Can't wait :+1:

**Comment by mikehenderlight** [comment]
You can always use ScrollViewer.ChangeView along with a DispatchTImer:

        public MainPage()
        {
            this.InitializeComponent();
            Loaded += MainPage_Loaded;
            timer.Interval = TimeSpan.FromMilliseconds(500);
            timer.Tick += Timer_Tick;
        }

        private void Timer_Tick(object sender, object e)
        {
            gridScrollViewer.ChangeView(null, gridScrollViewer.VerticalOffset + 5, null, false);
        }

        private void MainPage_Loaded(object sender, RoutedEventArgs e)
        {
            PopulateData();
            gridScrollViewer = GetChildElement<ScrollViewer>(GV1);
            gridScrollViewer.DirectManipulationStarted += GridScrollViewer_DirectManipulationStarted;
            timer.Start();
        }

        private void GridScrollViewer_DirectManipulationStarted(object sender, object e)
        {
            timer.Stop();
            gridScrollViewer.DirectManipulationCompleted += GridScrollViewer_DirectManipulationCompleted;
        }

        private void GridScrollViewer_DirectManipulationCompleted(object sender, object e)
        {
            gridScrollViewer.ManipulationCompleted -= GridScrollViewer_DirectManipulationCompleted;
            timer.Start();
        }
But it won't be very performant or smooth.
