### ISSUE TITLE
How to create a Cubic Ease ??

### ISSUE THREAD

**Issue by assassin316** [Microsoft/WindowsUIDevLabs#36]
I would like to create a Cubic "EaseIn", such as the one that exists in XAML (look in the link below in the Remarks section):

[https://msdn.microsoft.com/en-us/library/system.windows.media.animation.cubicease(v=vs.110).aspx](https://msdn.microsoft.com/en-us/library/system.windows.media.animation.cubicease(v=vs.110).aspx)

How do I do that using the Compositor.CreateCubicBezierEasingFunction()?? It takes two vectors, what values do I use for both Vectors?

**Comment by tomzorz** [comment]
The two vectors are the two control points for your cubic bézier function.

![bezier](https://cloud.githubusercontent.com/assets/6363312/14002820/aed3782e-f14e-11e5-9c40-fa8e66ab4b2f.png)

To exactly replicate the Cubic ease you'll need to do a little math. https://msdn.microsoft.com/en-us/library/system.windows.media.animation.cubicease%28v=vs.110%29.aspx the page says: "The formula used for this function is the following. **f(t) = t3**"

And also shows this helpful image:
 ![help](https://msdn.microsoft.com/dynimg/IC270156.jpeg)

This website comes in handy and does the calculation for you - just select "easeInCubic": https://matthewlein.com/ceaser/

This way you get what you want: vector1 is (0.55, 0.055) and vector2 is (0.675, 0.190).

**Comment by assassin316** [comment]
Great!!  Thanks so much!
