### ISSUE TITLE
New Composition API question regarding GetAlphaMask

### ISSUE THREAD

**Issue by tomzorz** [Microsoft/WindowsUIDevLabs#37]
Hi

So as the new insider builds are coming out I've seen a new method on the Windows.UI.Xaml.Shapes.Shape base class: CompositionBrush GetAlphaMask(). 

This is awesome, as one of my major pain points was that I couldn't use a Xaml element as a mask for a different one - now my question is: does the alpha mask compositionbrush stay up to date if I animate the shape?

This would make creating material design-like "shape fills up the screen" animations a breeze to do :)

Thanks,
Tamás

**Comment by jeffstall** [comment]
Hi Tamás ,

Yes, it automatically updates when the Xaml content has changed.

Also, depending on the complexity of your animations and content updates, it might be helpful to also remember that there are performance differences between Xaml’s dependent animations (which are executed in the application) from Xaml and Composition independent animations (which are executed in the system’s Composition Service, DWM.exe).

Thanks!
~ Jeffrey

**Comment by tomzorz** [comment]
Awesome, thanks! :) I'll wait with further questions until I see the presentation today (or tomorrow if there's no live stream).

**Comment by tomzorz** [comment]
Watched all the sessions and everything is clear on this for now - thanks! :)
