### ISSUE TITLE
Link to samples from msdn broken

### ISSUE THREAD

**Issue by ahimberg** [Microsoft/WindowsUIDevLabs#39]
msdn documentation at https://msdn.microsoft.com/en-us/windows/uwp/graphics/composition-effects has many links to https://github.com/Microsoft/composition/tree/master/SDK10240_WIN10_RTM/BasicCompositonEffects which no longer exist

**Comment by pgills** [comment]
Thanks for the catch. We've changed our repository code for BUILD and are currently updating our static links. 

If you find any more please let us know!

**Comment by pgills** [comment]
These have been updated on this MSDN page. Closing.
