### ISSUE TITLE
Implicit animations with GridView

### ISSUE THREAD

**Issue by JustinXinLiu** [Microsoft/WindowsUIDevLabs#40]
I cannot seem to get the same *implicit animations* to work on a `GridView`, which was demonstrated in quite a few Build talks. The build number of my Windows 10 is *14295*. 

The code is rather simple:
```
private void GridView_ContainerContentChanging(ListViewBase sender, ContainerContentChangingEventArgs args)
{
    var visual = ElementCompositionPreview.GetElementVisual(args.ItemContainer);

    var implicitAnimations = visual.Compositor.CreateImplicitAnimationMap();
    // CreateAnimationGroup simply returns an object of AnimationGroup
    implicitAnimations["Offset"] = CreateAnimationGroup();

    visual.ImplicitAnimations = implicitAnimations;
}
```

My understanding is, the animation needs to be **triggered** by the change of the `Offset` value of a `GridViewItem`, so the `GridView` control itself must have some built-in logic to update the `Offset` values of all its children. Maybe this feature is not supported in build *14295* yet?

**Comment by pgills** [comment]
@JustinXinLiu the `Offset` triggering integration unfortunately didn't make it into the 14295 build, but is tracking for a future flight. So thanks for continuing to be an Insider.

On the bright side, you can experiment with Implicit Animations on `Visuals` that you create and manage yourself - similar to the techniques shown in the [Implicit Animation](http://go.microsoft.com/fwlink/p/?LinkID=761163) sample we recently published. 

If you [retarget the Sample Gallery project](https://github.com/Microsoft/WindowsUIDevLabs/wiki/Sample-Gallery-SDK-Retargeting) you'll get a good idea of what is working with the 14295 build.

And we will be releasing more samples consistently, now that the BUILD conference is over.

**Comment by tomzorz** [comment]
@pgills On that note: could we get an updated list on what's (or what will be) supported in terms of xaml interop? (offset, hit testing, etc...)

**Comment by pgills** [comment]
@tomzorz - Yes, I'll work with the team to get something out on the changes from 10586 to 14295 for interop.

**Comment by JustinXinLiu** [comment]
@pgills would the `Offset` triggering integration work in other scenarios than the `GridView`? For exmple, I am using `AdaptiveTrigger` to create responsive UI and I'd like all the panels on the page to smoothly transition to new position, something visually similar to the `GridView` animation.

**Comment by pgills** [comment]
@JustinXinLiu I believe that should work in other contexts like `AdaptiveTriggers`. I'll follow up to double check. I can imagine wanting to change the `Orientation` of a `StackPanel` using `AdaptiveTriggers` and then watch the Children animate to their new positions.

**Comment by JustinXinLiu** [comment]
@pgills that'd be super awesome!!

**Comment by JasterAtMicrosoft** [comment]
Yes many situations where you are changing layout will "just work" with this new technique, including moving stuff around with `AdaptiveTrigger` and changing the orientation of a `StackPanel`.

**Comment by JustinXinLiu** [comment]
Just wow! Thanks @JasterAtMicrosoft! I am closing the issue now.
