### ISSUE TITLE
Where can i find the ConnectedAnimationService

### ISSUE THREAD

**Issue by Brian-Ding** [Microsoft/WindowsUIDevLabs#43]
in build 2016, [Creating Beautiful UX in a Real-World App with Visuals, Animations and Effects](https://channel9.msdn.com/Events/Build/2016/B818) James & Tim showed us how to make a connectedaimation

But i cant find the ConnectedAnimationService class under Windows.UI.Xaml.Media.Animation, any idea where it is located?

i have installed SDK 14295 with VS2015 update2

**Comment by shandilvarun** [comment]
It was not shipped as connectAnimations. It is shipped as StartAnimations()

**Comment by Brian-Ding** [comment]
@shandilvarun Please check out the video provide by the link, @33min, he coded "Windows.UI.Media.Animation.ConnectedAnimationService"

![image](https://cloud.githubusercontent.com/assets/11363173/14319250/0e046a52-fc43-11e5-9aed-9e58569cd380.png)

**Comment by shandilvarun** [comment]
Yes you are right, connectAnimations was in preview APIs but we finally shipped StartAnimations() you can find samples in the repo for usage of StartAnimations

**Comment by assassin316** [comment]
I have the same problem with GaussianBlurEffect, I can't create it even with the latest SDK installed.

**Comment by shandilvarun** [comment]
What ask number do you have?

**Comment by shandilvarun** [comment]
Sdk* thanks auto correct 😀

**Comment by Brian-Ding** [comment]
@shandilvarun StartAnimation() is for general animation starting, for all kinds of animations, like KeyFrameAnimation or Vector3KeyFrameAnimation, but you need to create a ConnectedAnimation to be started, right? so how to create a ConnectedAnimation instance? 

and I did checked the samples in this repo, here they have a [Continuity example](https://github.com/Microsoft/WindowsUIDevLabs/tree/master/SampleGallery/Samples/SDK%2010586/Continuity), but I cant find any "ConnectedAnimationService"

**Comment by assassin316** [comment]
I currently installed the SDK 10.0.14295.1000. Also have Update 2 on Windows 10 build 14295.

**Comment by assassin316** [comment]
What namespace is GaussianBlurEffect in? I'll try looking for it...

**Comment by Brian-Ding** [comment]
@assassin316 oh yeah, Microsoft did not update dev.windows.com to reflect the new API

What a TYPICAL way of Microsoft!!

**Comment by robmikh** [comment]
@assassin316 You can find the GaussianBlurEffect in the Microsoft.Graphics.Canvas.Effects namespace. Notice that you'll need Win2D included, as we take a dependency on them for the effect definitions.

@Brian-Ding I'll get back to you in a second. Battery is dying...

**Comment by shandilvarun** [comment]
Thanks @robmikh 
@Brian-Ding Apologies for the confusion above. ConnectedAnimationService is not yet available in current flights, but will be in future flights. In the mean time you can use the approach in Continuity sample. I will post an update on this thread once the API is available in a flight.
I also understand your concern on documentation and we are in process of updating dev.windows.com (https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.composition.aspx) to reflect new APIs and update existing documentation.

**Comment by shandilvarun** [comment]
@assassin316  Max, this talk deep dives into Effect https://channel9.msdn.com/Events/Build/2016/P490 
@Brian-Ding  this talk deep dives into connected Animations https://channel9.msdn.com/Events/Build/2016/P485

**Comment by robmikh** [comment]
Thanks @shandilvarun! 

@assassin316 You can look at a StackOverflow answer I wrote on how to use blur [here](http://stackoverflow.com/a/36441888).

**Comment by pgills** [comment]
Just to help clarify some points for folks.

@Brian-Ding `ConnectedAnimationService` unfortunately didn't make it for the 14295 build, but it is tracking for a future flight. API documentation for Insider flights is a known issue for us and we're working together to determine the best place for this type of information see Issue #25 where we're tracking it. We've had a lot of good suggestions from folks participating with us on this project.

@assassin316 As @robmikh points out, we use the same `Effect` descriptions as Win2D. In order to include them into your project, you must install the [Win2D Nuget Package](http://www.nuget.org/packages/Win2D.uwp/) and then you will be able to create `Effects` to be used with `Windows.UI.Composition`. If you read through the [Effect](http://microsoft.github.io/Win2D/html/N_Microsoft_Graphics_Canvas_Effects.htm) reference you will be able to know what descriptions that can only be used with Win2D and what descriptions can be used with both Win2D and Composition.

**Comment by assassin316** [comment]
@pgills  and @robmikh  Thanks guys for the clarification!! :)

**Comment by Brian-Ding** [comment]
@shandilvarun @robmikh @pgills Thank you guys for the help here. So i will try the work around Continuity Sample provided & wait for the ConnectedAimationService API then. Hope it wont take too long

**Comment by tomzorz** [comment]
@Brian-Ding  Maybe you could check if it's in the new 14316 build from yesterday :) (Although I guess you might need a new SDK for that to work?)

**Comment by pgills** [comment]
Closing this issue. We will let folks know when the ConnectAnimationService API makes it with an Insider flight.
