### ISSUE TITLE
SVGs native rendering

### ISSUE THREAD

**Issue by mjracca** [Microsoft/WindowsUIDevLabs#44]
SVG are key elements in our app. We use them for stickers (from Noun Project), and for large frameworks. Users can even drop their own SVGs to their murals.

Here is an example of a mural:
![image](https://cloud.githubusercontent.com/assets/3976257/14335961/4eb31898-fc14-11e5-92ae-5d6f59fc12d9.png)

Since we can't natively render SVG in XAML, we tried the next solutions:
- **Using WebViews**: This will render our SVG perfectly but the performance of the app drops significantly.
- **SvgForXaml:** This library didn't work for us since it fails to render many of our SVG files.
- **Pre-loaded .png files**: This works, but only if we don't resize the elements (which we need to), and if we don't support user SVGs (which we also need to)
- **WebView to .png**: This looked like promising but it failed to work for many reasons. First, you need to have the webview actually added to the xaml tree to make it work. Secondly, we can't seem to take a screenshot of a WebView that has transparent backgrounds. For this reason we had to take two screenshots and then figure out transparency to create another image. Third, it didn't consistently work.

Any thought? This is super important for us!

**Comment by robmikh** [comment]
You should be able to break down an SVG and use it as a Path within a Canvas. I've used this in apps in the past. For example, your SVG might contain the following (I grabbed an open domain airplane from the NounProject):

```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.0//EN" "http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd">
<svg version="1.0" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 97.239 100" enable-background="new 0 0 97.239 100" xml:space="preserve">
<path d="M42.732,5.521c0.01-7.396,11.138-7.396,11.151,0.207v30.956l43.355,26.108v11.412L54.091,60.032v23.137l9.953,7.814V100
	l-15.373-4.741L33.248,100v-9.017l9.9-7.814V60.032L0,74.205V62.792l42.732-26.108V5.521L42.732,5.521z">
</path></svg>
``` 

The `<path>` tag should be compatible with the Path object in XAML. Usually I'd do something like this:

```
<Viewbox Width="50" Height="50">
    <Canvas Width="97.239" Height="100">
        <Path Data="M42.732,5.521c0.01-7.396,11.138-7.396,
            11.151,0.207v30.956l43.355,26.108v11.412L54.091,
            60.032v23.137l9.953,7.814V100l-15.373-4.741L33.248,
            100v-9.017l9.9-7.814V60.032L0, 74.205V62.792l42.732-26.108V5.521L42.732,5.521z" 
            Fill="Black"/>
    </Canvas>
</Viewbox>
```
It should work even as you add complexity and additional paths. Have you explored using this technique? Wrapping this in a control that takes in an SVG file and parses it could also be pretty cool.

One alternative could also be to draw the content using Win2D into either a Win2D Canvas (a XAML control) or into a CompositionDrawingSurface (which you would then set to be the content of a Visual). However, that seems to be what SvgForXAML is doing, so you may want to let the developer know what you're seeing (or even contribute!). 

Ultimately you may find that doing it manually with DirectX and drawing into a CompositionDrawingSurface to be the most robust way. The Microsoft.UI.Toolkit code shows how to draw a surface that is useable by a Visual. You can find that [here](https://github.com/Microsoft/WindowsUIDevLabs/tree/master/Demos/SlideShow/Microsoft.UI.Composition.Toolkit).

**Comment by mjracca** [comment]
Thanks! We will definitely try out those options!

Side question: How would you recommend downloading the .svg file? In our test sometimes the file downloaded corrupted or with incorrect characters.

**Comment by robmikh** [comment]
That's strange. Usually something like this has worked fine for me:

```
private async Task<String> LoadSVG()
{
    String result = "";

    var picker = new FileOpenPicker();
    picker.ViewMode = PickerViewMode.Thumbnail;
    picker.SuggestedStartLocation = PickerLocationId.PicturesLibrary;
    picker.FileTypeFilter.Add(".svg");

    var file = await picker.PickSingleFileAsync();

    if (file != null)
    {
        result = await FileIO.ReadTextAsync(file);
    }

    return result;
}
```

**Comment by pgills** [comment]
Closing this issue, since there hasn't been any activity within the week.

**Comment by sohchatt** [comment]
@mjracca just letting you know that rendering .svg files is now natively supported in XAML in the Creators Update. See [SVGImageSource ](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.imaging.svgimagesource)for more details. Hope this helps!

**Comment by mjracca** [comment]
Amazing! thanks!
