### ISSUE TITLE
InkCanvas and UIElement's ManipulationModeCompleted not firing

### ISSUE THREAD

**Issue by mjracca** [Microsoft/WindowsUIDevLabs#45]
I'm working with a pannable and zoomable **ScrollViewer** which contains multiple elements you can move around and an **InkCanvas** on top where you can draw.

The issue that we are having is that, when manipulating an element and touching with another hand to the canvas or other element, sometimes **the manipultion events stops firing**, leaving the element in a weird state, where **you can't interact with it anymore**. _ManipulationStarted_ and _ManipulationCompleted_ are never called again, and sometimes _ManipulationDelta_ works.

Any idea? Which we found out it's that if we put the InkCanvas below all the elements, then it never breaks, but we need the InkCanvas to be on top of every element.

**We submited the example [here](https://github.com/mjracca/InkCanvasIssue)**. To reproduce, try to scale the element with two fingers, as fast as you can. You will notice that at some point the element will break.

**Also, you can watch a video of how we reproduced it [here](https://drive.google.com/file/d/0B1EvrbuVksALZVFJS0s0ZTBwdlE/view?usp=sharing)**. We broke the Whiteboard app for Surface Hub just moving an element and touching the canvas at the same time. After doing that, then we weren't able to move the elements any more.

**Comment by pgills** [comment]
@mjracca Thanks for the repo and video, these are super helpful for debugging.

What builds are you seeing this behavior on?

We'll get some folks on the team to take a look.

**Comment by mjracca** [comment]
I'm using the production build. I will install the preview OS and SDKs soon, but this happens to us since almost 1 year now.

We could also reproduce this bug in the OneNote app, which I think is the same as the Whiteboard app after all.

**Comment by likuba** [comment]
Thanks for the info!  I notice in the video you are showing this on a surface hub device.  Are you seeing this on other devices as well (such as a laptop), or only on the surface hub?

**Comment by mjracca** [comment]
Yes! We are having this issue on every device.

**Comment by likuba** [comment]
Hi @mjracca.

Thanks for letting us know about the issue!  I went ahead and filed a product bug and the team who owns this area has investigated.  Over the past year we have made some changes in this area and it sounds like the provided sample app no longer repros the issue on more recent builds.  For now I'm going to close this issue, but please let us know if you are seeing issues with your sample app after upgrading your build to the next version of Windows.

**Comment by mjracca** [comment]
Thanks @likuba! We tested this out in the Insider build, with the Anniversary Update and it finally works correctly :) :)

If this happen again in future build I'll let you know (since it already happened to us that some updates fixes the issue, and other didn't work)
