### ISSUE TITLE
Is there a Nav Pane Splitview template

### ISSUE THREAD

**Issue by AudioW** [Microsoft/WindowsUIDevLabs#47]
Hi,

at build there was a session on the new guidelines for the nav pane navigation pattern: https://channel9.msdn.com/Events/Build/2016/B842

Is there a template for this pattern available for download? Or is there a place with info on sizes, and instructions on how to make nav pane menu items look the way they should look?

**Comment by pgills** [comment]
@AudioW  You can find the [Navigation Menu](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/XamlNavigation) sample on the [Windows Universal Samples](https://github.com/Microsoft/Windows-universal-sample) repository. 

For UI and Design Guidance, like recommend the [Design and UI](https://developer.microsoft.com/en-us/windows/design) site. Specifically, you can look at the [Screen sizes and break points](https://msdn.microsoft.com/windows/uwp/layout/screen-sizes-and-breakpoints-for-responsive-design) page for some tips and tricks on sizing.

For established UX/UI patterns and practices I'd recommend looking for samples on the [Windows Universal Samples](https://github.com/Microsoft/Windows-universal-sample) repository there's lots of good established resources there. 

We are primarily focused on testing and experimenting with new UX patterns, getting early feedback on APIs, and working with developers developing on Insider builds. If you're interested in that I'd highly recommend becoming a Windows Insider.

Hope that helps!

**Comment by AudioW** [comment]
Hi

Thank you for your response. I saw all the samples but I am specifically looking for the one mentioned in the Build 2016 video. It looks different than the samples both in size and color.

**Comment by pgills** [comment]
I was unable to find the exact sample shown in the video, however you'll find some of the samples mentioned in the video here: https://developer.microsoft.com/en-us/windows/samples

Specifically, the PhotoSharing example: https://github.com/Microsoft/Appsample-Photosharing

**Comment by robmikh** [comment]
The main thing you'll want to look for is AppShell.xaml and its friends. The Photosharing sample that @pgills linked to and the [RssReader](https://github.com/Microsoft/Windows-appsample-rssreader) sample are great places to start. Just note that they also come with a lot of scaffolding to get them up and running, but I think it's worth it. Once it's up, there's much less tinkering whenever you want to add a new menu item/page.

**Comment by AudioW** [comment]
I made a ui on my own to mimic the shown functionality.
