### ISSUE TITLE
Dot and cross product in expressions

### ISSUE THREAD

**Issue by aL3891** [Microsoft/WindowsUIDevLabs#49]
Hello,
Looking at the reference for [ExpressionAnimation](https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.composition.expressionanimation.aspx) it doesn't look like dot and cross products are supported, is this correct or are the docs out of date?
If they are not available, please consider adding them, because they would be very useful.

**Comment by patsiu** [comment]
@aL3891 sorry we do not support cross/dot product operations for Vector types in Expressions right now. We're looking into other it along with other functions for the other types. If you have other function requests, feel free to pass them along!

**Comment by aL3891** [comment]
To be honest i just made the general observation when doing my expression tree based expressionanimation thing, but those functions would be very useful :)

**Comment by pgills** [comment]
Thanks for the feedback, I'm closing this issue, but it's been captured in the Feedback milestone.
