### ISSUE TITLE
TextBox doesn't render bold/italic when changing FontFamily

### ISSUE THREAD

**Issue by mjracca** [Microsoft/WindowsUIDevLabs#50]
We have an issue with **TextBox** where is doesn't render font formats like _FontStyle_ and _FontWeight_ when using a custom _FontFamily_. This works fine for TextBlock.

[Here ](https://github.com/megamingus/TextBoxBugExample)is a simple app showing the bug.

**Comment by tomzorz** [comment]
@mjracca Your code misses a small but important thing: the FontFile.ttf#**FontName** part has to be set for the preferred font style, eg. "MyCustomFont.ttf#MyCustomFont Bold".

See http://www.jayway.com/2012/10/31/using-custom-otf-fonts-in-windows-8-xaml/ or http://stackoverflow.com/questions/23905901/defining-a-custom-fontfamily-with-several-font-files-in-xaml-c for examples.

**Comment by mjracca** [comment]
Thanks! That's kind of unfortunate, since we are dynamically change formatting and we have every format binded up with converters. At lease now we are sure how to make it work.

That would be an awesome thing to have automatically solved!
