### ISSUE TITLE
TextBox ignores Foreground color when focused

### ISSUE THREAD

**Issue by mjracca** [Microsoft/WindowsUIDevLabs#51]
Whenever we focused **TextBox** to start writing the _Foreground_ color changes from the one we defined to black. We found no way to change it even when editing it's XAML definition.

**Comment by robmikh** [comment]
By XAML definition do you mean it's style template? You can learn more about that [here](https://www.jeff.wilcox.name/2010/08/using-blend-to-find-default-style-xaml/). Note that Blend is used in that post, but you can do the same in Visual Studio.

**Comment by tomzorz** [comment]
Also don't forget that even if you set specific values for the foreground color in the template as an override, you'll need to set it in all the visual states as well. Probably those are the things that you haven't changed yet.

**Comment by mjracca** [comment]
Yes, sorry! I meant the style template! I will try that again and let you know. Thanks!
