### ISSUE TITLE
RenderTargetBitmap alternative in Composition

### ISSUE THREAD

**Issue by ratishphilip** [Microsoft/WindowsUIDevLabs#53]
Is there a more powerful alternative to **RenderTargetBitmap.RenderAsync** method in Windows.UI.Composition? 
As per [MSDN](https://msdn.microsoft.com/en-us/library/windows/apps/dn298556.aspx), **RenderTargetBitmap.RenderAsync** has its own limitiations.
I wish there was a better API to capture the pixels within a UIElement.

**Comment by robmikh** [comment]
Currently there is no way to capture the content of Visuals or XAML elements using the composition api.

**Comment by ratishphilip** [comment]
It would be great if such an API could be added in Composition in the near future.

**Comment by pgills** [comment]
@ratishphilip Thanks for the feedback!

**Comment by tomzorz** [comment]
@ratishphilip @pgills +1'ing as it'd be a solution for many things - including #46 as well.

**Comment by pgills** [comment]
Closing this issue. This is really good feedback and is captured in the Feedback milestone.
