### ISSUE TITLE
List current properties in a PropertySet

### ISSUE THREAD

**Issue by aL3891** [Microsoft/WindowsUIDevLabs#54]
There doesn't seem to be a way to list the current properties and their types in a `CompositionPropertySet`. Please consider adding a `Keys` collection or something similar since it's difficult to know what properties you get from external sources like scrollviews

**Comment by pgills** [comment]
@aL3891 Thanks for the feedback!

**Comment by pgills** [comment]
Thanks for the feedback and closing this issue. It's captured in the Feedback milestone.
