### ISSUE TITLE
Microsoft.UI.Composition.Toolkit project does not seem to be complete

### ISSUE THREAD

**Issue by robert-virkus** [Microsoft/WindowsUIDevLabs#55]
The project "Microsoft.UI.Composition.Toolkit" in WindowsUIDevLabs-master\Demos\Reference Demos currently does not include all referenced files. Therefore I cannot build all demos that rely on this project.

Thanks for the good work,
Robert

**Comment by pgills** [comment]
@robert-virkus Thanks for logging this issue. We'll update that project file.

**Comment by msftdavid** [comment]
Cleaning up an old issue... 

I tried out the CompositionImageSample project in SampleGallery that references the Toolkit, and it builds and runs successfully. I believe this issue no longer occurs.
