### ISSUE TITLE
Repeating animation leads to a stuttering animation

### ISSUE THREAD

**Issue by robert-virkus** [Microsoft/WindowsUIDevLabs#56]
[CompositionRefreshProblem.zip](https://github.com/Microsoft/WindowsUIDevLabs/files/211936/CompositionRefreshProblem.zip)
Hi everyone,

I try to rotate the icon of an AppBarButton for a refresh scenario. For the first couple of runs this works fine but then the animation starts to stutter. 

Here's the code I am using:
`public sealed partial class MainPage : Page
    {

        Visual _refreshVisual;
        private bool _isAnimationStarted;

        public MainPage()
        {
            this.InitializeComponent();
        }

        private async void startRefresh(object sender, RoutedEventArgs e)
        {
            if (_isAnimationStarted)
            {
                Debug.WriteLine("ignoring refresh request");
                return;
            }
            _isAnimationStarted = true;
            var visual = _refreshVisual;
            if (visual == null)
            {
                visual = initRefreshVisual();
            }
            // start animation:
            var compositor = visual.Compositor;
            LinearEasingFunction linear = compositor.CreateLinearEasingFunction();
            var animation = compositor.CreateScalarKeyFrameAnimation();
            animation.InsertKeyFrame(0.0f, visual.RotationAngleInDegrees);
            animation.InsertKeyFrame(1.0f, visual.RotationAngleInDegrees + 360f, linear);
            animation.Duration = TimeSpan.FromMilliseconds(2000);
            animation.IterationBehavior = AnimationIterationBehavior.Forever;
            visual.StartAnimation("RotationAngleInDegrees", animation);

            await Task.Delay(1000);

            visual.StopAnimation("RotationAngleInDegrees");
            _isAnimationStarted = false;

        }

        private Visual initRefreshVisual()
        {
            var icon = refreshAppBarButton.Icon;
            Visual visual = ElementCompositionPreview.GetElementVisual(icon);
            visual.Size = new System.Numerics.Vector2((float)icon.ActualWidth, (float)icon.ActualHeight);
            visual.CenterPoint = new System.Numerics.Vector3(visual.Size.X / 2f, visual.Size.Y / 2f, 0f);
            _refreshVisual = visual;
            return visual;
        }
    }`

I have also attached a reproduction project. To reproduce the problem, start the app and then hit the refresh button and wait for the animation to stop. Repeat around 4 times to see the animation jittering and stuttering.

On a related note: calling visual.StopAnimation() seems to jump back a bit. 

Is there something that I am doing wrong here or did I find a bug? I am on Windows 10586, by the way.

Thanks in advance,
    Robert
[CompositionRefreshProblem.zip](https://github.com/Microsoft/WindowsUIDevLabs/files/211936/CompositionRefreshProblem.zip)

**Comment by pgills** [comment]
@robert-virkus Thanks for the repo and the build number those are super helpful for determining if it's a platform issue. We'll have some folks take a look.

**Comment by likuba** [comment]
Hey @robert-virkus 

In addition to seeing if there is something going on here, you may want to check out the gears sample where we do something similar and weren't encountering these bugs.  If there is not a reason you specifically want to do 0 to 360 as opposed to "current value + 360" you could try using an expression keyframe with this.startingvalue.  When using the below, we weren't seeing the issues described above. (Sorry about the formatting--GitHub isn't recognizing the first few lines as code...)

`private void EnsureGearMotor()
        {
            if (_gearMotor == null)
            {
                _gearMotor = _compositor.CreateScalarKeyFrameAnimation();
                var linear = _compositor.CreateLinearEasingFunction();

                _gearMotor.InsertExpressionKeyFrame(0.0f, "this.StartingValue");
                _gearMotor.InsertExpressionKeyFrame(1.0f, "this.StartingValue + 360", linear);

                _gearMotor.IterationBehavior = AnimationIterationBehavior.Forever;
            }
        }
`

**Comment by robmikh** [comment]
Fixed it for you :)

**Comment by robert-virkus** [comment]
Thanks a lot for the feedback. Unfortunately using a expression keyframe does not change anything. I have adapted the sample to make the clicking more visible and uploaded a video here:

https://onedrive.live.com/redir?resid=BFB8A4335206A652!380370&authkey=!AJ6edZMc3fZaR5Y&ithint=video%2cmp4

I have also attached the updated reproduction sample.

I encounter the same problem on Windows 10 Mobile / Lumia 950 XL (no insider, v10.0.10586.164).

Your Gears example is target Windows vNext with the insider SDK, but I am restricted to 10586.

Can you reproduce the problem? Any ideas what I could do about it? 

Thanks,
   Robert
[CompositionRefreshProblem-v2.zip](https://github.com/Microsoft/WindowsUIDevLabs/files/214461/CompositionRefreshProblem-v2.zip)

**Comment by robert-virkus** [comment]
Just FYI: with the latest official Windows release 10.0.10586.218 I encounter the same issue on both mobile and PC.

**Comment by robert-virkus** [comment]
Ok, I found a workaround. I just reset the XAML UI structure after 3 refreshes by setting a new icon. That's not nice but at least I am unblocked.

Here's the relevant code:
` private void resetRefreshVisual()
        {
            var icon = new SymbolIcon(Symbol.Refresh);
            icon.Loaded += onIconLoaded;
            refreshAppBarButton.Icon = icon;
        }

        private void onIconLoaded(object sender, RoutedEventArgs e)
        {
            _numberOfRefreshes = 0;
            initRefreshVisual();
            _animation = null;
        }

        private Visual initRefreshVisual()
        {
            var icon = refreshAppBarButton.Icon;
            Visual visual = ElementCompositionPreview.GetElementVisual(icon);
            visual.Size = new System.Numerics.Vector2((float)icon.ActualWidth, (float)icon.ActualHeight);
            visual.CenterPoint = new System.Numerics.Vector3(visual.Size.X / 2f, visual.Size.Y / 2f, 0f);
            _refreshVisual = visual;
            return visual;
        }`

I have also attached the workaround project in case other stumble upon the same problem.

Best,
   Robert
[CompositionRefreshProblem-workaround.zip](https://github.com/Microsoft/WindowsUIDevLabs/files/216682/CompositionRefreshProblem-workaround.zip)

**Comment by shandilvarun** [comment]
I made one change on the expression code i.e. made the animation duration and task.delay the same and I don't see any glitch now with continuous clicking. is there a reason you need different timings for them?

**Comment by robert-virkus** [comment]
Hi Shandilvarun,

thanks for your code, but in that code you don't stop the animation at all. My problem is that when the animation is repeatedly started and stopped, then it starts to jitter. The Task.Delay() call is too simulate a refresh situation, e.g. network access. The delay is not related to the animation time at all.

Best,
   Robert

**Comment by shandilvarun** [comment]
Any reason you have to do this? without this piece of code I don't see any jitters. 

 if (_numberOfRefreshes > 2)
            {
               resetRefreshVisual();
            }

**Comment by robert-virkus** [comment]
Hi Shandilvarun, you're looking at the workaround code that helped me to remove the jitters. Without it the animation jitters, compare the video. If you do not experience the jitters I assume that you are not on Windows 10.0.10586.218?

**Comment by shandilvarun** [comment]
Yes, I'm on a newer build and this should be fixed for you as you update your insider builds. Use this.StartingValue code and you should not see this problem in future flights. Thanks!!

**Comment by robert-virkus** [comment]
Ok, I'll use my workaround for the official release then.

**Comment by shandilvarun** [comment]
Awesome and Thanks for reaching out.
Closing this out.
