### ISSUE TITLE
Magic property strings

### ISSUE THREAD

**Issue by espenrl** [Microsoft/WindowsUIDevLabs#57]
This is a suggestion for readability - use nameof operator to clarify where property names origins.

Instead of
visual.StartAnimation("RotationAngle", ...)

use
visual.StartAnimation(nameof(Visual.RotationAngle), ...)

Instead of
implicitAnimationCollection["Offset"] = ...

use
implicitAnimationCollection[nameof(Visual.Offset)] = ...

**Comment by pgills** [comment]
@espenrl Thanks for the suggestion. Mostly it comes down to style to sample authors.

Folks on the team are starting to leverage some of the new features in C# 6.0 like the [nameof](https://msdn.microsoft.com/en-us/library/dn986596.aspx) operator and [string interpolation](https://msdn.microsoft.com/en-us/library/dn961160.aspx) when using our Expressions, KeyframeAnimations, and ExpressionAnimations.

**Comment by aL3891** [comment]
Fyi, my (CompositionAnimationToolkit)[https://github.com/aL3891/CompositionAnimationToolkit] library now has support for using a lambda to start and stop animations

**Comment by pgills** [comment]
Thanks for the feedback. We will start to recommend folks using the nameof operator where appropriate in future samples to help will discoverability and readability of the samples. Closing and captured in Feedback milestone.
