### ISSUE TITLE
Driving a Keyframe animation with an expression

### ISSUE THREAD

**Issue by aL3891** [Microsoft/WindowsUIDevLabs#58]
As far as i understand it's not possible to drive a key frame animation with an expression, as opposed to driving it with time, is this correct? That would be a very useful feature, like for connecting a key frame animation to a scroll viewer and have the animation play in sync with scrolling.

**Comment by tomzorz** [comment]
@aL3891 I think you can do something like this with the InteractionTracker now

**Comment by JasterAtMicrosoft** [comment]
Yes, canonical way of doing this is using an ExpressionAnimation. You can set as an input to an ExpressionAnimation either manipulation from a XAML ScrollViewer via ElementCompositionPreview.GetScrollViewerManipulationPropertySet(), or the various composition properties of InteractionTracker. Then you can use the ExpressionAnimation to animate a property based on scroll offset. The ParallaxingListItems sample in this repo has a nice example of this.

It would certainly be interesting to be able to re-use KeyFrameAnimations to take either time or expression input though. :+1: It's something we may consider for a future release.

**Comment by patsiu** [comment]
@aL3891 depending on your scenario, you can also use the Lerp function within an Expression Animation to drive the animation between two specific values where you can make an equation for the progress value that is derived from other components.

**Comment by aL3891** [comment]
I see, but that is only typically practical for two values, not for a whole bunch of them. Consider a scenario where you'd like to cycle though a bunch of colors while scrolling, or animate moving along a path. It would be really useful to have a `Time` expression on key frame animations, that you could either set to a `CurrentTime` function or some other expression.

**Comment by patsiu** [comment]
@aL3891 Correct - Lerp is only useful when going between two values/control points. Wasn't sure if you were going after multiple control points or two so I figured I'd propose using Lerp to see :). Appreciate the feedback!

**Comment by pgills** [comment]
Closing. Feedback captured in the Feedback milestone. Thanks!
