### ISSUE TITLE
How can you use CreateColorKeyFrameAnimation for animating Xaml Control Background?

### ISSUE THREAD

**Issue by AudioW** [Microsoft/WindowsUIDevLabs#60]
Hi

The new Composition API looks great but I was wondering if there is a sample / instruction on applying a CreateColorKeyFrameAnimation on a Visual's Background property.

This is what I have so far but I keep getting a incorrect parameter error:

        private void AnimateBox(Visual targetVisual, Vector3 finalOffset)
        {
            var animation = _compositor.CreateColorKeyFrameAnimation();

            animation.Duration = TimeSpan.FromSeconds(1);

            animation.InsertKeyFrame(0.0f, Colors.White);

            animation.InsertKeyFrame(1.0f, Colors.Green);

            targetVisual.StartAnimation("Background.Color", animation);

        }

**Comment by patsiu** [comment]
Hey @AudioW,

Thanks for reaching out with your question. Unfortunately, there isn't a property called Background off of Visual that you can animate. That is the reason for the incorrect parameter error. (check out [this page](https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.composition.visual.aspx) for the list of properties off Visual).

That said, if you want to animate color, you can do so by calling StartAnimation() off of the SpriteVisual.Brush and targeting the color property - I put a short code snippet below.

        void ColorAnimation(SpriteVisual visual)
        {
            var colorAnimation = _compositor.CreateColorKeyFrameAnimation();
            colorAnimation.InsertKeyFrame(0.0f, Colors.Green);
            colorAnimation.InsertKeyFrame(1.0f, Colors.Cyan);
            colorAnimation.Duration = TimeSpan.FromSeconds(3);

            visual.Brush.StartAnimation("Color", colorAnimation);
        }

So in your code above, you need to change your StartAnimation to be off of a SpriteVisual's Brush property and then in the quotes, target the Color property. Is there a reason you were looking for a property called Background?

**Comment by JasterAtMicrosoft** [comment]
@AudioW To clarify what is going on here, Control.Background and other XAML Brush properties are not currently represented in the Visual returned by ElementCompositionPreview.GetElementVisual(). This is something we will look to improve in the future!

In the meantime, you can either:

1. Add a SpriteVisual to the tree using ElementCompositionPreview.SetElementChildVisual() and use the technique that @patsiu mentioned above.
2. Just animate the background brush using a [ColorAnimation](https://msdn.microsoft.com/library/windows/apps/br243066).

Option 2 is probably a bit easier, but option 1 will let you use other new Composition API's if you want!

**Comment by AudioW** [comment]
Thank you for all the instructions!
