### ISSUE TITLE
Listview reorder animation

### ISSUE THREAD

**Issue by AudioW** [Microsoft/WindowsUIDevLabs#61]
Is there a way to customize the animation that occurs when a user drags a listviewitem and attempts to drop it elsewhere in the list?

I would like the drop location show some sort of indication that it is the drop target, like a colored rectangle or horizontal line.

Also the animation of the other items 'making space' for the dragged item is something I would like to customize.

**Comment by pgills** [comment]
You should be able to attempt providing a custom drag and drop experience in a `ListView` or `Panel`:

1. Disable the built-in behavior by setting the `CanReorderItems` property on the `Listview` to `false`
2. Listen for the respective `Drag`* `Drop`* events
3. In your `DragOver` handler, leverage the new for 14295 `IInsertionPanel` interface [(reference)](https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.xaml.controls.iinsertionpanel.aspx) by calling `GetInsertionIndexes` [(reference)](https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.xaml.controls.iinsertionpanel.getinsertionindexes.aspx) then that should give you an idea of what items you are in between to perform your custom drawing.

We'll also take this as feedback to attempt at authoring a sample that can demonstrate this behavior.

In the meantime, we recommend looking at those APIs and that should get you started.

Let us know how it comes along!

**Comment by pgills** [comment]
Added to Feedback milestone and cleaning up issues.
