### ISSUE TITLE
An application-internal exception has occurred Issue

### ISSUE THREAD

**Issue by AudioW** [Microsoft/WindowsUIDevLabs#62]
Hi

For some reason, I get an exception when I attempt to resize my window that contains UI elements that use the new composition API. The exception I am getting is:

Unhandled exception at 0x00007FFD615DD67A (Windows.UI.Xaml.dll) in MyApp.exe: 0xC000027B: An application-internal exception has occurred (parameters: 0x00000249B07A7200, 0x0000000000000001).

When I only use the managed debugger, the exception is not caught but Visual Studio tells me a debugger was attached but not configured to handle the exception.

How can I find out what the problem is exactly?

**Comment by JasterAtMicrosoft** [comment]
Hi @AudioW,

Could you please verify if you are using the expression "FinalValue" in your implicit animations code? If so you will need to change this string to "this.FinalValue" and that should fix the issue.

Thanks,
Jake

**Comment by pgills** [comment]
@AudioW also are you running against build 10586 or 14295?

**Comment by shandilvarun** [comment]
Are you using Expression Animations, Keyframeanimations with Expressiions, implicit Animations? that will help in identifying the issue a bit.

**Comment by AudioW** [comment]
Hi all,

I am not using the term FinalValue in my code:

`            _compositor = new Compositor();

            _root = ElementCompositionPreview.GetElementVisual(this);

            _grd = ElementCompositionPreview.GetElementVisual(grd);

            _grd.CenterPoint = new System.Numerics.Vector3(45f, 50f, 0.5f);

            _compositor = _root.Compositor;

            Visual _wrapper = ElementCompositionPreview.GetElementVisual(wrapellipse);

            Visual _ellipse = ElementCompositionPreview.GetElementVisual(ellipse);`

And my animation:

`            var animation = _compositor.CreateVector3KeyFrameAnimation();

            // Create two keyframes that define starting and ending value of the property
            animation.InsertKeyFrame(0.0f, new System.Numerics.Vector3(0.0f));
            animation.InsertKeyFrame(1.0f, new System.Numerics.Vector3(1.0f));


            animation.IterationBehavior = AnimationIterationBehavior.Forever;

            animation.Duration = TimeSpan.FromMilliseconds(3000);

            _grd.StartAnimation("Scale", animation);`

It runs on a custom control within a datatemplate of a GridView. When I uncomment this code and attempt to resize my window. The application crashes as mentioned above. I am running against 14295.

**Comment by shandilvarun** [comment]
Do you mind sharing a sample app? that will help provide some clarity. 
In which event are you executing this code? where are your animations defined?

**Comment by AudioW** [comment]
Is it possible to send my source code privately to microsoft?

**Comment by shandilvarun** [comment]
@AudioW  what do you do with these visuals? the above code should not throw exception.

**Comment by AudioW** [comment]
I want to animate a custom UserControl so that it pops in when loading. I researched a bit further and this line seems to be causing the exception:

`_root = ElementCompositionPreview.GetElementVisual(this);`

Could it be that the fact that I want to get a visual from a custom usercontrol that the exception occurs?

**Comment by AudioW** [comment]
I have created a sample app which mimics the situation I have in my own application and now there is no exception... Are there other ways of attaching a debugger which can notify me of what is going on?

**Comment by AudioW** [comment]
So here is some more research info:

I started stripping down my entire project until the exception would no longer occur and this code seems to be causing the problem:

`            <SplitView.Content>
                <Frame x:Name="ContentFrame" Margin="20,0,0,0">
                    <Frame.ContentTransitions>
                        <TransitionCollection>
                            <ContentThemeTransition />
                        </TransitionCollection>
                    </Frame.ContentTransitions>
                </Frame>
            </SplitView.Content>`

The page with my gridview is hosted in this ContentFrame and when I remove the ContentTransitions the exception no longer occurs. So it seems the ContentThemeTransition and the Compositor code form some sort of exception when combined...

**Comment by AudioW** [comment]
So here is some more info after some research. I started stripping away to find out when the exception would not occur anymore and when I remove all Page content transitions, the exception no longer occurs. It seems that when I want to use the visual composition api's together with content theme transitions, they form an exception together....

**Comment by JasterAtMicrosoft** [comment]
I wasn't able to reproduce this with a UserControl calling ElementCompositionPreview.GetElementVisual, in a GridView, in a Grid with ContentThemeTransition. I think it may have been fixed as part of the last Windows release. If you're still having trouble with this, please feel free to reply with detailed repro steps.

Thanks,
Jake
