### ISSUE TITLE
Scale CompositionImage Keeping Clipping

### ISSUE THREAD

**Issue by juanpaexpedite** [Microsoft/WindowsUIDevLabs#63]
First of all, at this moment I understand even having the 14295 SDK Preview we cannot use anything really new. So I am using the 10586 to make the following taking the CompositionImage like the PointerEffectsXaml

1.- In the CompositionImage Loading Event I set the Sprite to Opacity= 0 and Scale to 1.25,1.25,1.0f (Vector3).

2.- I have successfully animate the opacity when the composition Image appears (I track all are loaded "CompositionImage_ImageOpened" and then I animate them) 

3.- I would like to animate also the Scale and keep a 'Clip' about the Width and Height it has like a Viewport because when I scale it I want to scale just the brush and not all the CompositionImage. Is that possible at this moment? which should be the target?

**Comment by pgills** [comment]
For the first issue, have you tried [retargeting](https://github.com/Microsoft/WindowsUIDevLabs/wiki/Sample-Gallery-SDK-Retargeting) both the Sample Gallery and Samples Common project files against 14295? After retargeting you should see new samples that demonstrate: Shadows, Thumbnail Lighting, Interactions, Destination/Backdrop effects. 

I believe SamplesCommon\CompositionImage.cs has an example of what I think you are trying to achieve (I think you want to do a `Scale` down the `Brush` to 1, and fade in the `Opacity` to 1, but maintain a clipping region that's the original size of the context). If you look at the `StartCrossFade` method the Scaling behavior kicks in on builds compiled with the 14295 SDK, so I think the default behavior is built in. The Continuity Sample has that effect applied to its items.

**Comment by juanpaexpedite** [comment]
Yes I realized when I began that the projects weren't with the 14295, the remote computer for debugging I am using is Build 14316.rs1_release.16402-2217. (I prefer do not upgrade my local machine, but deploys fine)

Well I understand when I am able to run the new views of the example I will solve that.

Anyway I have a mockup with XAML with:

         <common:CompositionImage.Clip>
         <RectangleGeometry Rect="0,0,250,196"/>
         </common:CompositionImage.Clip>

until I am able to do that via Composition. The effect is really awesome, since Windows Phone 7 I wanted to make this kind of effects keeping the app smooth. And thanks for the support, it is really appreciated.

**Comment by robmikh** [comment]
You could achieve this if you add an extra visual. Let's call your current visual "Visual A" and a new visual "Visual B". If you make Visual A a child of Visual B and assign an InsetClip as the Clip property to Visual B, this should work. I've got this rigged up using the code bellow:

```
private Compositor _compositor;
private IImageLoader _imageLoader;
private ContainerVisual _parentVisual;
private SpriteVisual _childVisual;

public MainPage()
{
    this.InitializeComponent();

    Loaded += (s, a) =>
    {
        InitComposition();
    };
}

private async void InitComposition()
{
    _compositor = ElementCompositionPreview.GetElementVisual(this).Compositor;
    _imageLoader = ImageLoaderFactory.CreateImageLoader(_compositor);

    var surface = await _imageLoader.LoadImageFromUriAsync(new Uri("ms-appx:///Assets/photo.jpg"));
    var brush = _compositor.CreateSurfaceBrush(surface);

    var contentVisual = _compositor.CreateSpriteVisual();
    contentVisual.Size = surface.Size.ToVector2();
    contentVisual.Brush = brush;
    contentVisual.CenterPoint = new Vector3(surface.Size.ToVector2() / 2.0f, 0);

    var clipVisual = _compositor.CreateContainerVisual();
    clipVisual.Size = surface.Size.ToVector2();
    clipVisual.Offset = new Vector3(
        (float)ActualWidth / 2 - clipVisual.Size.X / 2,
        (float)ActualHeight / 2 - clipVisual.Size.Y / 2, 
        0);
    clipVisual.Clip = _compositor.CreateInsetClip(0, 0, 0, 0);

    clipVisual.Children.InsertAtTop(contentVisual);
    ElementCompositionPreview.SetElementChildVisual(this, clipVisual);

    _childVisual = contentVisual;
    _parentVisual = clipVisual;

    Animate();
}

private void Animate()
{
    double duration = 1500;

    var opacityAnimation = _compositor.CreateScalarKeyFrameAnimation();

    opacityAnimation.InsertKeyFrame(0.0f, 0.0f);
    opacityAnimation.InsertKeyFrame(1.0f, 1.0f);

    opacityAnimation.IterationCount = 1;
    opacityAnimation.Duration = TimeSpan.FromMilliseconds(duration);

    var scaleAnimation = _compositor.CreateVector3KeyFrameAnimation();

    scaleAnimation.InsertKeyFrame(0.0f, new Vector3(3.0f, 3.0f, 1.0f));
    scaleAnimation.InsertKeyFrame(1.0f, new Vector3(1.0f, 1.0f, 1.0f));

    scaleAnimation.IterationCount = 1;
    scaleAnimation.Duration = TimeSpan.FromMilliseconds(duration);

    _childVisual.StartAnimation(nameof(_childVisual.Opacity), opacityAnimation);
    _childVisual.StartAnimation(nameof(_childVisual.Scale), scaleAnimation);
}
```

And it should look like this:

![Scale and Clip](http://i.giphy.com/8HJC1WL8oC8bC.gif)

Was that the type of effect you were looking for?

**Comment by juanpaexpedite** [comment]
Really cool!, yes exactly that, I did not think that there were something like clipVisual.Clip = _compositor.CreateInsetClip(0, 0, 0, 0); Thanks I will try when come back.

**Comment by pgills** [comment]
Cleaning up issues.
