### ISSUE TITLE
Unable to animate Opacity of a Grid

### ISSUE THREAD

**Issue by ratishphilip** [Microsoft/WindowsUIDevLabs#64]
I have a Grid which consists of several children ( a collection of UserControls). I am trying to animate the Opacity of this Grid using the following code

`var rootGridVisual = ElementCompositionPreview.GetElementVisual(RootGrid);`
`scalarAnim = _compositor.CreateScalarKeyFrameAnimation();`
`scalarAnim.InsertKeyFrame(0.4f, 0);`
`scalarAnim.Duration = TimeSpan.FromSeconds(0.5);`

`rootGridVisual.StartAnimation(nameof(rootGridVisual.Opacity), scalarAnim);`

But upon running this code, the opacity of the Grid does not change **at all**.

Am I missing something here?

**Comment by tomzorz** [comment]
Not sure, but I think you'll need two keyframes minimum.

**Comment by ratishphilip** [comment]
Even then it does not work. I tried the following code

`var rootGridVisual = ElementCompositionPreview.GetElementVisual(RootGrid); `
`scalarAnim = _compositor.CreateScalarKeyFrameAnimation(); `
`scalarAnim.InsertKeyFrame(0, 1f); `
`scalarAnim.InsertKeyFrame(0.4f, 0.4f);` 
`scalarAnim.InsertKeyFrame(0.7f, 0); `
`scalarAnim.Duration = TimeSpan.FromSeconds(0.5); `

` rootGridVisual.StartAnimation(nameof(rootGridVisual.Opacity), scalarAnim); `

But it still does not work.

*The same code works as expected on a newly created* ***SpriteVisual****.*

**Comment by shandilvarun** [comment]
Hi @ratishphilip, 
Can you provide some details on what you want to achieve? What build # are you on? 
When I run your code I do see the grid and children to hide and play the animation. Here is the code 

 private void Button_Click(object sender, RoutedEventArgs e)
        {
            
            var rootGridVisual = ElementCompositionPreview.GetElementVisual(contentGrid);
            var _compositor = rootGridVisual.Compositor;
            var scalarAnim = _compositor.CreateScalarKeyFrameAnimation();
            scalarAnim.InsertKeyFrame(0, 1f);
            scalarAnim.InsertKeyFrame(0.4f, 0.4f);
            scalarAnim.InsertKeyFrame(0.7f, 0f);
            scalarAnim.Duration = TimeSpan.FromSeconds(0.5);

            rootGridVisual.StartAnimation(nameof(rootGridVisual.Opacity), scalarAnim);

        }

<Grid x:Name="mainGrid">
        <Grid.ColumnDefinitions>
            <ColumnDefinition/>
            <ColumnDefinition/>
        </Grid.ColumnDefinitions>
        <Button Content="test" Width="200" Grid.Column="0" Height="200" Click="Button_Click"/>
        <Grid x:Name="contentGrid" Grid.Column="1">
            <Image Source="Assets\StoreLogo.png"/>
        </Grid>
    </Grid>

**Comment by ratishphilip** [comment]
I am on SDK 14295.

My Grid contains several rows and columns. Each of the cell contains a user control (which contains a border and a textblock).

I am able to run a scale animation successfully on the grid. It scales well. But it does not animate the opacity. I am trying to achieve the following:
1.  animate the opacity to 0 while the grid scales up.
2.  animate the opacity to 1 when the grid scales back to its original size.

I am using a scoped batch to execute the opacity and scale animations together.

**Comment by ratishphilip** [comment]
Another difference I noted in your code is that you are assigning the compositor like this
```C#
var _compositor = rootGridVisual.Compositor;
```

whereas in my code I am initializing the compositor in the OnNavigatedTo override

```C#
protected override void OnNavigatedTo(NavigationEventArgs e)
        {
            base.OnNavigatedTo(e);

            InitializeComposition();
        }

private void InitializeComposition()
        {
            _compositor = ElementCompositionPreview.GetElementVisual(this).Compositor;
            ...
        }
```

Does that make a difference?

**Comment by shandilvarun** [comment]
@ratishphilip assigning compositor either way should be fine. for opacity do you want to change opacity on each item in the grid or do you want to change opacity of the Grid itself? can you add a sample project for us to see what is going on?

**Comment by shandilvarun** [comment]
Hi @ratishphilip, Update
we think you might be running into a bug that we had in 14295, which has been resolved in future builds and hence I'm not seeing this issue. You should see this fixed in coming flights.

**Comment by ratishphilip** [comment]
I found the cause of the issue.

Within the scopedbatch animation I am setting the** Grid.IsHitTestVisible = false**. Due to this the opacity animation does not work.

If I comment that line of code, then opacity works!

**Comment by shandilvarun** [comment]
Awesome! Closing down the issue.
