### ISSUE TITLE
CompositionImage issues

### ISSUE THREAD

**Issue by ratishphilip** [Microsoft/WindowsUIDevLabs#65]
If I have a CompositionImage in a XAML and subscribe to its PointerPressed event, then on clicking on the image the event is not raised.

Also XAML Designer shows that there is an exception whenever I add a CompositionImage to the XAML.

**Comment by pgills** [comment]
@ratishphilip Thanks for the issue. Could you also include which Windows build and SDK you are using as well? It just helps narrow down a repro for us to determine if it's hit testing in the platform or some other issue.

Also in the future it would be super helpful to log an issue per potential bug you are encountering - that way we can track them accordingly and ensure we don't loose something through the cracks.

Visuals not displaying in the XAML Designer is a known issue that we are looking into. @robmikh for this one as FYI.

**Comment by ratishphilip** [comment]
Sorry, I shall log an issue per potential bug in the future.

I am using SDK v14295. I am on Windows build 14316.

**Comment by pgills** [comment]
No worries. We're still experimenting how we want to use GitHub issues for bugs, feedback, etc. and we haven't been too formal on the process. We've gotten some feedback within the team to try and formalize issue formatting. So sometime time in the future we'll have something written down.

Currently, we're trying to recommend folks stay on matching builds and SDKs for the best compatibility, especially with Insider builds. We're starting to track that here [Last Known Good](https://github.com/Microsoft/WindowsUIDevLabs/wiki/Last-Known-Good). 

The current version combinations you are using might just line up enough so most of your scenarios continue to behave the same, but unfortunately it's not guaranteed. Just letting you know incase you start hitting more issues as you explore more of the API surface area.

But we'll look into that hit testing one.

**Comment by msftdavid** [comment]
Resolving due to lack of activity.
