### ISSUE TITLE
Support for System.Double in System.Numerics namespace

### ISSUE THREAD

**Issue by ratishphilip** [Microsoft/WindowsUIDevLabs#67]
It would be great if the classes in **System.Numerics** namespace such as **Vector2**, **Vector3**, **Vector4**, **Matrix3x2**, **Matrix4x4**, **Plane** & **Quaternion** accept **System.Double** too wherever they are accepting **System.Single** or **float**.

Most of the values that we calculate or derive from other properties of UIElement are of type **System.Double** and each time while providing values to the classes in the **System.Numerics** namespace we have to cast them to **float**.

It would be great if they could accept **System.Double** and convert them to **float** _**internally**_. _This would save us lot of time._

**Comment by pgills** [comment]
Added to Feedback milestone and cleaning up issues.
