### ISSUE TITLE
ComboBox close bug

### ISSUE THREAD

**Issue by AudioW** [Microsoft/WindowsUIDevLabs#69]
Hi,

I noticed that when I open a Combobox that only contains disabled items and I attempt to scroll down, the combobox immediately closes...

**Comment by pgills** [comment]
@AudioW Which build + SDK combination are you seeing this behavior?

I'll be happy to forward this one on to our Controls team to determine if this is the expected behavior or a platform issue.

**Comment by AudioW** [comment]
I am running build 14332 against sdk 14295

**Comment by pgills** [comment]
Thanks for the info, I'll send this over to the Controls team to see if this is expected of a platform issue.

**Comment by YuliKl** [comment]
@AudioW Thank you for your feedback. I'm not able to repro the problem using the following. How are you populating your ComboBox?

```xaml
<ComboBox>
    <ComboBoxItem Content="Happy" IsEnabled="False"/>
    <ComboBoxItem Content="Sleepy" IsEnabled="False"/>
    <ComboBoxItem Content="Sneezy" IsEnabled="False"/>
    <ComboBoxItem Content="Bashful" IsEnabled="False"/>
    <ComboBoxItem Content="Grumpy" IsEnabled="False"/>
    <ComboBoxItem Content="Dopey" IsEnabled="False"/>
    <ComboBoxItem Content="Doc" IsEnabled="False"/>
    <ComboBoxItem Content="Happy" IsEnabled="False"/>
    <ComboBoxItem Content="Sleepy" IsEnabled="False"/>
    <ComboBoxItem Content="Sneezy" IsEnabled="False"/>
    <ComboBoxItem Content="Bashful" IsEnabled="False"/>
    <ComboBoxItem Content="Grumpy" IsEnabled="False"/>
    <ComboBoxItem Content="Dopey" IsEnabled="False"/>
    <ComboBoxItem Content="Doc" IsEnabled="False"/>
</ComboBox>

**Comment by pgills** [comment]
Closing issue, please reopen if this issue still reproduces on the latest configuration.
