### ISSUE TITLE
What is the best way to alternate ListView row color like in Microsoft Groove?

### ISSUE THREAD

**Issue by AudioW** [Microsoft/WindowsUIDevLabs#70]
I am looking for the easiest way to do alternate row colors without subclassing ListView

**Comment by JasterAtMicrosoft** [comment]
Hi @AudioW, you can use [ListView.ContainerContentChanging](https://msdn.microsoft.com/library/windows/apps/windows.ui.xaml.controls.listviewbase.containercontentchanging.aspx) to update the style or background of the ListViewItem's based on item index. Would that be preferable for your use case?

**Comment by AudioW** [comment]
Got It !

**Comment by tomzorz** [comment]
@AudioW I used the CustomResource markup extension for this in my library. Check out the Alternator https://github.com/tomzorz/Groves/wiki/FakeMarkupExtension-syntax here :)

**Comment by JasterAtMicrosoft** [comment]
Cool stuff @tomzorz !
