### ISSUE TITLE
Known Issue: Crash when deploying to Windows Phone - SDK 14332 + Build 14332

### ISSUE THREAD

**Issue by assassin316** [Microsoft/WindowsUIDevLabs#72]
Ever since installing the 14332 SDK, VS 2015 Update 2 crashes when attempting to debug my app on an actual device (Lumia 830). Anyone else experience this ?

**Comment by pgills** [comment]
@assassin316 You might be hitting a issue with the live debugging tools that's we've been seeing.

Can you try this workaround in our [Known Issues](https://github.com/Microsoft/WindowsUIDevLabs/wiki/Insider-FAST#known-issues) for 14332 FAST and see if that helps?

**Comment by assassin316** [comment]
Ah yes, that worked!

Sorry for posting the question, should've tried that first, just came across that post.

Thanks!

**Comment by pgills** [comment]
No worries. I'm sure you're not going to be the only one who asks. I'm going to keep this issue open for a little bit so that other folks will know where to go if they run into the same issue on 14332.

**Comment by pgills** [comment]
Closing as we've added a known issues section to our wiki.
