### ISSUE TITLE
14332 Root Frame does not navigate anymore

### ISSUE THREAD

**Issue by AudioW** [Microsoft/WindowsUIDevLabs#73]
Hi

I have just upgraded my SDK to 14332 and my PC build to 14332 and when starting my application the following line:

`Frame.Navigate(typeof(SetupPage));`

which is executed from my MainPage.xaml.cs does not do anything. The navigation that occurs within App.xaml.cs does seem to work and when I try to navigate a subframe from MainPage.Xaml.CS this also works. 

I have changed my project to try this with SDK 14295 and 10586 but the results are the same.

What can I try?

Update:

When creating a new project and attempting to navigate to a different type page from MainPage.xaml.cs the navigation does not work.

**Comment by pgills** [comment]
@AudioW I'm a little confused on the issue that you are hitting.

Navigation when calling Navigate on the Frame hosted in App.xaml.cs will successfully navigate to MainPage.xaml.cs? However, trying to Navigate to any other subsequently defined Page does not navigate?

And by does not work, are you seeing an error, exception, or blank page?

**Comment by AudioW** [comment]
Hi Paul,

I hope I can clarify the situation:

The frame hosted in App.xaml.cs succesfully navigates to MainPage.xam.cs. No problems so far.

Then in the constructor of MainPage.xaml.cs I set:

`Frame.Navigate(typeof(MyOtherPage));`

This code is executed but nothing happens -> The frame stays on MainPage.xaml.cs

**Comment by JohnnyWestlake** [comment]
I could be wrong, but I don't believe you can navigate during an in-progress navigation (which in this case, a call during the construction of a page being navigated too is still inside a navigation).

You may want to wait until the navigation completes before calling another. I'm curious to know whether it used to work? I was under the impression that it shouldn't

**Comment by AudioW** [comment]
Hi Johnny,

you are right. I changed the navigation to occur when the Loaded event is fired and now all is well.

Thanks
