### ISSUE TITLE
Progressring does not animate properly

### ISSUE THREAD

**Issue by AudioW** [Microsoft/WindowsUIDevLabs#74]
I have a progressring which only does the circle twice. Then when reloaded the animation stays fixed and looks like this
![progress](https://cloud.githubusercontent.com/assets/10196339/14939141/74fd56ec-0f3a-11e6-94b7-d362eaa22daf.PNG)

All the dots move together when the animation does its 'one run'

**Comment by pgills** [comment]
@AudioW Thanks for the screen shot. It would be helpful if you could include the following information as well:

- Windows Insider Build Version: 
- Windows Insider SDK Version:
- A code snippet of the markup and code behind
- The expected result that you intended on
- The actual result you are seeing (which you've included as a screen shot already)

This will help our team understand if it's an underlying platform issue we need to investigate.

**Comment by AudioW** [comment]
![images](https://cloud.githubusercontent.com/assets/10196339/14970533/f713c4b4-10c9-11e6-8957-ca7be4f74f8c.png)
Hi Paul,

here is the extra info:
insider build 143321
sdk 14332

the code snippet is just a progressring within a new application...

The expected result is the attached picture. This weird behavior seems to be system wide, when I update apps in the store app, I see the same distorted progress ring in the titlebar of the application

**Comment by AudioW** [comment]
Fixed in 14383
