### ISSUE TITLE
Acces violation in WindowsXamlDiagnosticsTap.dll on build 14332 

### ISSUE THREAD

**Issue by aL3891** [Microsoft/WindowsUIDevLabs#75]
Hello, 
I got this strange error _almost_ every time I start the sample gallery project now, 

Unhandled exception at 0x00007FFDEAC619DA (WindowsXamlDiagnosticsTap.dll) in CompositionSampleGallery.exe: 0xC0000005: Access violation reading location 0x0000000000000000.

I'm not quite sure if its something I've done but I've removed all the changes I've made as far as I know and I still get it. this happens immediately when the app starts and only while debugging.. is this something you've seen?

**Comment by pgills** [comment]
@aL3891 Check out latest known issues against the FAST ring: http://aka.ms/winuilabs/InsiderFast

You are most likely hitting the Live Visual Tree issue - Disable the Live Visual Tree Debugging and that should unblock you.

**Comment by pgills** [comment]
Also it will include the list of API changes from 14295 to 14332. Hope that helps

**Comment by aL3891** [comment]
ah cool, thanks!
