### ISSUE TITLE
Page Transitions

### ISSUE THREAD

**Issue by assassin316** [Microsoft/WindowsUIDevLabs#76]
Hi,

Does anyone know of a recipe/formula to use Composition for page transitions?? In my case, my app is composed of a SplitView which contains the root frame. So I'm wondering, am I supposed to perform a page transition before actually calling a Navigate since calling Navigate immediately removes the page?

**Comment by pgills** [comment]
@assassin316 We'll take that as an action item to formulate guidance, a potential pattern, and a possible sample. I know it can be tricky considering the lifetime management of the Pages and XAML default Transition animations. @JasterAtMicrosoft for FYI if he already has some thoughts in the area.

**Comment by tomzorz** [comment]
Subbing, as this is something I always wanted to do. And yes, it'd be great to have the ability to animate the leaving and arriving content at the same time.

If there's a solution it'd be great if we'd get that as a universal content changing transition ability - technically the page-frame is just that.

**Comment by JohnnyWestlake** [comment]
As a general idea, using something like the TransitionFrame from the Windows Phone Silverlight toolkit is still a very valid idea, and works with composition.

Essentially you create a new frame by inheriting from frame - and put two ContentPresenter's inside it's template - one hosting new page and one hosting the old. You can then override the OnContentChanged method on the frame to animate your two content presenters, and work in whatever crazy system you want to choose the animations. Of course, you can stick composition in there too.

(For reference here's the WP version, but it's mighty overkill - https://phone.codeplex.com/SourceControl/latest#Microsoft.Phone.Controls.Toolkit/Transitions/TransitionFrame.cs, my own implementation barely hits 200 nicely-formatted lines)

**Comment by JasterAtMicrosoft** [comment]
Thanks for the response @JohnnyWestlake! This is a good approach.

As the original poster mentioned, the major difficulty with animating page transitions is that the new page content immediately replaces the old during the transition.

So, there are a few options here:

1. Implement system page transitions, like you can see in the Settings and Maps apps, via [NavigationThemeTransition](https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.xaml.media.animation.navigationthemetransition).
2. Use a solution like Johnny discussed that keeps the old page alive during your custom animated transition.
3. Only animate the incoming page with custom animations. Depending on your design this is sometimes okay. 
4. Delay the navigation, so e.g. in response to some user interaction you do a quick fade out animation, wait for it to complete, and then navigate the Frame.

This is absolutely something that we will be looking to support better in the future. In the mean time solutions like TransitionFrame can help bridge the gap for apps that need truly unique page navigation motions. As @pgills mentioned we may be putting out more content on this subject in the future. Feel free to respond here if you have further questions. Thanks!

**Comment by assassin316** [comment]
Thanks for the great feedback guys!!  I'm currently looking into option 1, hope it works for what I need, thanks!  :)
