### ISSUE TITLE
Slow performance comparing to the "previous" build

### ISSUE THREAD

**Issue by pellea** [Microsoft/WindowsUIDevLabs#8]
Hello,

I created an app based on the Slideshow UWP app. I was using the CompositionImage that was built-in directly in the DLL.
Now, I converted the application with the "new" CompositionImage in the Toolkit.

The big difference between the two version is if you reload the page of the application, in the previous version, for the second time, the image load very quickly (as if the images still in a cache). Now, the second load of the page takes the exact same time for the image to load as the first time (it downloads again the images).

Is there a difference when downloading the images? The previous version was very useful and the user experience increase a lot if the images are somehow "cache" along the way.

Thanks, Adrien.

**Comment by robald** [comment]
Hey Adrien, sorry for slow response.  Yes, the toolkit doesn't currently provide any caching for CompositionImage.  Image caching policy is often customized for the individual needs of the application but we are thinking about adding some basic support for it at some point in the future.  For now, if you need caching you should be able to build your own on top of CompositionImage in the Toolkit.

Thanks, Rob.

**Comment by pellea** [comment]
My point was that the previous version is far more "optimized" in term of "perceived performance" that the current one. I know that there is no caching in the toolkit. I was not able to run again the previous version again (wrong win10 insider version or whatever). Is there any chance you could check that performance fact when you load the page a second time? 

I think the new CanvasBitmap.LoadAsync is slow. I'm creating an app that displays multiples tile images to make one big image and the download of each tile images is very problematic. Compare to a web based version the download of images is very very slow. I don't know if this problem is linked to the previous one.

**Comment by robald** [comment]
I may have a local repro of what you are seeing.  We'll investigate and reply back with what we find.  Thanks!

**Comment by pellea** [comment]
Do you have any news regarding this issue ?
Thanks.

**Comment by robald** [comment]
We've identified a couple of bugs in the image loader sample code that may be causing the perceived perf issues.  We don't yet have fixes available but will post back here as soon as we do.

One option for you to consider if you are blocked by this is to try using Win2D for image loading for now.

thanks

**Comment by pgills** [comment]
Thanks @robald. 

We are currently iterating on our loading story. 

@pellea we have some more questions on your specific scenario:
- Have you tried using `CanvasBitmap.LoadAsync`? If so, when you say compared to a web version, do you mean compared to loading images in a browser or using something like `HttpClient.GetBufferAsync` to download the image?
- In your scenario, are you interested in applying image effects during load time?
- Have you tried using XAML image loading and using interop to manipulate the visuals that way using `ElementCompositionPreview.GetElementVisual(imageControl)`?

There are lots of ways to load images in the system today and we're working to get a good mix of feature for folks specifically targeting `Windows.UI.Composition`.

**Comment by pellea** [comment]
Based on all the test I have made, the `HttpClient.GetBufferAsync` is the better choice to quickly load images. But currently I load them with the `imageFactory `of the toolkit (because I need to use the UI Composition).

I do not need image effect. I only need to place them in a "grid-like control" and wrap them of a specific-colored border. I do not know how many columns/rows the "grid" will have in advance. And yes, I did try to load image in XAML but it's too "difficult" to place them dynamically where I want with XAML only.

Please do not forget that the first load of images isn't the initial problem. The problem is when I load a second time the same page, the images were loaded very quickly (as if images were cached somewhere) and it's not anymore the case.

**Comment by pgills** [comment]
Thanks for the feedback. We are definitely looking into this.

Just out of curiosity, what are the aspects of Windows.UI.Composition are you using for your scenario?

Or are you just trying to have a grid of images with dynamic rows and columns, something like having images in a GridView control?

**Comment by pellea** [comment]
I'm trying to make my inventory of Guild Wars 2 into an app. It has some border every 3 rows.... That part works really fine.

I can give you (in private) my solution if you want to see which crappy things I'm doing :)

**Comment by pgills** [comment]
@pellea this has been super helpful. 

What I'm going to do now start breaking down this big issue into smaller issues to have some folks address certain parts of it.

Just to recap the main issue we've been talking about this - is that correct?:
- Second load of the image seems to take the same amount time as the first time loading an image

Outside of that, have you looked at using image loading in XAML with something like `Image`, `BitmapImage` or `BitmapSource`? There are many case where displaying a grid of images might be more well suited using a `GridView` and `Image` controls. 

And then lastly what were the aspects of `Windows.UI.Composition` you wanted to use in your example?

**Comment by pellea** [comment]
> Just to recap the main issue we've been talking about this - is that correct?:
>     Second load of the image seems to take the same amount time as the first time loading an image

In earlier build, the second load of images take no time at all. Now in later build it take the same amount of time.

I used the Toolkit for loading images asynchronously using the CompositionImage.ImageLoaded (like the gallery example).

**Comment by pgills** [comment]
Perfect thanks for the clarification.

**Comment by pgills** [comment]
Closing. Have a look at the new ImageLoader in the SampleCommon's project for loading image data into CompositionDrawingSurfaces.
