### ISSUE TITLE
Type inferred keyframe animations

### ISSUE THREAD

**Issue by aL3891** [Microsoft/WindowsUIDevLabs#82]
Hey there,
I've added new methods to the [composition animation toolkit](https://github.com/aL3891/CompositionAnimationToolkit) that infers a lot of the things you have to state explicitly in the current api (because it needs to adhere to the winRT api restrictions)

Instead of writing this:

    Vector3KeyFrameAnimation offsetAnimation = compositor.CreateVector3KeyFrameAnimation();
    offsetAnimation.InsertKeyFrame(0.0f, new Vector3(0, 0, 0));
    offsetAnimation.InsertKeyFrame(0.5f, new Vector3(0, 0, -2000));
    offsetAnimation.InsertKeyFrame(1.0f, new Vector3(0, 0, 0));
    offsetAnimation.Duration = TimeSpan.FromMilliseconds(8000);
    offsetAnimation.IterationBehavior = AnimationIterationBehavior.Forever;
    visual.StartAnimation("Offset", offsetAnimation);

you can now write this

    visual.StartAnimation(r => r.Offset, new Vector3(0, 0, 0), new Vector3(0, 0, -2000), new Vector3(0, 0, 0)).Duration(8000).Loop();

This api infers the type of the property being animated (and its name) and takes keyframes directly as arguments, it then spaces them out evenly over the animation

What do you think? would love any feedback you have :)

**Comment by patsiu** [comment]
This is pretty cool! A few thoughts/questions :)
- I assume you evenly space out the KeyFrames? If so, any particular reason you didn't want to have the timestamp of the keyframe be an additional argument?
- Can you use another lamda expression as an argument if you wanted to create an Expression KeyFrame?
- Is there a way to input easing functions into this notation?

**Comment by aL3891** [comment]
Yes, keyframes are evenly spaced out, i'm not sure I understand what you mean though, since they are evenly spaced I don't need to have the timestamp(?) if you do want to set the timestamp, you cant really use this shorthand. The values argument is actually a params argument, so you an specify any number of values there, so I havent figured out a good way to also specify the timestamps. My thinking was that this would be used for small animations where even spacing is fine.

You cant use these methods to insert expression keyframes, i've been thinking about how to incorporate that, while retaining the strong typing for the values, it might actually be possible with some implicit type conversion to an intermediary keyframe type... have to think about that

Right now you can only add easing functions at the first or last frame using the `EaseIn`/`EaseOut` methods:

    visual.StartAnimation(r => r.Rotation, 360).EaseOut(compositor.CreateLinearEasingFunction()).Start();

Also, besides starting the animations directly there are also `CreateAnimation` overloads that don't start right away, so you can tweak the animation or reuse it

**Comment by patsiu** [comment]
Sorry, by timestamp I mean where along the normalized timeline from 0.0 -> 1.0 the Keyframe gets inserted at. My initial guess was this notation is targeted towards the simpler KFAs with less nuances and not a full replacement to the current model to creating KFAs. But super cool stuff! Keep us posted if you decide to add more to this :)

**Comment by aL3891** [comment]
Right, absolutely, this is not meant to be a replacement, only a shorthand :) my plan is to enable you to drop down to the actual animation types and add to them (you can do this now as well but its not super convenient) and also get the type inference and avoid strings

I have been thinking about adding more features to the actual expression system like a Time property or dot/cross product functions but i'm only thinking about that right now. basically i'd add a hidden composition object with some properties like a constantly increasing value (for time) and expression that calculate the dot/cross product. I figure you're already working on less hacky ways to do that though so i've put it on low prio :)

**Comment by JasterAtMicrosoft** [comment]
Very cool stuff! I would echo the feedback that supporting non-uniformly-distributed key frames and expression key frames would be nice as these are very common usages for the API's. Looking forward to see how this evolves!

**Comment by ratishphilip** [comment]
@aL3891 @patsiu @JasterAtMicrosoft 
Check out **KeyFrameAnimation&lt;T&gt;** generic class in [CompositionExpressionToolkit](https://github.com/ratishphilip/CompositionExpressionToolkit).
It is a generic class which provides a common interface to the various types of animation classes deriving from **KeyFrameAnimation**.
It also contains a set of APIs which can be chained together.

**Comment by aL3891** [comment]
Allright, I've made some changes :) 
Now its possible to write this:

    visual.CreateAnimation(v => v.RotationAngleInDegrees, 90, KeyFrame.Create(0.75, 180f), 360).Start();

So whats going on here? Basically the apis now accept a KeyFrame<TValue> insread of just a TValue. This class also has a implicit converstion from TValue to KeyFrame<Tvalue> so the original call pattern still works (where values are supplied as is) The non-generic KeyFrame class is used to create KeyFrame objects while also enabling type inference.

KeyFrame.Create can take either values or expressions that return the correct type: 

    visual.CreateAnimation(v => v.RotationAngleInDegrees, 90, KeyFrame.Create<float>(c => c.StartingValue + 90), 360).Start(); // small niggle, type inference doesn't work here

it can also accept a time stamp, 0.75 in this case and/or an easing function:

    LinearEasingFunction linear = compositor.CreateLinearEasingFunction();
    visual.CreateAnimation(v => v.RotationAngleInDegrees, 90, KeyFrame.Create(0.75, 180f, linear), 360).Start();

So you might wonder then, what happens when you supply the timestamp for some keys and not others? Currently those keys are marked as "floating" and are interpolated between the keys that have explicit timestamps, or 0 and 1 if the first or last key is not fixed. for example:

    visual.CreateAnimation(v => v.RotationAngleInDegrees, 0, 50, KeyFrame.Create(0.25, 100f), 150, KeyFrame.Create(0.75, 200f), 250, 300);

Here the 50 degree keyframe will have its time interpolated between 0 and 0.25, the 150 degree frame will have its time interpolated between 0.25 and 0.75 and the 250 degree frame will occur at the midpoint between the 200 and 300 keyframes

I'm not sure I'm explaining it very well but I think it makes sense :) the floating keys spread out evenly between the fixed ones and the "edges"

Additionally, you can now insert key frames after the animation is initially created:

    var ani = visual.CreateAnimation(v => v.RotationAngle, 0, 180);
    ani.InsertKeyframe(KeyFrame.Create(360f));

This also supports all the KeyFrame.Create options

You can also access and change existing keyframes:

    ani[ani.Count - 1].Value = 270;

This also creates a problem, what happens if you insert a keyframe with timestamp = 0.1? what happens if you change the last keyframes timestamp to 0.1? What happens is that the api will sort the fixed keys and redistribute the floating ones so that the animation will make sense.

Finally, I've removed the StartAnimation methods because I had a bit of a brain fart and didn't realize that they will start the animations immediately before the following fluent method calls are actually evaluated. this still makes sense though because you can still fluently call Start() and animations should be reused anyway.

These changes are not on nuget yet, but they are pushed to the repo. I do need to to some additional cleanup and testing before I release it properly though

**Comment by aL3891** [comment]
@ratishphilip That's interesting! One thing that I've really wanted to have though was the capture of the property that was animated, so that it doesn't have to be repeated each time the animation is started, that's why the `TargetedKeyFrameAnimation` are a bit more chunky

**Comment by patsiu** [comment]
@aL3891, @ratishphilip  Cool stuff guys! I'll have to play around with both of these sometime soon :)

**Comment by aL3891** [comment]
So I guess this is kind of obsolete now with the new expression builder? :)

**Comment by patsiu** [comment]
Expression Builder definitely helps out with a number of authoring issues for Expressions and for KeyFrameAnimations, ExpressionKeyFrames. That said, it doesn't go into shorthands/helpers for KeyFrameAnimations like your tookit does. Feel free submit ideas of what to add on or expand Expression Builder (or even better, submit a PR! :) )

**Comment by aL3891** [comment]
oh, I didn't realize it was open source, I thought it was a part of the sdk it self, i'll definitely check that out and see if some of the stuff in my lib can be moved over
