### ISSUE TITLE
ThemeTransitions & XAML Storyboards perform worse in Windows 10

### ISSUE THREAD

**Issue by JohnnyWestlake** [Microsoft/WindowsUIDevLabs#83]
Sorry, didn't get a chance to make a *good* video of this yet, but this one should give you some idea.

Basically, the built in Theme Transitions perform much worse / give a degraded user experience in Windows 10 vs Windows 8 / Phone 8.

See video demo here: (60FPS, but I don't know if OneDrive web player can play back at that)
https://onedrive.live.com/redir?resid=DE47921B27CEAD6E!358725&authkey=!AAjeKk2aqndVzyc&ithint=video%2cmp4

Video demos a Yellow Lumia 1520 on Win Mobile 10, Black Lumia 735 on Win Mob 10, and a much weaker White Lumia 520 on Windows Phone 8.1 on the right, all running the same store versions of Epicurious & Font Candy. (Performance issues are the same across all version of Win Mob 10 vs all versions on Windows Phone 8.1, more or less). Both apps are WinRT Phone apps.

You can see examples of ContinuumThemeTransition and EntranceThemeTransition both behaving either broken or ugly compared to previous Windows.  At points we either have it skipping the starts of animations, apparently ignoring easing functions (or not constantly evaluating them), and in some instances giving up the animation half way through.

[I can confirm those are the transitions being used because I wrote the demoed apps - apart from Settings of course ;P] Given ThemeTransition was meant to be an easy way of adding beautiful, smooth and performant animation this makes them less fit for purpose now, and certain not as an easy way of creating a beautiful app. They can actually make some apps look uglier now!

You can also see how the DrillDown / backwards theme transition in Windows Mobile 10 Settings performing wildly differently on different devices, and generally not doing what is expected of a ThemeTransition. Whereas Win 8 would pause a small bit to make sure the animation was perfect, Win 10 just goes for it and ends up delivering a worse experience.

There's a similar but less obviously evident issue with XAML storyboards, so I'm trying to get a much clearer example of that.

**Comment by JasterAtMicrosoft** [comment]
Thanks very much for the info Johnny. There's a lot to work through here, but I'll make sure we are tracking all of these issues as product bugs. We did change some of the default easing curves for the theme animations which may have broken some of these experiences as well. (For example, by default EntranceThemeTransition is vertical, not horizontal, in Windows 10.)

**Comment by JohnnyWestlake** [comment]
So, adding a sample for XAML animations now too:


This is using another app I wrote the UI for, CBS News, a WP 8.1 XAML App, demoed on a Lumia 520 running WP8.1, and a more powerful Lumia 735 running WinMo 10.

Of course, the weaker & older 520 bests in the 735 in everything. (Apologies, tried to get two of the same devices side by side running the different OS's just to make the point even clearer but couldn't locate our other 520).

Essentially points out a similar problem I've been noticing on the theme transitions - it's now having a tendency on Windows Mobile 10 to either occasionally skip animations altogether or ease incorrectly. Happening on BackEase & custom KeySpline animations (article text translate), whereas both were perfect previously.

Video also demo's problems with the PivotThemeTransition. 

It's especially frustrating on this app because on WP8.1, the smoothness and consistency on the animation rival experiences on iOS. And now with more powerful hardware on a newer OS, the exact same app get's visually downgraded because of these animation hiccups - and from what little testing I've done I've not found a way to get them anywhere near the level of smoothness or consistency was 8.1

60 FPS Video: https://onedrive.live.com/redir?resid=DE47921B27CEAD6E!365894&authkey=!AMmPZygfZXirVGE&ithint=video%2cmp4

**Comment by JasterAtMicrosoft** [comment]
Hey, I'm closing this because we are tracking this issue internally and there's not much more to add in this thread. Thanks again for your feedback!

**Comment by JohnnyWestlake** [comment]
No problem - I'm curious to know though whether it's actually verified on your end that there is some sort of end-performance disparity between 8 & 10 and not just nothingness

Thanks for taking a look!
