### ISSUE TITLE
Question: Refactoring InsertKeyFrame & InsertExpressionKeyFrame methods

### ISSUE THREAD

**Issue by ratishphilip** [Microsoft/WindowsUIDevLabs#84]
In **KeyFrameAnimation** class the overloads of the method **InsertExpressionKeyFrame** differ by the parameter **easingFunction**.

```C#
public void InsertExpressionKeyFrame(System.Single normalizedProgressKey, System.String value);
public void InsertExpressionKeyFrame(System.Single normalizedProgressKey, System.String value,
                                                    CompositionEasingFunction easingFunction);
```

Can't the overloads be combined into a single method where the **easingFunction** is an optional parameter? 

 Same case for the **InsertKeyFrame** method in the animation classes deriving from **KeyFrameAnimation**.

Are you throwing (or planning to throw) any exception if **null** value is passed for **easingFunction**?

**Comment by jeffstall** [comment]
The “easingFunction” parameter is optional. You may safely pass ‘null’.

**Comment by ratishphilip** [comment]
Thanks.
