### ISSUE TITLE
Invert effect does not respect alpha

### ISSUE THREAD

**Issue by juanpaexpedite** [Microsoft/WindowsUIDevLabs#86]
I understand (of course depending on the definition) that when I use invert, it only inverts the components R,G,B and not the alpha even when it uses premultiplied alpha inside. 
Why the InvertEffect doesn't keep the alpha values and why it supposes that goes from transparent to white?

**Comment by krenner** [comment]
@juanpaexpedite This is a known issue that has been recently addressed - which flight/build are you using?

**Comment by juanpaexpedite** [comment]
In this case just 10586, tomorrow I will try with a 14342 machine,  thank you for the answer

**Comment by krenner** [comment]
@juanpaexpedite please let us know if you still see an issue.  Thanks for your comments.
