### ISSUE TITLE
Moving source of Arithmetic effect

### ISSUE THREAD

**Issue by juanpaexpedite** [Microsoft/WindowsUIDevLabs#87]
First sorry for make al these issues, I really deep involved in my first game and all the menus and animations of titles etc. are using Composition and after I manage the basics I want to add more details.

In this case suppose I use two images to create the following:

![example](https://cloud.githubusercontent.com/assets/5947026/15398274/e6b2f5e0-1dda-11e6-84cb-d77d571049ad.jpg)

which is really cool, Done with the following sources:
![dinosaur](https://cloud.githubusercontent.com/assets/5947026/15398472/a208edc2-1ddb-11e6-8e79-4d30ade6f394.png)
![logomask](https://cloud.githubusercontent.com/assets/5947026/15398471/a2089246-1ddb-11e6-998d-282c30108281.png)

The mask is white with png so select to note that :).

Ok now what I want to make is move that image (the 'mask') because of course I can Offset the whole Visual but is it possible to move Source2 in somehow because it's a CompositionSurfaceBrush.

Might be there is another way that I have not realized out about, any way to achieve that?

I am using the following values:

     new[] { 1.0f, 0.0f, 1.0f, 0.0f } 

with the following helper:

     public static CompositionEffectBrush CreateComplexEffectBrush(Compositor compositor, CompositionSurfaceBrush imagebrush, CompositionSurfaceBrush secondbrush, ComplexEffects kind, float[] initialvalues, out IEnumerable<string> parameters)
        {
            IGraphicsEffect effect = null;

            switch (kind)
            {
                case ComplexEffects.Arithmetic:
                    effect = new ArithmeticCompositeEffect
                    {
                        Name = "effect",
                        ClampOutput = false,
                        Source1 = new CompositionEffectSourceParameter("Image"),
                        Source2 = new CompositionEffectSourceParameter("SecondImage"),
                        MultiplyAmount = initialvalues[0],
                        Source1Amount = initialvalues[1],
                        Source2Amount = initialvalues[2],
                        Offset = initialvalues[3]
                    };
                    parameters = new[] { "effect.MultiplyAmount", "effect.Source1Amount", "effect.Source2Amount", "effect.Offset" };
                    break;
                default:
                    parameters = new string[0];
                    break;
            }

            var effectbrush = compositor.CreateEffectFactory(effect, parameters).CreateBrush();
            effectbrush.SetSourceParameter("Image", imagebrush);
            effectbrush.SetSourceParameter("SecondImage", secondbrush);

            return effectbrush;
        }

Thank you for the patience and documentation (including the videos)

**Comment by krenner** [comment]
@juanpaexpedite You can use a Transform2DEffect as input to a CompositeEffect, setting the mask as source to the Tranform2D effect, and animate.  A simpler solution would be to use SceneLighting.  Looking at your image and mask I think you want a shimmer of light to traverse across the image?  You can achieve this by creating a light and animating the offset.  You do not need an EffectBrush to create a light (Compositor.CreatePointLight) The TextShimmer sample in the Sample Gallery showcases this type of UI treatment.

**Comment by juanpaexpedite** [comment]
Ok, thank you a lot for the answers. About the performance of using SceneLighting in mobile, does it works smooth?, at this moment my Lumia 1320 has only 10586 so I cannot test. I will try the transform2D and when I can deploy the lighting. Than you
