### ISSUE TITLE
Unhandled exception with Visual.Children.InsertAtTop()

### ISSUE THREAD

**Issue by JustinXinLiu** [Microsoft/WindowsUIDevLabs#88]
I got this error message in one of the inside builds and after upgrading to *14332* the issue was gone.

> An unhandled exception of type 'System.AccessViolationException' occurred in Six2Seven.exe
> 
> Additional information: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

The error is attached to this line -

`_clockFaceVisual.Children.InsertAtTop(tickVisual);`

Yesterday I upgraded to the latest *14342* and the issue now comes back. I cannot really think of any reason why the code wouldn't work so I guess it's a bug?

Also I just noticed that if I run the app without the debugger, it loads up fine. So the code is definitely OK.

**Comment by ratishphilip** [comment]
@JustinXinLiu 
Have you unchecked the [**Enable UI Debugging Tools for XAML**](https://twitter.com/Clarkezone/status/726075757127045121)?

**Comment by JustinXinLiu** [comment]
@ratishphilip You're right! After turning it off it's working now. Not sure how it was reset to default though. Many thanks!!
