### ISSUE TITLE
Vector3 animations not running

### ISSUE THREAD

**Issue by aL3891** [Microsoft/WindowsUIDevLabs#89]
I'm having problems with vector3 animations not running in build 14342, even in the sample gallery, the following code from the perspective sample doesn't seem to do anything:

            Vector3KeyFrameAnimation offsetAnimation = compositor.CreateVector3KeyFrameAnimation();
            offsetAnimation.InsertKeyFrame(0.0f, new Vector3(0, 0, 0));
            offsetAnimation.InsertKeyFrame(0.5f, new Vector3(0, 0, -2000));
            offsetAnimation.InsertKeyFrame(1.0f, new Vector3(0, 0, 0));
            offsetAnimation.Duration = TimeSpan.FromMilliseconds(8000);
            offsetAnimation.IterationBehavior = AnimationIterationBehavior.Forever;
            visual.StartAnimation("Offset", offsetAnimation);

Is this a known issue or am I missing something?

**Comment by JustinXinLiu** [comment]
I am having the exact same issue. One `Visual` works and the other doesn't. The code is almost identical.

**Comment by JustinXinLiu** [comment]
Looks like it works if I put a short delay (1 second) before kicking off the `Offset` animation. This tells me the system might be doing some `Offset` calculation and the code has to wait until that finishes before doing any `Offset` related animations...

**Comment by shandilvarun** [comment]
Hi, is this specific offset animation not working or any Vector3 animation not working for you guys? 
Is it the sample that is not working? or any Vector3 animation?

**Comment by aL3891** [comment]
The code is from the perspective sample in the sample gallery in this repo. for me at least none of the vector3 animations in that sample runs, but I havent looked around extensively in the other ones. The rotation animation in that sample works fine though

**Comment by likuba** [comment]
Thanks for letting us know about the broken sample.

I think you are hitting issues based on the updated behavior of XAML-Composition property synchronization (https://github.com/Microsoft/WindowsUIDevLabs/wiki/XAML-Composition-Property-Synchronization-Changes)

The issue here is that XAML and Composition will "clobber" each other (last one wins) if they both try updating the same property.  This means that setting XAML properties that cause layout to run will break the animation binding unless you start the animation after layout has run.  If you try wrapping the textbox in a canvas and removing the margin from the textbox does it animate?  That would confirm that this is the issue being hit.

**Comment by aL3891** [comment]
hmm i tried doing this but it doenst seem to work, at least not for text boxes, allthough it does seem to work for the image though

**Comment by likuba** [comment]
Thanks @aL3891 for trying this out.

Did you make sure to also remove the margin from the textbox in addition to adding the canvas? The other suggestion is to add a border to the textbox and put the margin there.  Does that help?

Thanks for bearing with us on this one--we are still working on getting the full set of cases where this impacts animations tracked with info on how to make it work for those cases.

**Comment by aL3891** [comment]
This is what I have now, the images moves around but none of the textboxes does.. does the fix work for you? 

    <StackPanel x:Name="MyPanel" Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
        <Canvas>
            <TextBlock Text="Example 1 - Animate a visual's Z offset"
                   TextWrapping="WrapWholeWords"
                   FontWeight="Bold"
                   />
                   <TextBlock x:Name="TextBlock1" 
                   Text="Watch me animate towards the vanishing point and back again"
                   TextWrapping="Wrap"
                   />
            </Canvas>
            <Canvas>
                <TextBlock Text="Example 2 - Rotate a visual with perspective, Z offset = 200"
                TextWrapping="WrapWholeWords"
                FontWeight="Bold"/>
                <Image x:Name="RotatedImage" Source="ms-appx:///Samples/SDK 10586/Perspective/jellyfish.jpg" Width="300" Height="100" Stretch="Fill"/>
                </Canvas>
            </StackPanel>

**Comment by aL3891** [comment]
Adding a border around the text box didn't work either unfortunately

**Comment by likuba** [comment]
As a heads up--this is actually now fixed for the perspective sample if you look at the updated markup for that one :)

The current behavior of layout/Composition being "last one wins" is the planned behavior for shipping in this update to Windows.  We'll be continuing to improve the interop story with XAML over the next few releases though and this behavior change now was made to set us up for better long term options.  I know that it is a bit vague, but hopefully it helps explain why there is a bit of pain now.

**Comment by aL3891** [comment]
Allright, thanks for the update, looking forward to those long term options because the current setup with wrapping is a bit of a hassle :)
