### ISSUE TITLE
EasingFunctions

### ISSUE THREAD

**Issue by ratishphilip** [Microsoft/WindowsUIDevLabs#91]
It would be great if you could add more Easing Functions to Composition (similar to the ones available in XAML) with an option to specify whether they are **EaseIn** or **EaseOut** functions.

Also could you provide some more details about how **CubicBezierEasingFunction** should be used. How should the two **Vector2** arguments be calculated?

**Comment by patsiu** [comment]
@ratishphilip Yup, we're looking into providing easier access to different easing functions, particularly the Penner Equations. You can also generate the EaseIn, EaseOut, EaseInOut variations for a number of the Penner Equations using a Cubic Bezier with the exception of more complicated ones like Elastic and Bounce.

When constructing a Cubic Bezier, you provide two different control points that define the curve/form of the easing function. These control points are of type Vector2. I use [this website](http://cubic-bezier.com/#0,-0.01,.48,.99) to visualize what kind of curve my control points generate.

**Comment by tomzorz** [comment]
There was already a question about this - https://github.com/Microsoft/WindowsUIDevLabs/issues/36#issuecomment-200569775 although, I think this is feedback on the lack of proper documentation.

**Comment by ratishphilip** [comment]
@tomzorz I must have missed that. Thanks for pointing it out.
@patsiu thanks for the link.
Yeah I agree, a strong and detailed documentation is what is missing most in Composition.
