### ISSUE TITLE
How Backdrop captures parent and get UIElement brush to use in other effects 

### ISSUE THREAD

**Issue by juanpaexpedite** [Microsoft/WindowsUIDevLabs#94]
I am trying to realize out how backdrop works because in the example I do not find how it is joined to the parent Grid to apply the effect, does it do internally finding its parent? I cannot find if it's defined by code.

And then taking this into account, Is there a way to take an UIElement as source of an Effect brush? or as source of CreateMaskBrush?

Might be I am missing something, thank you a lot for the patience.

**Comment by krenner** [comment]
@juanpaexpedite BackdropBrush applies the set effect to whatever is drawn or rendered underneath its visual.  You can not explicitly take a UIElement as input to an EffectBursh.  The BasicXAMLInterop sample in our gallery has comments regarding ElementCompositionPreview.

**Comment by juanpaexpedite** [comment]
Understood, thank you with also the information about the CompositionImage control it is enough to understand this better, thank you
