### ISSUE TITLE
Question: Custom shaped visuals

### ISSUE THREAD

**Issue by ratishphilip** [Microsoft/WindowsUIDevLabs#95]
Is it possible to create custom shaped visuals (which can be defined using geometry or combined geometries) like **CanvasGeometry** in **Win2d**?

I need to achieve the following scenario:
I have a rectangle (say **Parent**) inside which is another rectangle (say **Child**). Now I need to create a visual which includes the **Parent** area but excludes the **Child** area and fill the "combined" area with a Backdrop brush. The area occupied by the **Child** remains transparent.

Is it possible?

If it is not, then is there a way to create a **CanvasGeometry** and fill it with a **BackdropBrush**?

**Comment by ratishphilip** [comment]
@krenner @msftdavid 
I have created a solution for this issue - [**CompositionProToolkit**](https://github.com/ratishphilip/CompositionProToolkit). It allows you to create custom shaped Visuals using **CanvasGeometry**.
It is based on @robmikh 's [**CompositionImageLoader**](https://github.com/robmikh/compositionimageloader)

It would be great if you could check it out.

**Comment by sohchatt** [comment]
My apologies for the delay in replying to your issue. I was going to say that while we do not support custom shaped visuals in the WindowsUIComposition APIs today, a possible solution for your case would be to draw CanvasGeometry using Win2d to a CompositionDrawingSurface and create a CompositionSurfaceBrush with it. Use this SurfaceBrush as the source to a CompositionMaskBrush if you want to use it as a mask only. If your scenario also involves chaining effects, you may want to set the SurfaceBrush as the source parameter to an AlphaMask effect and chain the AlphaMask effect with a BackdropBrush (or any other) effect if necessary. And so and so forth. But you beat me to it by creating an entire toolkit!
 
I checked out CompositionProToolkit and it looks great (and easy to use)!

**Comment by ratishphilip** [comment]
@sohchatt Thanks for the reply.
I have another question related to this issue. It would be great if you could help me out.

It is similar to the scenario I mentioned earlier
I have a rectangle (say **Parent**) inside which is another rectangle (say **Child**). Now I create a **CanvasGeometry** by excluding the **Child** area from the **Parent** area. I create a maskbrush based on this **CanvasGeometry**. 
Now the thing is, the Child area rotates at irregular intervals. And each time the rotation happens, I need to recalculate the CanvasGeometry and update the mask.
So my question is, is there a way to animate the change of value of rotation of the Child area (an thus the recalculation of the mask) just like the way a **Visual**'s **RotationAngleInDegrees** property can be animated. (maybe I could add the angle in a **CompositionPropertySet** and animate it. But I cannot figure out a way how to bind the value in the **CompositionPropertySet** to a non-Composition entity)

**Comment by ratishphilip** [comment]
Closing this issue as my questions were answered by @robmikh  in #102
