### ISSUE TITLE
APIs (SDK 14332) broken in Build 14352?

### ISSUE THREAD

**Issue by JustinXinLiu** [Microsoft/WindowsUIDevLabs#96]
I am trying to run the *Pull to Animate* sample from the sample gallery and it's throwing me with errors like -

> Additional information: Method not found: 'Windows.UI.Composition.CompositionBackdropBrush Windows.UI.Composition.Compositor.CreateBackdropBrush()'.

> Additional information: Could not find Windows Runtime type 'Windows.UI.Composition.Interactions.InteractionTracker'.

Looks like these methods are somehow missing but the project does compile fine.

**Comment by likuba** [comment]
Hi Justin--

Thanks for taking the time to file this one.  We are not able to repro locally, so I have a few quick questions.  Are you able to use either of these APIs in your own sample projects without seeing these issues?  If so, have you checked that you are building against the correct SDK in Visual Studio?

Thanks!

**Comment by JustinXinLiu** [comment]
I created a band new project and both Target and Min version of it are set to Build 14332. Maybe something got corrupted?

**Comment by likuba** [comment]
Thanks for confirming @JustinXinLiu 

Are you also running your machine on Build 14332, or did you get the most recent flight last week?  We suspect this could be an issue related to the fact that the most recently flighted build did not go out with a matching SDK.

**Comment by JustinXinLiu** [comment]
Sorry should be more specific about the title. It's indeed running on the latest Build 14352. So I guess I will have to wait for the next one. Thanks Lindsay!

**Comment by Seanalex** [comment]
Having the same issue. Will wait for the next one. Looking forward to the updates!

**Comment by JustinXinLiu** [comment]
Looks like these issues still haven't been fixed in the new build *14361* released earlier today? Been waiting for a new build for weeks and still no fix. :(

**Comment by likuba** [comment]
Hey @JustinXinLiu 

Thanks for checking so quickly.  We haven't been able to repro this locally, so I'll give it another shot on the builds you called out and see if we can understand what is going wrong.

Just to confirm:
With SDK 14332 and build 14361 you are seeing everything compile fine but in the sample gallery as well as new projects when you actually run the app you are getting errors around everything InteractionTracker and BackdropBrush?

**Comment by JustinXinLiu** [comment]
Hi @likuba,

With SDK *14332* and the build **prior to** *14361*, I was able to run the sample gallery project but it crashed when I went to certain parts that used `InteractionTracker` or `BackdropBrush` (there could be more things broken as I only tested these two).

After I upgraded to *14361*, the project still complies fine but it throws me an error as soon as I run it.
![comp bug](https://cloud.githubusercontent.com/assets/1710184/15916307/ba8a06e2-2e34-11e6-948c-f698d4b1987d.PNG)

**Comment by h82258652** [comment]
pc build 14342 could not run the demo too.
![qq 20160609124935](https://cloud.githubusercontent.com/assets/5144550/15919152/18c45a94-2e41-11e6-90c1-062987345e51.png)

**Comment by robmikh** [comment]
@JustinXinLiu Hey Justin, do you have SDK 14295 installed at all? I've got a VM running with the newest build and installed SDK 14332 but I can't reproduce your issue. I've seen cases in the past where even if the newer SDK is selected, the older SDK is used instead if installed. It's been awhile since I've seen it though, but it might be worth a shot.

@h82258652 You're running into a known issue that you can find guidance about [here](https://github.com/Microsoft/WindowsUIDevLabs/wiki/Insider-FAST#known-issues). TL;DR: You need to disable Live Visual Tree Debugging in Visual Studio.

**Comment by h82258652** [comment]
@robmikh 
Thanks a lot, it can run now.
And I try the ConnectedAnimation demo, I found when I navigate back, the image will flicker.

**Comment by JustinXinLiu** [comment]
@robmikh ahh THAT IS IT!! After I removed *14295* it's all working fine. Now I can get back to my experiment. :) Thanks heaps!

**Comment by robmikh** [comment]
@JustinXinLiu  No problem! :)

@h82258652 Could you open a new issue with what you've found? It makes it much easier for us to see what problems people are having and to keep track of who we have and have not helped.
