### ISSUE TITLE
Additional requirements for ConnectedAnimationService animations?

### ISSUE THREAD

**Issue by limefrogyank** [Microsoft/WindowsUIDevLabs#97]
I'm trying to use the ConnectedAnimationService almost the same way that the sample does.  In my case, I have a Grid UIElement that has a set of custom Visuals in a ContainerVisual that I want to animate during the transition.  I have tried to attach just the placeholder grid that contains the visuals when I call ConnectedAnimationService.GetForCurrentView().PrepareToAnimate.  I have also tried to attach the larger UserControl that contains the Visuals...

When I get to my new page and call ConnectedAnimationService.GetForCurrentView().GetAnimation, my animation is still null. 

So what other requirements are necessary to get this to work?  I have the preview SDK and all the samples work fine...

**Comment by JasterAtMicrosoft** [comment]
Hi @limefrogyank,

Could you please confirm that you are setting the size of your UIElement to the size of the Visual content? (You can query the value of Grid.ActualWidth and Grid.ActualHeight to check on this.) There is a known limitation where ConnectedAnimationService will not automatically take into account the size of visual layer content when setting up the animation.

**Comment by limefrogyank** [comment]
Yes, they do have values.  The following is literally what I'm using.  

GridView_ItemClicked event:

    var seriesItem = e.ClickedItem as SeriesItem;
    container = ((GridView)sender).ContainerFromItem(e.ClickedItem) as GridViewItem;
    if (container != null)
    {
        var root = (FrameworkElement)container.ContentTemplateRoot;
        var posterItem = (UserControls.SeriesPosterControl)root.FindName("seriesPosterControl");
        seriesItem.lastPosterUsed = posterItem.lastPosterUsed;
        var image = (UIElement)root.FindName("placeHolder");

         var animation = ConnectedAnimationService.GetForCurrentView().PrepareToAnimate("PosterImage", posterItem);
    }

OnNavigatedTo event:

     var animation = ConnectedAnimationService.GetForCurrentView().GetAnimation("PosterImage");

And the animation is null... I thought it might have something to do with the NavigationCacheMode since I was disabling it, but that's not it.

**Comment by JasterAtMicrosoft** [comment]
Thanks! I don't see anything wrong with your usage pattern. If possible could you attach a project that reproduces the issue?

**Comment by limefrogyank** [comment]
I'll modify the working sample to use one of the UserControls I have in my project.  It changes the image on a timer and uses Visuals to do a crossfade effect, instead of animating it using xaml.  Perhaps I'm doing something weird... I'll investigate more.

**Comment by limefrogyank** [comment]
Ah, it was something weird that I did.  In my case, I had installed the Visual Studio 2015 update 2 sometime between creating the project and then working on the transitions.  While the app still compiled and ran, there were huge problems like NuGet being gone entirely from Visual Studio.  I reinstalled it and then my app starting using ConnectedAnimationService correctly.

Sorry, but thanks for the quick response anyways!

**Comment by limefrogyank** [comment]
FYI, for anyone else with this problem, these animations will NOT work using a remote desktop connection.  I knew this, so it wasn't my problem, but I like to work on the preview SDK using a spare tablet and it's easier to work using my desktop.  I just have to preview the animations directly.

**Comment by JasterAtMicrosoft** [comment]
As an FYI, you should be able to work around animations not playing on remote desktop by enabling "Play animations in Windows" in Settings -> Other Ease of Access Settings. This is an accessibility setting that the platform honors when possible, and it's also disabled by default to save resources on remote desktop. However, animations tend to not look great on remote desktop anyway since there are a lot of dropped frames.
