### ISSUE TITLE
Can we do Composition effects in XAML (without c#)

### ISSUE THREAD

**Issue by abhilashca** [Microsoft/WindowsUIDevLabs#98]
Hello,

Is it possible to do Composition effects fully in XAML the same way writing a storyboard animation using Blend?

Thanks.

**Comment by tomzorz** [comment]
@abhilashca Not right now, but I'm working on a library to do just that :)

**Comment by JasterAtMicrosoft** [comment]
What kind of effects are you interested in using specifically? We have some helpers in this repo for using Composition technologies in XAML markup as well.

**Comment by abhilashca** [comment]
@tomzorz Glad to hear that a library is on it's way. Will be really helpful.

@JasterAtMicrosoft  We have an integration team whose main role is to beautify XAML with cool styling,  animations and transitions which is fully done in Blend and with very very less C# code. Composition API, at the moment, can be created using C# only. Correct? This will require our team to write more c# code, which is not a choice at the moment. I am glad to know that a library is on it's way.

Thanks a lot for your valuable reply.

**Comment by JasterAtMicrosoft** [comment]
@abhilashca Yes that is correct. Thanks for the feedback and for your interest in the platform! We are aware that use of code-behind is not great for traditional XAML design integrator workflows, and are tracking this area for potential improvement in a future release. In the meantime, Storyboard animations authored in Blend are still a fine solution for most animation scenarios, and for advanced animations and effects using Composition, libraries like the one @tomzorz is working on should help out quite a bit!
