### ISSUE TITLE
 Build 14361 problem with BackDrop control

### ISSUE THREAD

**Issue by ericgrover** [Microsoft/WindowsUIDevLabs#99]
I just installed Build 14361, and there appears to be a breaking change that has caused the backdrop control to stop working. I now get the exception: "Attempted to read or write protected memory. This is often an indication that other memory is corrupt." on line 48 ElementCompositionPreview.SetElementChildVisual(this as UIElement, m_blurVisual);

**Comment by robmikh** [comment]
Strange, I haven't hit this yet on the newest build. Do you have the Live Visual Tree debugging tool enabled? Could you try turning it off if you have it on?

Is this just in the Sample Gallery, or are you using it in your own app?

**Comment by patsiu** [comment]
hey @ericgrover, try turning the Live Visual Tree debugging off like @robmikh mentioned. I believe you are hitting a known issue we have with ElementCompositionPreview with this Insider Build. Let us know if this fixes your issue.

**Comment by ericgrover** [comment]
It was the Live Visual Tree.  I turned it off and it fixed the bug.  Thanks!
